// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_inventory_poll_runs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAccountInventoryPollRun = `-- name: ClaimAccountInventoryPollRun :one
SELECT public.control_claim_account_inventory_poll_run(
    $1::uuid,
    $2::integer
)::jsonb AS claim_result
`

type ClaimAccountInventoryPollRunParams struct {
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
	LeaseSeconds      int32       `json:"lease_seconds"`
}

func (q *Queries) ClaimAccountInventoryPollRun(ctx context.Context, arg ClaimAccountInventoryPollRunParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, claimAccountInventoryPollRun, arg.LeaseFencingToken, arg.LeaseSeconds)
	var claim_result []byte
	err := row.Scan(&claim_result)
	return claim_result, err
}

const finalizeAccountInventoryPollRun = `-- name: FinalizeAccountInventoryPollRun :one
SELECT poll_run_id, instance_id, node_type, driver_contract_version, scheduled_at, provider_policy_version, status, attempt_count, max_attempts, poll_start_grace_seconds, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, finalized_at, abandoned_at, execution_reason, observed_at, transport_success, response_shape_valid, contract_valid, inventory_mode, node_identity_complete, snapshot_complete, degraded, result, reason, source_record_count, identifiable_record_count, unidentified_record_count, unsupported_provider_count, out_of_scope_provider_count, node_version, node_commit FROM public.control_finalize_account_inventory_poll_run(
    $1::uuid,
    $2::uuid,
    $3::boolean,
    $4::boolean,
    $5::boolean,
    $6::text,
    $7::boolean,
    $8::boolean,
    $9::boolean,
    $10::text,
    $11::text,
    $12::integer,
    $13::integer,
    $14::integer,
    $15::integer,
    $16::integer,
    $17::text,
    $18::text,
    $19::jsonb
)
`

type FinalizeAccountInventoryPollRunParams struct {
	PollRunID                pgtype.UUID `json:"poll_run_id"`
	LeaseFencingToken        pgtype.UUID `json:"lease_fencing_token"`
	TransportSuccess         bool        `json:"transport_success"`
	ResponseShapeValid       bool        `json:"response_shape_valid"`
	ContractValid            bool        `json:"contract_valid"`
	InventoryMode            pgtype.Text `json:"inventory_mode"`
	NodeIdentityComplete     bool        `json:"node_identity_complete"`
	SnapshotComplete         bool        `json:"snapshot_complete"`
	Degraded                 bool        `json:"degraded"`
	Result                   string      `json:"result"`
	Reason                   string      `json:"reason"`
	SourceRecordCount        int32       `json:"source_record_count"`
	IdentifiableRecordCount  int32       `json:"identifiable_record_count"`
	UnidentifiedRecordCount  int32       `json:"unidentified_record_count"`
	UnsupportedProviderCount int32       `json:"unsupported_provider_count"`
	OutOfScopeProviderCount  int32       `json:"out_of_scope_provider_count"`
	NodeVersion              string      `json:"node_version"`
	NodeCommit               string      `json:"node_commit"`
	ProviderResults          []byte      `json:"provider_results"`
}

func (q *Queries) FinalizeAccountInventoryPollRun(ctx context.Context, arg FinalizeAccountInventoryPollRunParams) (AccountInventoryPollRun, error) {
	row := q.db.QueryRow(ctx, finalizeAccountInventoryPollRun,
		arg.PollRunID,
		arg.LeaseFencingToken,
		arg.TransportSuccess,
		arg.ResponseShapeValid,
		arg.ContractValid,
		arg.InventoryMode,
		arg.NodeIdentityComplete,
		arg.SnapshotComplete,
		arg.Degraded,
		arg.Result,
		arg.Reason,
		arg.SourceRecordCount,
		arg.IdentifiableRecordCount,
		arg.UnidentifiedRecordCount,
		arg.UnsupportedProviderCount,
		arg.OutOfScopeProviderCount,
		arg.NodeVersion,
		arg.NodeCommit,
		arg.ProviderResults,
	)
	var i AccountInventoryPollRun
	err := row.Scan(
		&i.PollRunID,
		&i.InstanceID,
		&i.NodeType,
		&i.DriverContractVersion,
		&i.ScheduledAt,
		&i.ProviderPolicyVersion,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.PollStartGraceSeconds,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.FinalizedAt,
		&i.AbandonedAt,
		&i.ExecutionReason,
		&i.ObservedAt,
		&i.TransportSuccess,
		&i.ResponseShapeValid,
		&i.ContractValid,
		&i.InventoryMode,
		&i.NodeIdentityComplete,
		&i.SnapshotComplete,
		&i.Degraded,
		&i.Result,
		&i.Reason,
		&i.SourceRecordCount,
		&i.IdentifiableRecordCount,
		&i.UnidentifiedRecordCount,
		&i.UnsupportedProviderCount,
		&i.OutOfScopeProviderCount,
		&i.NodeVersion,
		&i.NodeCommit,
	)
	return i, err
}

const getAccountInventoryPollRun = `-- name: GetAccountInventoryPollRun :one
SELECT poll_run_id, instance_id, node_type, driver_contract_version, scheduled_at, provider_policy_version, status, attempt_count, max_attempts, poll_start_grace_seconds, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, finalized_at, abandoned_at, execution_reason, observed_at, transport_success, response_shape_valid, contract_valid, inventory_mode, node_identity_complete, snapshot_complete, degraded, result, reason, source_record_count, identifiable_record_count, unidentified_record_count, unsupported_provider_count, out_of_scope_provider_count, node_version, node_commit
FROM account_inventory_poll_runs
WHERE poll_run_id = $1::uuid
`

func (q *Queries) GetAccountInventoryPollRun(ctx context.Context, pollRunID pgtype.UUID) (AccountInventoryPollRun, error) {
	row := q.db.QueryRow(ctx, getAccountInventoryPollRun, pollRunID)
	var i AccountInventoryPollRun
	err := row.Scan(
		&i.PollRunID,
		&i.InstanceID,
		&i.NodeType,
		&i.DriverContractVersion,
		&i.ScheduledAt,
		&i.ProviderPolicyVersion,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.PollStartGraceSeconds,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.FinalizedAt,
		&i.AbandonedAt,
		&i.ExecutionReason,
		&i.ObservedAt,
		&i.TransportSuccess,
		&i.ResponseShapeValid,
		&i.ContractValid,
		&i.InventoryMode,
		&i.NodeIdentityComplete,
		&i.SnapshotComplete,
		&i.Degraded,
		&i.Result,
		&i.Reason,
		&i.SourceRecordCount,
		&i.IdentifiableRecordCount,
		&i.UnidentifiedRecordCount,
		&i.UnsupportedProviderCount,
		&i.OutOfScopeProviderCount,
		&i.NodeVersion,
		&i.NodeCommit,
	)
	return i, err
}

const listAccountInventoryPollProviderResults = `-- name: ListAccountInventoryPollProviderResults :many
SELECT poll_run_id, provider, identifiable_count, missing_identity_count, duplicate_identity_count, identity_complete, snapshot_complete, degraded, reason
FROM account_inventory_poll_provider_results
WHERE poll_run_id = $1::uuid
ORDER BY provider
`

func (q *Queries) ListAccountInventoryPollProviderResults(ctx context.Context, pollRunID pgtype.UUID) ([]AccountInventoryPollProviderResult, error) {
	rows, err := q.db.Query(ctx, listAccountInventoryPollProviderResults, pollRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountInventoryPollProviderResult{}
	for rows.Next() {
		var i AccountInventoryPollProviderResult
		if err := rows.Scan(
			&i.PollRunID,
			&i.Provider,
			&i.IdentifiableCount,
			&i.MissingIdentityCount,
			&i.DuplicateIdentityCount,
			&i.IdentityComplete,
			&i.SnapshotComplete,
			&i.Degraded,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountInventoryPollRunMetrics = `-- name: ListAccountInventoryPollRunMetrics :many
WITH current_slot AS (
    SELECT to_timestamp(floor(extract(epoch FROM clock_timestamp()) / 300) * 300) AS scheduled_at
), latest AS (
    SELECT DISTINCT ON (run.instance_id)
        run.instance_id,
        run.status,
        run.scheduled_at,
        run.created_at,
        run.first_started_at,
        run.last_started_at
    FROM account_inventory_poll_runs AS run
    ORDER BY run.instance_id, run.scheduled_at DESC
), latest_finalized AS (
    SELECT DISTINCT ON (run.instance_id)
        run.instance_id,
        run.scheduled_at,
        run.transport_success,
        run.contract_valid
    FROM account_inventory_poll_runs AS run
    WHERE run.status = 'finalized'
    ORDER BY run.instance_id, run.scheduled_at DESC
)
SELECT
    latest.instance_id,
    latest.status,
    latest.scheduled_at,
    greatest(0, extract(epoch FROM (
        current_slot.scheduled_at - coalesce(latest_finalized.scheduled_at, latest.scheduled_at)
    )))::double precision AS scheduler_lag_seconds,
    greatest(0, extract(epoch FROM (
        coalesce(latest.last_started_at, clock_timestamp()) - latest.created_at
    )))::double precision AS queue_wait_seconds,
    (latest.first_started_at IS NOT NULL)::boolean AS poll_started,
    coalesce(greatest(0, extract(epoch FROM (
        latest.first_started_at - latest.scheduled_at
    ))), 0)::double precision AS poll_start_lag_seconds,
    latest_finalized.transport_success,
    latest_finalized.contract_valid
FROM latest
CROSS JOIN current_slot
LEFT JOIN latest_finalized USING (instance_id)
ORDER BY latest.instance_id
`

type ListAccountInventoryPollRunMetricsRow struct {
	InstanceID          pgtype.UUID        `json:"instance_id"`
	Status              string             `json:"status"`
	ScheduledAt         pgtype.Timestamptz `json:"scheduled_at"`
	SchedulerLagSeconds float64            `json:"scheduler_lag_seconds"`
	QueueWaitSeconds    float64            `json:"queue_wait_seconds"`
	PollStarted         bool               `json:"poll_started"`
	PollStartLagSeconds float64            `json:"poll_start_lag_seconds"`
	TransportSuccess    pgtype.Bool        `json:"transport_success"`
	ContractValid       pgtype.Bool        `json:"contract_valid"`
}

func (q *Queries) ListAccountInventoryPollRunMetrics(ctx context.Context) ([]ListAccountInventoryPollRunMetricsRow, error) {
	rows, err := q.db.Query(ctx, listAccountInventoryPollRunMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountInventoryPollRunMetricsRow{}
	for rows.Next() {
		var i ListAccountInventoryPollRunMetricsRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.Status,
			&i.ScheduledAt,
			&i.SchedulerLagSeconds,
			&i.QueueWaitSeconds,
			&i.PollStarted,
			&i.PollStartLagSeconds,
			&i.TransportSuccess,
			&i.ContractValid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountInventoryProviderMetrics = `-- name: ListAccountInventoryProviderMetrics :many
WITH latest_finalized AS (
    SELECT DISTINCT ON (run.instance_id)
        run.instance_id, run.poll_run_id
    FROM account_inventory_poll_runs AS run
    WHERE run.status = 'finalized'
    ORDER BY run.instance_id, run.scheduled_at DESC
)
SELECT latest_finalized.instance_id, result.provider, result.snapshot_complete
FROM latest_finalized
JOIN account_inventory_poll_provider_results AS result
  ON result.poll_run_id = latest_finalized.poll_run_id
ORDER BY latest_finalized.instance_id, result.provider
`

type ListAccountInventoryProviderMetricsRow struct {
	InstanceID       pgtype.UUID `json:"instance_id"`
	Provider         string      `json:"provider"`
	SnapshotComplete bool        `json:"snapshot_complete"`
}

func (q *Queries) ListAccountInventoryProviderMetrics(ctx context.Context) ([]ListAccountInventoryProviderMetricsRow, error) {
	rows, err := q.db.Query(ctx, listAccountInventoryProviderMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountInventoryProviderMetricsRow{}
	for rows.Next() {
		var i ListAccountInventoryProviderMetricsRow
		if err := rows.Scan(&i.InstanceID, &i.Provider, &i.SnapshotComplete); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileAccountInventoryPollRun = `-- name: ReconcileAccountInventoryPollRun :one
SELECT poll_run_id, instance_id, node_type, driver_contract_version, scheduled_at, provider_policy_version, status, attempt_count, max_attempts, poll_start_grace_seconds, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, finalized_at, abandoned_at, execution_reason, observed_at, transport_success, response_shape_valid, contract_valid, inventory_mode, node_identity_complete, snapshot_complete, degraded, result, reason, source_record_count, identifiable_record_count, unidentified_record_count, unsupported_provider_count, out_of_scope_provider_count, node_version, node_commit FROM public.control_reconcile_account_inventory_poll_run(
)
`

func (q *Queries) ReconcileAccountInventoryPollRun(ctx context.Context) (AccountInventoryPollRun, error) {
	row := q.db.QueryRow(ctx, reconcileAccountInventoryPollRun)
	var i AccountInventoryPollRun
	err := row.Scan(
		&i.PollRunID,
		&i.InstanceID,
		&i.NodeType,
		&i.DriverContractVersion,
		&i.ScheduledAt,
		&i.ProviderPolicyVersion,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.PollStartGraceSeconds,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.FinalizedAt,
		&i.AbandonedAt,
		&i.ExecutionReason,
		&i.ObservedAt,
		&i.TransportSuccess,
		&i.ResponseShapeValid,
		&i.ContractValid,
		&i.InventoryMode,
		&i.NodeIdentityComplete,
		&i.SnapshotComplete,
		&i.Degraded,
		&i.Result,
		&i.Reason,
		&i.SourceRecordCount,
		&i.IdentifiableRecordCount,
		&i.UnidentifiedRecordCount,
		&i.UnsupportedProviderCount,
		&i.OutOfScopeProviderCount,
		&i.NodeVersion,
		&i.NodeCommit,
	)
	return i, err
}

const scheduleCurrentAccountInventoryPollRuns = `-- name: ScheduleCurrentAccountInventoryPollRuns :one
SELECT public.control_schedule_account_inventory_poll_runs(
    $1::integer,
    $2::integer,
    $3::integer,
    $4::integer
)::jsonb AS schedule_result
`

type ScheduleCurrentAccountInventoryPollRunsParams struct {
	PeriodSeconds         int32 `json:"period_seconds"`
	PollStartGraceSeconds int32 `json:"poll_start_grace_seconds"`
	MaxAttempts           int32 `json:"max_attempts"`
	ScheduleLimit         int32 `json:"schedule_limit"`
}

func (q *Queries) ScheduleCurrentAccountInventoryPollRuns(ctx context.Context, arg ScheduleCurrentAccountInventoryPollRunsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, scheduleCurrentAccountInventoryPollRuns,
		arg.PeriodSeconds,
		arg.PollStartGraceSeconds,
		arg.MaxAttempts,
		arg.ScheduleLimit,
	)
	var schedule_result []byte
	err := row.Scan(&schedule_result)
	return schedule_result, err
}
