// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_inventory_history.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAccountInventoryHistoryCompatibility = `-- name: CheckAccountInventoryHistoryCompatibility :one
SELECT public.control_history_schema_compatibility_v1()::jsonb AS compatibility
`

func (q *Queries) CheckAccountInventoryHistoryCompatibility(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, checkAccountInventoryHistoryCompatibility)
	var compatibility []byte
	err := row.Scan(&compatibility)
	return compatibility, err
}

const claimAccountInventoryHistoryCompaction = `-- name: ClaimAccountInventoryHistoryCompaction :one
SELECT
    claim.compaction_run_id,
    claim.summary_date,
    claim.instance_id,
    claim.provider_policy_version,
    claim.status,
    claim.failed_from,
    claim.claim_owner,
    claim.lease_expires_at,
    claim.fencing_token,
    claim.attempt_count,
    claim.checksum_version,
    claim.source_snapshot_count,
    claim.source_poll_count,
    claim.source_provider_result_count,
    claim.source_duplicate_count,
    claim.source_checksum,
    claim.deleted_snapshot_count,
    claim.deleted_poll_count,
    claim.deleted_provider_result_count,
    claim.deleted_duplicate_count,
    claim.failure_reason,
    claim.created_at,
    claim.summarized_at,
    claim.deleting_at,
    claim.completed_at,
    claim.failed_at,
    claim.updated_at
FROM public.control_claim_account_inventory_compaction_v1(
    $1::uuid,
    $2::integer
) AS claim
`

type ClaimAccountInventoryHistoryCompactionParams struct {
	WorkerToken  pgtype.UUID `json:"worker_token"`
	LeaseSeconds int32       `json:"lease_seconds"`
}

func (q *Queries) ClaimAccountInventoryHistoryCompaction(ctx context.Context, arg ClaimAccountInventoryHistoryCompactionParams) (AccountInventoryCompactionRun, error) {
	row := q.db.QueryRow(ctx, claimAccountInventoryHistoryCompaction, arg.WorkerToken, arg.LeaseSeconds)
	var i AccountInventoryCompactionRun
	err := row.Scan(
		&i.CompactionRunID,
		&i.SummaryDate,
		&i.InstanceID,
		&i.ProviderPolicyVersion,
		&i.Status,
		&i.FailedFrom,
		&i.ClaimOwner,
		&i.LeaseExpiresAt,
		&i.FencingToken,
		&i.AttemptCount,
		&i.ChecksumVersion,
		&i.SourceSnapshotCount,
		&i.SourcePollCount,
		&i.SourceProviderResultCount,
		&i.SourceDuplicateCount,
		&i.SourceChecksum,
		&i.DeletedSnapshotCount,
		&i.DeletedPollCount,
		&i.DeletedProviderResultCount,
		&i.DeletedDuplicateCount,
		&i.FailureReason,
		&i.CreatedAt,
		&i.SummarizedAt,
		&i.DeletingAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimAccountInventoryHistoryDailyRollup = `-- name: ClaimAccountInventoryHistoryDailyRollup :one
SELECT
    claim.rollup_run_id,
    claim.summary_date,
    claim.instance_id,
    claim.status,
    claim.claim_owner,
    claim.lease_expires_at,
    claim.fencing_token,
    claim.completed_fencing_token,
    claim.attempt_count,
    claim.expected_segment_count,
    claim.completed_segment_count,
    claim.checksum_version,
    claim.segment_checksum,
    claim.failure_reason,
    claim.created_at,
    claim.completed_at,
    claim.failed_at,
    claim.updated_at
FROM public.control_claim_account_inventory_daily_rollup_v1(
    $1::uuid,
    $2::integer
) AS claim
`

type ClaimAccountInventoryHistoryDailyRollupParams struct {
	WorkerToken  pgtype.UUID `json:"worker_token"`
	LeaseSeconds int32       `json:"lease_seconds"`
}

func (q *Queries) ClaimAccountInventoryHistoryDailyRollup(ctx context.Context, arg ClaimAccountInventoryHistoryDailyRollupParams) (AccountInventoryDailyRollupRun, error) {
	row := q.db.QueryRow(ctx, claimAccountInventoryHistoryDailyRollup, arg.WorkerToken, arg.LeaseSeconds)
	var i AccountInventoryDailyRollupRun
	err := row.Scan(
		&i.RollupRunID,
		&i.SummaryDate,
		&i.InstanceID,
		&i.Status,
		&i.ClaimOwner,
		&i.LeaseExpiresAt,
		&i.FencingToken,
		&i.CompletedFencingToken,
		&i.AttemptCount,
		&i.ExpectedSegmentCount,
		&i.CompletedSegmentCount,
		&i.ChecksumVersion,
		&i.SegmentChecksum,
		&i.FailureReason,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeAccountInventoryHistoryCompaction = `-- name: CompleteAccountInventoryHistoryCompaction :one
SELECT public.control_complete_account_inventory_compaction_v1(
    $1::uuid,
    $2::uuid,
    $3::bytea
)::jsonb AS complete_result
`

type CompleteAccountInventoryHistoryCompactionParams struct {
	CompactionRunID  pgtype.UUID `json:"compaction_run_id"`
	FencingToken     pgtype.UUID `json:"fencing_token"`
	ExpectedChecksum []byte      `json:"expected_checksum"`
}

func (q *Queries) CompleteAccountInventoryHistoryCompaction(ctx context.Context, arg CompleteAccountInventoryHistoryCompactionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, completeAccountInventoryHistoryCompaction, arg.CompactionRunID, arg.FencingToken, arg.ExpectedChecksum)
	var complete_result []byte
	err := row.Scan(&complete_result)
	return complete_result, err
}

const deleteAccountInventoryCompactionRunRetention = `-- name: DeleteAccountInventoryCompactionRunRetention :one
SELECT public.control_delete_account_inventory_compaction_run_retention_v1(
    $1::integer
)::jsonb AS retention_result
`

func (q *Queries) DeleteAccountInventoryCompactionRunRetention(ctx context.Context, deleteLimit int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteAccountInventoryCompactionRunRetention, deleteLimit)
	var retention_result []byte
	err := row.Scan(&retention_result)
	return retention_result, err
}

const deleteAccountInventoryHistorySnapshotBatch = `-- name: DeleteAccountInventoryHistorySnapshotBatch :one
SELECT public.control_delete_account_inventory_snapshot_batch_v1(
    $1::uuid,
    $2::uuid,
    $3::integer
)::jsonb AS delete_result
`

type DeleteAccountInventoryHistorySnapshotBatchParams struct {
	CompactionRunID pgtype.UUID `json:"compaction_run_id"`
	FencingToken    pgtype.UUID `json:"fencing_token"`
	DeleteLimit     int32       `json:"delete_limit"`
}

func (q *Queries) DeleteAccountInventoryHistorySnapshotBatch(ctx context.Context, arg DeleteAccountInventoryHistorySnapshotBatchParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteAccountInventoryHistorySnapshotBatch, arg.CompactionRunID, arg.FencingToken, arg.DeleteLimit)
	var delete_result []byte
	err := row.Scan(&delete_result)
	return delete_result, err
}

const deleteAccountInventoryPollRetention = `-- name: DeleteAccountInventoryPollRetention :one
SELECT public.control_delete_account_inventory_poll_retention_v1(
    $1::integer
)::jsonb AS retention_result
`

func (q *Queries) DeleteAccountInventoryPollRetention(ctx context.Context, deleteLimit int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteAccountInventoryPollRetention, deleteLimit)
	var retention_result []byte
	err := row.Scan(&retention_result)
	return retention_result, err
}

const deleteAccountInventoryRollupRowRetention = `-- name: DeleteAccountInventoryRollupRowRetention :one
SELECT public.control_delete_account_inventory_rollup_row_retention_v1(
    $1::integer
)::jsonb AS retention_result
`

func (q *Queries) DeleteAccountInventoryRollupRowRetention(ctx context.Context, deleteLimit int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteAccountInventoryRollupRowRetention, deleteLimit)
	var retention_result []byte
	err := row.Scan(&retention_result)
	return retention_result, err
}

const deleteAccountInventoryRollupRunRetention = `-- name: DeleteAccountInventoryRollupRunRetention :one
SELECT public.control_delete_account_inventory_rollup_run_retention_v1(
    $1::integer
)::jsonb AS retention_result
`

func (q *Queries) DeleteAccountInventoryRollupRunRetention(ctx context.Context, deleteLimit int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteAccountInventoryRollupRunRetention, deleteLimit)
	var retention_result []byte
	err := row.Scan(&retention_result)
	return retention_result, err
}

const failAccountInventoryHistoryCompaction = `-- name: FailAccountInventoryHistoryCompaction :one
SELECT public.control_fail_account_inventory_compaction_v1(
    $1::uuid,
    $2::uuid,
    $3::text
)::jsonb AS fail_result
`

type FailAccountInventoryHistoryCompactionParams struct {
	CompactionRunID pgtype.UUID `json:"compaction_run_id"`
	FencingToken    pgtype.UUID `json:"fencing_token"`
	FixedReason     string      `json:"fixed_reason"`
}

func (q *Queries) FailAccountInventoryHistoryCompaction(ctx context.Context, arg FailAccountInventoryHistoryCompactionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, failAccountInventoryHistoryCompaction, arg.CompactionRunID, arg.FencingToken, arg.FixedReason)
	var fail_result []byte
	err := row.Scan(&fail_result)
	return fail_result, err
}

const failAccountInventoryHistoryDailyRollup = `-- name: FailAccountInventoryHistoryDailyRollup :one
SELECT public.control_fail_account_inventory_daily_rollup_v1(
    $1::uuid,
    $2::uuid,
    $3::text
)::jsonb AS fail_result
`

type FailAccountInventoryHistoryDailyRollupParams struct {
	RollupRunID  pgtype.UUID `json:"rollup_run_id"`
	FencingToken pgtype.UUID `json:"fencing_token"`
	FixedReason  string      `json:"fixed_reason"`
}

func (q *Queries) FailAccountInventoryHistoryDailyRollup(ctx context.Context, arg FailAccountInventoryHistoryDailyRollupParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, failAccountInventoryHistoryDailyRollup, arg.RollupRunID, arg.FencingToken, arg.FixedReason)
	var fail_result []byte
	err := row.Scan(&fail_result)
	return fail_result, err
}

const finalizeAccountInventoryHistoryDailyRollup = `-- name: FinalizeAccountInventoryHistoryDailyRollup :one
SELECT public.control_finalize_account_inventory_daily_rollup_v1(
    $1::uuid,
    $2::uuid
)::jsonb AS finalize_result
`

type FinalizeAccountInventoryHistoryDailyRollupParams struct {
	RollupRunID  pgtype.UUID `json:"rollup_run_id"`
	FencingToken pgtype.UUID `json:"fencing_token"`
}

func (q *Queries) FinalizeAccountInventoryHistoryDailyRollup(ctx context.Context, arg FinalizeAccountInventoryHistoryDailyRollupParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, finalizeAccountInventoryHistoryDailyRollup, arg.RollupRunID, arg.FencingToken)
	var finalize_result []byte
	err := row.Scan(&finalize_result)
	return finalize_result, err
}

const getAccountInventoryHistoryMetricsSnapshot = `-- name: GetAccountInventoryHistoryMetricsSnapshot :one
SELECT public.control_account_inventory_history_metrics_snapshot_v1()::jsonb AS metrics_snapshot
`

func (q *Queries) GetAccountInventoryHistoryMetricsSnapshot(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAccountInventoryHistoryMetricsSnapshot)
	var metrics_snapshot []byte
	err := row.Scan(&metrics_snapshot)
	return metrics_snapshot, err
}

const listAccountInventoryHistoryCoverageMetrics = `-- name: ListAccountInventoryHistoryCoverageMetrics :many
SELECT
    metric.instance_id::uuid AS instance_id,
    metric.provider::text AS provider,
    metric.coverage_ratio::double precision AS coverage_ratio,
    metric.coverage_complete::boolean AS coverage_complete
FROM public.control_list_account_inventory_history_metrics_v1() AS metric
ORDER BY metric.instance_id, metric.provider
`

type ListAccountInventoryHistoryCoverageMetricsRow struct {
	InstanceID       pgtype.UUID `json:"instance_id"`
	Provider         string      `json:"provider"`
	CoverageRatio    float64     `json:"coverage_ratio"`
	CoverageComplete bool        `json:"coverage_complete"`
}

func (q *Queries) ListAccountInventoryHistoryCoverageMetrics(ctx context.Context) ([]ListAccountInventoryHistoryCoverageMetricsRow, error) {
	rows, err := q.db.Query(ctx, listAccountInventoryHistoryCoverageMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountInventoryHistoryCoverageMetricsRow{}
	for rows.Next() {
		var i ListAccountInventoryHistoryCoverageMetricsRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.Provider,
			&i.CoverageRatio,
			&i.CoverageComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planAccountInventoryHistory = `-- name: PlanAccountInventoryHistory :one
SELECT public.control_plan_account_inventory_history_v1(
    $1::integer
)::jsonb AS plan_result
`

func (q *Queries) PlanAccountInventoryHistory(ctx context.Context, scheduleLimit int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, planAccountInventoryHistory, scheduleLimit)
	var plan_result []byte
	err := row.Scan(&plan_result)
	return plan_result, err
}

const reconcileAccountInventoryHistoryCompactions = `-- name: ReconcileAccountInventoryHistoryCompactions :one
SELECT public.control_reconcile_account_inventory_compactions_v1(
    $1::integer
)::jsonb AS reconcile_result
`

func (q *Queries) ReconcileAccountInventoryHistoryCompactions(ctx context.Context, reconcileLimit int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, reconcileAccountInventoryHistoryCompactions, reconcileLimit)
	var reconcile_result []byte
	err := row.Scan(&reconcile_result)
	return reconcile_result, err
}

const reconcileAccountInventoryHistoryDailyRollups = `-- name: ReconcileAccountInventoryHistoryDailyRollups :one
SELECT public.control_reconcile_account_inventory_daily_rollups_v1(
    $1::integer
)::jsonb AS reconcile_result
`

func (q *Queries) ReconcileAccountInventoryHistoryDailyRollups(ctx context.Context, reconcileLimit int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, reconcileAccountInventoryHistoryDailyRollups, reconcileLimit)
	var reconcile_result []byte
	err := row.Scan(&reconcile_result)
	return reconcile_result, err
}

const renewAccountInventoryHistoryCompaction = `-- name: RenewAccountInventoryHistoryCompaction :one
SELECT renewed.compaction_run_id
FROM public.control_renew_account_inventory_compaction_v1(
    $1::uuid,
    $2::uuid,
    $3::integer
) AS renewed
`

type RenewAccountInventoryHistoryCompactionParams struct {
	CompactionRunID pgtype.UUID `json:"compaction_run_id"`
	FencingToken    pgtype.UUID `json:"fencing_token"`
	LeaseSeconds    int32       `json:"lease_seconds"`
}

func (q *Queries) RenewAccountInventoryHistoryCompaction(ctx context.Context, arg RenewAccountInventoryHistoryCompactionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, renewAccountInventoryHistoryCompaction, arg.CompactionRunID, arg.FencingToken, arg.LeaseSeconds)
	var compaction_run_id pgtype.UUID
	err := row.Scan(&compaction_run_id)
	return compaction_run_id, err
}

const renewAccountInventoryHistoryDailyRollup = `-- name: RenewAccountInventoryHistoryDailyRollup :one
SELECT renewed.rollup_run_id
FROM public.control_renew_account_inventory_daily_rollup_v1(
    $1::uuid,
    $2::uuid,
    $3::integer
) AS renewed
`

type RenewAccountInventoryHistoryDailyRollupParams struct {
	RollupRunID  pgtype.UUID `json:"rollup_run_id"`
	FencingToken pgtype.UUID `json:"fencing_token"`
	LeaseSeconds int32       `json:"lease_seconds"`
}

func (q *Queries) RenewAccountInventoryHistoryDailyRollup(ctx context.Context, arg RenewAccountInventoryHistoryDailyRollupParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, renewAccountInventoryHistoryDailyRollup, arg.RollupRunID, arg.FencingToken, arg.LeaseSeconds)
	var rollup_run_id pgtype.UUID
	err := row.Scan(&rollup_run_id)
	return rollup_run_id, err
}

const summarizeAccountInventoryHistoryCompaction = `-- name: SummarizeAccountInventoryHistoryCompaction :one
SELECT public.control_summarize_account_inventory_compaction_v1(
    $1::uuid,
    $2::uuid
)::jsonb AS summarize_result
`

type SummarizeAccountInventoryHistoryCompactionParams struct {
	CompactionRunID pgtype.UUID `json:"compaction_run_id"`
	FencingToken    pgtype.UUID `json:"fencing_token"`
}

func (q *Queries) SummarizeAccountInventoryHistoryCompaction(ctx context.Context, arg SummarizeAccountInventoryHistoryCompactionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, summarizeAccountInventoryHistoryCompaction, arg.CompactionRunID, arg.FencingToken)
	var summarize_result []byte
	err := row.Scan(&summarize_result)
	return summarize_result, err
}
