// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_inventory_readonly_query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAccountInventoryReadonlyQueryCompatibility = `-- name: CheckAccountInventoryReadonlyQueryCompatibility :one
SELECT
    to_regprocedure(
        'public.control_query_current_account_inventory_v1(uuid,text,text,text,text,text,integer)'
    ) IS NOT NULL
    AND to_regclass('public.account_inventory_normalized_email_read_idx') IS NOT NULL
    AND to_regclass('public.account_inventory_basic_status_read_idx') IS NOT NULL
    AND has_function_privilege(
        current_user,
        'public.control_query_current_account_inventory_v1(uuid,text,text,text,text,text,integer)',
        'EXECUTE'
    )
    AND NOT has_table_privilege(current_user, 'public.account_inventory', 'SELECT')
    AND NOT has_table_privilege(current_user, 'public.account_inventory_provider_states', 'SELECT')
`

func (q *Queries) CheckAccountInventoryReadonlyQueryCompatibility(ctx context.Context) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, checkAccountInventoryReadonlyQueryCompatibility)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const queryCurrentAccountInventoryV1 = `-- name: QueryCurrentAccountInventoryV1 :many
SELECT to_jsonb(inventory) AS inventory
FROM public.control_query_current_account_inventory_v1(
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::integer
) AS inventory
`

type QueryCurrentAccountInventoryV1Params struct {
	InstanceID      pgtype.UUID `json:"instance_id"`
	Provider        string      `json:"provider"`
	Lifecycle       string      `json:"lifecycle"`
	BasicStatus     string      `json:"basic_status"`
	NormalizedEmail string      `json:"normalized_email"`
	AfterAccountKey string      `json:"after_account_key"`
	PageLimit       int32       `json:"page_limit"`
}

func (q *Queries) QueryCurrentAccountInventoryV1(ctx context.Context, arg QueryCurrentAccountInventoryV1Params) ([][]byte, error) {
	rows, err := q.db.Query(ctx, queryCurrentAccountInventoryV1,
		arg.InstanceID,
		arg.Provider,
		arg.Lifecycle,
		arg.BasicStatus,
		arg.NormalizedEmail,
		arg.AfterAccountKey,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var inventory []byte
		if err := rows.Scan(&inventory); err != nil {
			return nil, err
		}
		items = append(items, inventory)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
