// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_inventory_poll_capacity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountInventoryPollCapacityV1 = `-- name: GetAccountInventoryPollCapacityV1 :one
SELECT capacity.evaluated_at::timestamptz AS evaluated_at,
       capacity.evaluated_slot::timestamptz AS evaluated_slot,
       capacity.eligible_node_count::bigint AS eligible_node_count
FROM public.control_query_account_inventory_poll_capacity_v1()
    AS capacity(evaluated_at, evaluated_slot, eligible_node_count)
`

type GetAccountInventoryPollCapacityV1Row struct {
	EvaluatedAt       pgtype.Timestamptz `json:"evaluated_at"`
	EvaluatedSlot     pgtype.Timestamptz `json:"evaluated_slot"`
	EligibleNodeCount int64              `json:"eligible_node_count"`
}

func (q *Queries) GetAccountInventoryPollCapacityV1(ctx context.Context) (GetAccountInventoryPollCapacityV1Row, error) {
	row := q.db.QueryRow(ctx, getAccountInventoryPollCapacityV1)
	var i GetAccountInventoryPollCapacityV1Row
	err := row.Scan(&i.EvaluatedAt, &i.EvaluatedSlot, &i.EligibleNodeCount)
	return i, err
}
