// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_inventory_provider_state_query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountInventoryProviderStatesV1 = `-- name: GetAccountInventoryProviderStatesV1 :one
SELECT statement_timestamp()::timestamptz AS observed_at,
       COALESCE(
           jsonb_agg(to_jsonb(provider_state) ORDER BY provider_state.provider),
           '[]'::jsonb
       )::jsonb AS providers
FROM public.control_query_account_inventory_provider_states_v1(
    $1::uuid
) AS provider_state
`

type GetAccountInventoryProviderStatesV1Row struct {
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	Providers  []byte             `json:"providers"`
}

func (q *Queries) GetAccountInventoryProviderStatesV1(ctx context.Context, instanceID pgtype.UUID) (GetAccountInventoryProviderStatesV1Row, error) {
	row := q.db.QueryRow(ctx, getAccountInventoryProviderStatesV1, instanceID)
	var i GetAccountInventoryProviderStatesV1Row
	err := row.Scan(&i.ObservedAt, &i.Providers)
	return i, err
}
