// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_command_registry.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminCommandReservation = `-- name: GetAdminCommandReservation :one
SELECT command_id, actor_admin_id, command_domain, command_kind,
       intent_encoding_version, canonical_intent_hash,
       secret_fingerprint_key_version, reserved_at
FROM admin_command_registry
WHERE command_id = $1::uuid
`

func (q *Queries) GetAdminCommandReservation(ctx context.Context, commandID pgtype.UUID) (AdminCommandRegistry, error) {
	row := q.db.QueryRow(ctx, getAdminCommandReservation, commandID)
	var i AdminCommandRegistry
	err := row.Scan(
		&i.CommandID,
		&i.ActorAdminID,
		&i.CommandDomain,
		&i.CommandKind,
		&i.IntentEncodingVersion,
		&i.CanonicalIntentHash,
		&i.SecretFingerprintKeyVersion,
		&i.ReservedAt,
	)
	return i, err
}

const insertControlledAssetAdminCommandReceipt = `-- name: InsertControlledAssetAdminCommandReceipt :exec
SELECT control_insert_asset_admin_command_receipt_v1(
    $1::uuid,
    $2::text,
    $3::smallint,
    $4::bytea,
    $5::jsonb,
    $6::smallint,
    $7::uuid,
    $8::timestamptz,
    $9::smallint
)
`

type InsertControlledAssetAdminCommandReceiptParams struct {
	CommandID                   pgtype.UUID        `json:"command_id"`
	CommandKind                 string             `json:"command_kind"`
	IntentEncodingVersion       int16              `json:"intent_encoding_version"`
	CanonicalIntentHash         []byte             `json:"canonical_intent_hash"`
	SanitizedResult             []byte             `json:"sanitized_result"`
	ResponseStatus              int16              `json:"response_status"`
	ActorAdminID                pgtype.UUID        `json:"actor_admin_id"`
	CommittedAt                 pgtype.Timestamptz `json:"committed_at"`
	SecretFingerprintKeyVersion pgtype.Int2        `json:"secret_fingerprint_key_version"`
}

func (q *Queries) InsertControlledAssetAdminCommandReceipt(ctx context.Context, arg InsertControlledAssetAdminCommandReceiptParams) error {
	_, err := q.db.Exec(ctx, insertControlledAssetAdminCommandReceipt,
		arg.CommandID,
		arg.CommandKind,
		arg.IntentEncodingVersion,
		arg.CanonicalIntentHash,
		arg.SanitizedResult,
		arg.ResponseStatus,
		arg.ActorAdminID,
		arg.CommittedAt,
		arg.SecretFingerprintKeyVersion,
	)
	return err
}

const reserveAdminCommand = `-- name: ReserveAdminCommand :one
SELECT command_id, actor_admin_id, command_domain, command_kind,
       intent_encoding_version, canonical_intent_hash,
       secret_fingerprint_key_version, reserved_at
FROM control_reserve_admin_command_v1(
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::smallint,
    $6::bytea,
    $7::smallint
)
`

type ReserveAdminCommandParams struct {
	CommandID                   pgtype.UUID `json:"command_id"`
	ActorAdminID                pgtype.UUID `json:"actor_admin_id"`
	CommandDomain               string      `json:"command_domain"`
	CommandKind                 string      `json:"command_kind"`
	IntentEncodingVersion       int16       `json:"intent_encoding_version"`
	CanonicalIntentHash         []byte      `json:"canonical_intent_hash"`
	SecretFingerprintKeyVersion pgtype.Int2 `json:"secret_fingerprint_key_version"`
}

func (q *Queries) ReserveAdminCommand(ctx context.Context, arg ReserveAdminCommandParams) (AdminCommandRegistry, error) {
	row := q.db.QueryRow(ctx, reserveAdminCommand,
		arg.CommandID,
		arg.ActorAdminID,
		arg.CommandDomain,
		arg.CommandKind,
		arg.IntentEncodingVersion,
		arg.CanonicalIntentHash,
		arg.SecretFingerprintKeyVersion,
	)
	var i AdminCommandRegistry
	err := row.Scan(
		&i.CommandID,
		&i.ActorAdminID,
		&i.CommandDomain,
		&i.CommandKind,
		&i.IntentEncodingVersion,
		&i.CanonicalIntentHash,
		&i.SecretFingerprintKeyVersion,
		&i.ReservedAt,
	)
	return i, err
}
