// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssetCounts = `-- name: GetAssetCounts :one
SELECT
    (SELECT count(instance_id) FROM gateway_instances)::bigint AS gateways,
    (SELECT count(instance_id) FROM relay_node_assets)::bigint AS nodes,
    (SELECT count(node_type) FROM node_drivers)::bigint AS drivers,
    (SELECT count(policy_version_id) FROM provider_inventory_policy_versions)::bigint AS provider_policies
`

type GetAssetCountsRow struct {
	Gateways         int64 `json:"gateways"`
	Nodes            int64 `json:"nodes"`
	Drivers          int64 `json:"drivers"`
	ProviderPolicies int64 `json:"provider_policies"`
}

func (q *Queries) GetAssetCounts(ctx context.Context) (GetAssetCountsRow, error) {
	row := q.db.QueryRow(ctx, getAssetCounts)
	var i GetAssetCountsRow
	err := row.Scan(
		&i.Gateways,
		&i.Nodes,
		&i.Drivers,
		&i.ProviderPolicies,
	)
	return i, err
}

const getCurrentProviderInventoryPolicy = `-- name: GetCurrentProviderInventoryPolicy :one
WITH current_policy AS (
    SELECT
        policy.policy_version_id,
        policy.node_type,
        policy.driver_contract_version,
        policy.active_providers,
        policy.out_of_scope_providers,
        activation.effective_from,
        activation.effective_to,
        policy.created_at
    FROM provider_inventory_policy_activations AS activation
    JOIN provider_inventory_policy_versions AS policy
      ON policy.policy_version_id = activation.policy_version_id
     AND policy.node_type = activation.node_type
     AND policy.driver_contract_version = activation.driver_contract_version
    WHERE activation.node_type = $1
      AND activation.driver_contract_version = $2
      AND CURRENT_TIMESTAMP <@ activation.active_range
), matched AS (
    SELECT count(*)::bigint AS current_match_count
    FROM current_policy
)
SELECT
    matched.current_match_count,
    policy.policy_version_id,
    policy.node_type,
    policy.driver_contract_version,
    policy.active_providers,
    policy.out_of_scope_providers,
    policy.effective_from,
    policy.effective_to,
    policy.created_at
FROM matched
LEFT JOIN current_policy AS policy
  ON matched.current_match_count = 1
`

type GetCurrentProviderInventoryPolicyParams struct {
	NodeType              string `json:"node_type"`
	DriverContractVersion string `json:"driver_contract_version"`
}

type GetCurrentProviderInventoryPolicyRow struct {
	CurrentMatchCount     int64              `json:"current_match_count"`
	PolicyVersionID       pgtype.UUID        `json:"policy_version_id"`
	NodeType              pgtype.Text        `json:"node_type"`
	DriverContractVersion pgtype.Text        `json:"driver_contract_version"`
	ActiveProviders       []string           `json:"active_providers"`
	OutOfScopeProviders   []string           `json:"out_of_scope_providers"`
	EffectiveFrom         pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo           pgtype.Timestamptz `json:"effective_to"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCurrentProviderInventoryPolicy(ctx context.Context, arg GetCurrentProviderInventoryPolicyParams) (GetCurrentProviderInventoryPolicyRow, error) {
	row := q.db.QueryRow(ctx, getCurrentProviderInventoryPolicy, arg.NodeType, arg.DriverContractVersion)
	var i GetCurrentProviderInventoryPolicyRow
	err := row.Scan(
		&i.CurrentMatchCount,
		&i.PolicyVersionID,
		&i.NodeType,
		&i.DriverContractVersion,
		&i.ActiveProviders,
		&i.OutOfScopeProviders,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getGatewayAsset = `-- name: GetGatewayAsset :one
SELECT
    instance_id,
    display_name,
    management_endpoint,
    COALESCE(reader_secret_configured, false)::boolean AS secret_configured,
    created_at,
    updated_at
FROM gateway_instances
WHERE singleton_id = 1
`

type GetGatewayAssetRow struct {
	InstanceID         pgtype.UUID        `json:"instance_id"`
	DisplayName        string             `json:"display_name"`
	ManagementEndpoint string             `json:"management_endpoint"`
	SecretConfigured   bool               `json:"secret_configured"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetGatewayAsset(ctx context.Context) (GetGatewayAssetRow, error) {
	row := q.db.QueryRow(ctx, getGatewayAsset)
	var i GetGatewayAssetRow
	err := row.Scan(
		&i.InstanceID,
		&i.DisplayName,
		&i.ManagementEndpoint,
		&i.SecretConfigured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeAsset = `-- name: GetNodeAsset :one
SELECT
    node.instance_id,
    node.display_name,
    node.node_type,
    node.driver_contract_version,
    node.management_endpoint,
    COALESCE(node.reader_secret_configured, false)::boolean AS secret_configured,
    COALESCE(
        (
            SELECT array_agg(capability.capability ORDER BY capability.capability)::text[]
            FROM node_capabilities AS capability
            WHERE capability.instance_id = node.instance_id
        ),
        ARRAY[]::text[]
    )::text[] AS capabilities,
    (monitoring.active_match_count = 1)::boolean AS monitoring_active,
    monitoring.active_match_count AS monitoring_match_count,
    monitoring.effective_from AS monitoring_effective_from,
    monitoring.effective_to AS monitoring_effective_to,
    node.created_at,
    node.updated_at
FROM relay_node_assets AS node
LEFT JOIN LATERAL (
    SELECT
        count(*)::bigint AS active_match_count,
        (CASE WHEN count(*) = 1 THEN min(activation.effective_from) END)::timestamptz AS effective_from,
        (CASE WHEN count(*) = 1 THEN min(activation.effective_to) END)::timestamptz AS effective_to
    FROM relay_node_inventory_monitoring_activations AS activation
    WHERE activation.instance_id = node.instance_id
      AND CURRENT_TIMESTAMP <@ activation.active_range
) AS monitoring ON true
WHERE node.instance_id = $1
`

type GetNodeAssetRow struct {
	InstanceID              pgtype.UUID        `json:"instance_id"`
	DisplayName             string             `json:"display_name"`
	NodeType                string             `json:"node_type"`
	DriverContractVersion   string             `json:"driver_contract_version"`
	ManagementEndpoint      string             `json:"management_endpoint"`
	SecretConfigured        bool               `json:"secret_configured"`
	Capabilities            []string           `json:"capabilities"`
	MonitoringActive        bool               `json:"monitoring_active"`
	MonitoringMatchCount    int64              `json:"monitoring_match_count"`
	MonitoringEffectiveFrom pgtype.Timestamptz `json:"monitoring_effective_from"`
	MonitoringEffectiveTo   pgtype.Timestamptz `json:"monitoring_effective_to"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNodeAsset(ctx context.Context, instanceID pgtype.UUID) (GetNodeAssetRow, error) {
	row := q.db.QueryRow(ctx, getNodeAsset, instanceID)
	var i GetNodeAssetRow
	err := row.Scan(
		&i.InstanceID,
		&i.DisplayName,
		&i.NodeType,
		&i.DriverContractVersion,
		&i.ManagementEndpoint,
		&i.SecretConfigured,
		&i.Capabilities,
		&i.MonitoringActive,
		&i.MonitoringMatchCount,
		&i.MonitoringEffectiveFrom,
		&i.MonitoringEffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodeAssets = `-- name: ListNodeAssets :many
SELECT
    node.instance_id,
    node.display_name,
    node.node_type,
    node.driver_contract_version,
    node.management_endpoint,
    COALESCE(node.reader_secret_configured, false)::boolean AS secret_configured,
    COALESCE(
        (
            SELECT array_agg(capability.capability ORDER BY capability.capability)::text[]
            FROM node_capabilities AS capability
            WHERE capability.instance_id = node.instance_id
        ),
        ARRAY[]::text[]
    )::text[] AS capabilities,
    (monitoring.active_match_count = 1)::boolean AS monitoring_active,
    monitoring.active_match_count AS monitoring_match_count,
    monitoring.effective_from AS monitoring_effective_from,
    monitoring.effective_to AS monitoring_effective_to,
    node.created_at,
    node.updated_at
FROM relay_node_assets AS node
LEFT JOIN LATERAL (
    SELECT
        count(*)::bigint AS active_match_count,
        (CASE WHEN count(*) = 1 THEN min(activation.effective_from) END)::timestamptz AS effective_from,
        (CASE WHEN count(*) = 1 THEN min(activation.effective_to) END)::timestamptz AS effective_to
    FROM relay_node_inventory_monitoring_activations AS activation
    WHERE activation.instance_id = node.instance_id
      AND CURRENT_TIMESTAMP <@ activation.active_range
) AS monitoring ON true
WHERE ($1::text IS NULL OR node.node_type = $1)
  AND (
      $2::text IS NULL
      OR EXISTS (
          SELECT 1
          FROM node_capabilities AS filtered_capability
          WHERE filtered_capability.instance_id = node.instance_id
            AND filtered_capability.capability = $2
      )
  )
  AND (
      $3::boolean IS NULL
      OR monitoring.active_match_count > 1
      OR $3 = (monitoring.active_match_count = 1)
  )
  AND ($4::uuid IS NULL OR node.instance_id > $4)
ORDER BY node.instance_id
LIMIT $5
`

type ListNodeAssetsParams struct {
	NodeType         pgtype.Text `json:"node_type"`
	Capability       pgtype.Text `json:"capability"`
	MonitoringActive pgtype.Bool `json:"monitoring_active"`
	AfterInstanceID  pgtype.UUID `json:"after_instance_id"`
	PageSize         int32       `json:"page_size"`
}

type ListNodeAssetsRow struct {
	InstanceID              pgtype.UUID        `json:"instance_id"`
	DisplayName             string             `json:"display_name"`
	NodeType                string             `json:"node_type"`
	DriverContractVersion   string             `json:"driver_contract_version"`
	ManagementEndpoint      string             `json:"management_endpoint"`
	SecretConfigured        bool               `json:"secret_configured"`
	Capabilities            []string           `json:"capabilities"`
	MonitoringActive        bool               `json:"monitoring_active"`
	MonitoringMatchCount    int64              `json:"monitoring_match_count"`
	MonitoringEffectiveFrom pgtype.Timestamptz `json:"monitoring_effective_from"`
	MonitoringEffectiveTo   pgtype.Timestamptz `json:"monitoring_effective_to"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNodeAssets(ctx context.Context, arg ListNodeAssetsParams) ([]ListNodeAssetsRow, error) {
	rows, err := q.db.Query(ctx, listNodeAssets,
		arg.NodeType,
		arg.Capability,
		arg.MonitoringActive,
		arg.AfterInstanceID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeAssetsRow{}
	for rows.Next() {
		var i ListNodeAssetsRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.DisplayName,
			&i.NodeType,
			&i.DriverContractVersion,
			&i.ManagementEndpoint,
			&i.SecretConfigured,
			&i.Capabilities,
			&i.MonitoringActive,
			&i.MonitoringMatchCount,
			&i.MonitoringEffectiveFrom,
			&i.MonitoringEffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeDrivers = `-- name: ListNodeDrivers :many
SELECT
    driver.node_type,
    driver.driver_contract_version,
    driver.display_name,
    driver.lifecycle_status,
    COALESCE(
        array_agg(capability.capability ORDER BY capability.capability)
            FILTER (WHERE capability.capability IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS capabilities,
    driver.created_at
FROM node_drivers AS driver
LEFT JOIN driver_capabilities AS capability
    ON capability.node_type = driver.node_type
   AND capability.driver_contract_version = driver.driver_contract_version
GROUP BY
    driver.node_type,
    driver.driver_contract_version,
    driver.display_name,
    driver.lifecycle_status,
    driver.created_at
ORDER BY driver.node_type, driver.driver_contract_version
`

type ListNodeDriversRow struct {
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	DisplayName           string             `json:"display_name"`
	LifecycleStatus       string             `json:"lifecycle_status"`
	Capabilities          []string           `json:"capabilities"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNodeDrivers(ctx context.Context) ([]ListNodeDriversRow, error) {
	rows, err := q.db.Query(ctx, listNodeDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeDriversRow{}
	for rows.Next() {
		var i ListNodeDriversRow
		if err := rows.Scan(
			&i.NodeType,
			&i.DriverContractVersion,
			&i.DisplayName,
			&i.LifecycleStatus,
			&i.Capabilities,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
