// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authentication.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateAdminUser = `-- name: ActivateAdminUser :one
UPDATE control_admin_users
SET status = 'enabled', activated_at = CURRENT_TIMESTAMP, disabled_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE admin_id = $1 AND status = 'pending'
RETURNING admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at
`

func (q *Queries) ActivateAdminUser(ctx context.Context, adminID pgtype.UUID) (ControlAdminUser, error) {
	row := q.db.QueryRow(ctx, activateAdminUser, adminID)
	var i ControlAdminUser
	err := row.Scan(
		&i.AdminID,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const completeBootstrap = `-- name: CompleteBootstrap :one
UPDATE control_bootstrap_state
SET state = 'completed',
    pending_admin_id = NULL,
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE singleton_id = 1 AND state = 'in_progress' AND pending_admin_id = $1
RETURNING singleton_id, state, pending_admin_id, started_at, completed_at, updated_at
`

func (q *Queries) CompleteBootstrap(ctx context.Context, pendingAdminID pgtype.UUID) (ControlBootstrapState, error) {
	row := q.db.QueryRow(ctx, completeBootstrap, pendingAdminID)
	var i ControlBootstrapState
	err := row.Scan(
		&i.SingletonID,
		&i.State,
		&i.PendingAdminID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmAdminTOTP = `-- name: ConfirmAdminTOTP :one
UPDATE control_admin_totp
SET confirmed_at = CURRENT_TIMESTAMP, last_used_step = $2
WHERE admin_id = $1 AND confirmed_at IS NULL
RETURNING admin_id, encrypted_secret, nonce, key_version, created_at, confirmed_at, last_used_step
`

type ConfirmAdminTOTPParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	LastUsedStep pgtype.Int8 `json:"last_used_step"`
}

func (q *Queries) ConfirmAdminTOTP(ctx context.Context, arg ConfirmAdminTOTPParams) (ControlAdminTotp, error) {
	row := q.db.QueryRow(ctx, confirmAdminTOTP, arg.AdminID, arg.LastUsedStep)
	var i ControlAdminTotp
	err := row.Scan(
		&i.AdminID,
		&i.EncryptedSecret,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.LastUsedStep,
	)
	return i, err
}

const consumeActivationToken = `-- name: ConsumeActivationToken :one
UPDATE control_admin_activation_tokens
SET consumed_at = CURRENT_TIMESTAMP
WHERE key_version = $1 AND token_digest = $2
  AND consumed_at IS NULL AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
RETURNING activation_token_id, admin_id, created_by_admin_id, token_digest, key_version, created_at, expires_at, consumed_at, revoked_at
`

type ConsumeActivationTokenParams struct {
	KeyVersion  int32  `json:"key_version"`
	TokenDigest []byte `json:"token_digest"`
}

func (q *Queries) ConsumeActivationToken(ctx context.Context, arg ConsumeActivationTokenParams) (ControlAdminActivationToken, error) {
	row := q.db.QueryRow(ctx, consumeActivationToken, arg.KeyVersion, arg.TokenDigest)
	var i ControlAdminActivationToken
	err := row.Scan(
		&i.ActivationTokenID,
		&i.AdminID,
		&i.CreatedByAdminID,
		&i.TokenDigest,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const consumeAuthChallenge = `-- name: ConsumeAuthChallenge :one
UPDATE control_auth_challenges
SET consumed_at = CURRENT_TIMESTAMP
WHERE challenge_id = $1 AND consumed_at IS NULL AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
RETURNING challenge_id, admin_id, token_digest, key_version, source_fingerprint, created_at, expires_at, consumed_at, revoked_at
`

func (q *Queries) ConsumeAuthChallenge(ctx context.Context, challengeID pgtype.UUID) (ControlAuthChallenge, error) {
	row := q.db.QueryRow(ctx, consumeAuthChallenge, challengeID)
	var i ControlAuthChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.AdminID,
		&i.TokenDigest,
		&i.KeyVersion,
		&i.SourceFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE control_admin_recovery_codes
SET consumed_at = CURRENT_TIMESTAMP
WHERE admin_id = $1 AND key_version = $2 AND code_digest = $3
  AND consumed_at IS NULL AND revoked_at IS NULL
RETURNING recovery_code_id, admin_id, batch_id, code_digest, key_version, created_at, consumed_at, revoked_at
`

type ConsumeRecoveryCodeParams struct {
	AdminID    pgtype.UUID `json:"admin_id"`
	KeyVersion int32       `json:"key_version"`
	CodeDigest []byte      `json:"code_digest"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (ControlAdminRecoveryCode, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode, arg.AdminID, arg.KeyVersion, arg.CodeDigest)
	var i ControlAdminRecoveryCode
	err := row.Scan(
		&i.RecoveryCodeID,
		&i.AdminID,
		&i.BatchID,
		&i.CodeDigest,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const consumeTOTPTimeStep = `-- name: ConsumeTOTPTimeStep :one
UPDATE control_admin_totp
SET last_used_step = $2
WHERE admin_id = $1
  AND confirmed_at IS NOT NULL
  AND (last_used_step IS NULL OR last_used_step < $2)
RETURNING admin_id, encrypted_secret, nonce, key_version, created_at, confirmed_at, last_used_step
`

type ConsumeTOTPTimeStepParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	LastUsedStep pgtype.Int8 `json:"last_used_step"`
}

func (q *Queries) ConsumeTOTPTimeStep(ctx context.Context, arg ConsumeTOTPTimeStepParams) (ControlAdminTotp, error) {
	row := q.db.QueryRow(ctx, consumeTOTPTimeStep, arg.AdminID, arg.LastUsedStep)
	var i ControlAdminTotp
	err := row.Scan(
		&i.AdminID,
		&i.EncryptedSecret,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.LastUsedStep,
	)
	return i, err
}

const countActiveAdminSessions = `-- name: CountActiveAdminSessions :one
SELECT count(*) FROM control_admin_sessions AS s
JOIN control_admin_users AS u ON u.admin_id = s.admin_id
WHERE s.revoked_at IS NULL
  AND s.absolute_expires_at > CURRENT_TIMESTAMP
  AND s.last_activity_at > CURRENT_TIMESTAMP - interval '30 minutes'
  AND u.status = 'enabled'
`

func (q *Queries) CountActiveAdminSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAvailableRecoveryCodes = `-- name: CountAvailableRecoveryCodes :one
SELECT count(*) FROM control_admin_recovery_codes
WHERE admin_id = $1 AND consumed_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) CountAvailableRecoveryCodes(ctx context.Context, adminID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableRecoveryCodes, adminID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledAdminUsers = `-- name: CountEnabledAdminUsers :one
SELECT count(*) FROM control_admin_users WHERE status = 'enabled'
`

func (q *Queries) CountEnabledAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivationToken = `-- name: CreateActivationToken :one
INSERT INTO control_admin_activation_tokens
    (activation_token_id, admin_id, created_by_admin_id, token_digest, key_version, expires_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP + interval '24 hours')
RETURNING activation_token_id, admin_id, created_by_admin_id, token_digest, key_version, created_at, expires_at, consumed_at, revoked_at
`

type CreateActivationTokenParams struct {
	ActivationTokenID pgtype.UUID `json:"activation_token_id"`
	AdminID           pgtype.UUID `json:"admin_id"`
	CreatedByAdminID  pgtype.UUID `json:"created_by_admin_id"`
	TokenDigest       []byte      `json:"token_digest"`
	KeyVersion        int32       `json:"key_version"`
}

func (q *Queries) CreateActivationToken(ctx context.Context, arg CreateActivationTokenParams) (ControlAdminActivationToken, error) {
	row := q.db.QueryRow(ctx, createActivationToken,
		arg.ActivationTokenID,
		arg.AdminID,
		arg.CreatedByAdminID,
		arg.TokenDigest,
		arg.KeyVersion,
	)
	var i ControlAdminActivationToken
	err := row.Scan(
		&i.ActivationTokenID,
		&i.AdminID,
		&i.CreatedByAdminID,
		&i.TokenDigest,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO control_admin_sessions
    (session_id, admin_id, token_digest, csrf_digest, key_version, mfa_method,
     mfa_completed_at, absolute_expires_at, reauthenticated_at)
VALUES (
    $1, $2, $3, $4, $5, $6,
    CASE WHEN $6 = 'none' THEN NULL ELSE CURRENT_TIMESTAMP END,
    CURRENT_TIMESTAMP + interval '12 hours',
    CASE WHEN $7::boolean THEN CURRENT_TIMESTAMP ELSE NULL END
)
RETURNING session_id, admin_id, token_digest, csrf_digest, key_version, mfa_method, mfa_completed_at, created_at, last_activity_at, absolute_expires_at, reauthenticated_at, revoked_at, revoke_reason
`

type CreateAdminSessionParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	AdminID         pgtype.UUID `json:"admin_id"`
	TokenDigest     []byte      `json:"token_digest"`
	CsrfDigest      []byte      `json:"csrf_digest"`
	KeyVersion      int32       `json:"key_version"`
	MfaMethod       string      `json:"mfa_method"`
	Reauthenticated bool        `json:"reauthenticated"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (ControlAdminSession, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.SessionID,
		arg.AdminID,
		arg.TokenDigest,
		arg.CsrfDigest,
		arg.KeyVersion,
		arg.MfaMethod,
		arg.Reauthenticated,
	)
	var i ControlAdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.KeyVersion,
		&i.MfaMethod,
		&i.MfaCompletedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthenticatedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO control_admin_users (admin_id, login_name, display_name)
VALUES ($1, $2, $3)
RETURNING admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at
`

type CreateAdminUserParams struct {
	AdminID     pgtype.UUID `json:"admin_id"`
	LoginName   string      `json:"login_name"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (ControlAdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.AdminID, arg.LoginName, arg.DisplayName)
	var i ControlAdminUser
	err := row.Scan(
		&i.AdminID,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createAuthChallenge = `-- name: CreateAuthChallenge :one
INSERT INTO control_auth_challenges
    (challenge_id, admin_id, token_digest, key_version, source_fingerprint, expires_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP + interval '5 minutes')
RETURNING challenge_id, admin_id, token_digest, key_version, source_fingerprint, created_at, expires_at, consumed_at, revoked_at
`

type CreateAuthChallengeParams struct {
	ChallengeID       pgtype.UUID `json:"challenge_id"`
	AdminID           pgtype.UUID `json:"admin_id"`
	TokenDigest       []byte      `json:"token_digest"`
	KeyVersion        int32       `json:"key_version"`
	SourceFingerprint []byte      `json:"source_fingerprint"`
}

func (q *Queries) CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) (ControlAuthChallenge, error) {
	row := q.db.QueryRow(ctx, createAuthChallenge,
		arg.ChallengeID,
		arg.AdminID,
		arg.TokenDigest,
		arg.KeyVersion,
		arg.SourceFingerprint,
	)
	var i ControlAuthChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.AdminID,
		&i.TokenDigest,
		&i.KeyVersion,
		&i.SourceFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO control_admin_recovery_codes
    (recovery_code_id, admin_id, batch_id, code_digest, key_version)
VALUES ($1, $2, $3, $4, $5)
RETURNING recovery_code_id, admin_id, batch_id, code_digest, key_version, created_at, consumed_at, revoked_at
`

type CreateRecoveryCodeParams struct {
	RecoveryCodeID pgtype.UUID `json:"recovery_code_id"`
	AdminID        pgtype.UUID `json:"admin_id"`
	BatchID        pgtype.UUID `json:"batch_id"`
	CodeDigest     []byte      `json:"code_digest"`
	KeyVersion     int32       `json:"key_version"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (ControlAdminRecoveryCode, error) {
	row := q.db.QueryRow(ctx, createRecoveryCode,
		arg.RecoveryCodeID,
		arg.AdminID,
		arg.BatchID,
		arg.CodeDigest,
		arg.KeyVersion,
	)
	var i ControlAdminRecoveryCode
	err := row.Scan(
		&i.RecoveryCodeID,
		&i.AdminID,
		&i.BatchID,
		&i.CodeDigest,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteAccountFailureWindow = `-- name: DeleteAccountFailureWindow :execrows
DELETE FROM control_auth_failure_windows
WHERE dimension = 'account' AND key_version = $1 AND subject_fingerprint = $2
`

type DeleteAccountFailureWindowParams struct {
	KeyVersion         int32  `json:"key_version"`
	SubjectFingerprint []byte `json:"subject_fingerprint"`
}

func (q *Queries) DeleteAccountFailureWindow(ctx context.Context, arg DeleteAccountFailureWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountFailureWindow, arg.KeyVersion, arg.SubjectFingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAdminTOTP = `-- name: DeleteAdminTOTP :execrows
DELETE FROM control_admin_totp WHERE admin_id = $1
`

func (q *Queries) DeleteAdminTOTP(ctx context.Context, adminID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminTOTP, adminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthChallenges = `-- name: DeleteExpiredAuthChallenges :execrows
DELETE FROM control_auth_challenges
WHERE expires_at <= CURRENT_TIMESTAMP OR consumed_at IS NOT NULL OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredAuthChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthFailureEvents = `-- name: DeleteExpiredAuthFailureEvents :execrows
DELETE FROM control_auth_failure_events
WHERE occurred_at <= CURRENT_TIMESTAMP - interval '15 minutes'
`

func (q *Queries) DeleteExpiredAuthFailureEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthFailureEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthFailureWindows = `-- name: DeleteExpiredAuthFailureWindows :execrows
DELETE FROM control_auth_failure_windows AS windows
WHERE (windows.blocked_until IS NULL OR windows.blocked_until <= CURRENT_TIMESTAMP)
  AND windows.updated_at <= CURRENT_TIMESTAMP - interval '30 minutes'
  AND NOT EXISTS (
      SELECT 1
      FROM control_auth_failure_events AS events
      WHERE events.dimension = windows.dimension
        AND events.key_version = windows.key_version
        AND events.subject_fingerprint = windows.subject_fingerprint
        AND events.occurred_at > CURRENT_TIMESTAMP - interval '15 minutes'
  )
`

func (q *Queries) DeleteExpiredAuthFailureWindows(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthFailureWindows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingAdminUser = `-- name: DeletePendingAdminUser :execrows
DELETE FROM control_admin_users WHERE admin_id = $1 AND status = 'pending'
`

func (q *Queries) DeletePendingAdminUser(ctx context.Context, adminID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingAdminUser, adminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableAdminUser = `-- name: DisableAdminUser :one
UPDATE control_admin_users
SET status = 'disabled', disabled_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE admin_id = $1 AND status = 'enabled'
RETURNING admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at
`

func (q *Queries) DisableAdminUser(ctx context.Context, adminID pgtype.UUID) (ControlAdminUser, error) {
	row := q.db.QueryRow(ctx, disableAdminUser, adminID)
	var i ControlAdminUser
	err := row.Scan(
		&i.AdminID,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const expireAdminSessions = `-- name: ExpireAdminSessions :execrows
UPDATE control_admin_sessions
SET revoked_at = CURRENT_TIMESTAMP,
    revoke_reason = CASE
        WHEN absolute_expires_at <= CURRENT_TIMESTAMP THEN 'absolute_expired'
        ELSE 'idle_expired'
    END
WHERE revoked_at IS NULL
  AND (absolute_expires_at <= CURRENT_TIMESTAMP
       OR last_activity_at <= CURRENT_TIMESTAMP - interval '30 minutes')
`

func (q *Queries) ExpireAdminSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireAdminSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAdminSessionByDigest = `-- name: GetActiveAdminSessionByDigest :one
SELECT s.session_id, s.admin_id, s.token_digest, s.csrf_digest, s.key_version, s.mfa_method, s.mfa_completed_at, s.created_at, s.last_activity_at, s.absolute_expires_at, s.reauthenticated_at, s.revoked_at, s.revoke_reason, u.login_name, u.display_name, u.auth_source, u.role, u.status AS admin_status
FROM control_admin_sessions AS s
JOIN control_admin_users AS u ON u.admin_id = s.admin_id
WHERE s.key_version = $1 AND s.token_digest = $2
  AND s.revoked_at IS NULL
  AND s.absolute_expires_at > CURRENT_TIMESTAMP
  AND s.last_activity_at > CURRENT_TIMESTAMP - interval '30 minutes'
  AND u.status = 'enabled'
`

type GetActiveAdminSessionByDigestParams struct {
	KeyVersion  int32  `json:"key_version"`
	TokenDigest []byte `json:"token_digest"`
}

type GetActiveAdminSessionByDigestRow struct {
	SessionID         pgtype.UUID        `json:"session_id"`
	AdminID           pgtype.UUID        `json:"admin_id"`
	TokenDigest       []byte             `json:"token_digest"`
	CsrfDigest        []byte             `json:"csrf_digest"`
	KeyVersion        int32              `json:"key_version"`
	MfaMethod         string             `json:"mfa_method"`
	MfaCompletedAt    pgtype.Timestamptz `json:"mfa_completed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastActivityAt    pgtype.Timestamptz `json:"last_activity_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	ReauthenticatedAt pgtype.Timestamptz `json:"reauthenticated_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason      pgtype.Text        `json:"revoke_reason"`
	LoginName         string             `json:"login_name"`
	DisplayName       string             `json:"display_name"`
	AuthSource        string             `json:"auth_source"`
	Role              string             `json:"role"`
	AdminStatus       string             `json:"admin_status"`
}

func (q *Queries) GetActiveAdminSessionByDigest(ctx context.Context, arg GetActiveAdminSessionByDigestParams) (GetActiveAdminSessionByDigestRow, error) {
	row := q.db.QueryRow(ctx, getActiveAdminSessionByDigest, arg.KeyVersion, arg.TokenDigest)
	var i GetActiveAdminSessionByDigestRow
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.KeyVersion,
		&i.MfaMethod,
		&i.MfaCompletedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthenticatedAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.AdminStatus,
	)
	return i, err
}

const getActiveAuthChallengeByDigest = `-- name: GetActiveAuthChallengeByDigest :one
SELECT challenge_id, admin_id, token_digest, key_version, source_fingerprint, created_at, expires_at, consumed_at, revoked_at FROM control_auth_challenges
WHERE key_version = $1 AND token_digest = $2
  AND consumed_at IS NULL AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
`

type GetActiveAuthChallengeByDigestParams struct {
	KeyVersion  int32  `json:"key_version"`
	TokenDigest []byte `json:"token_digest"`
}

func (q *Queries) GetActiveAuthChallengeByDigest(ctx context.Context, arg GetActiveAuthChallengeByDigestParams) (ControlAuthChallenge, error) {
	row := q.db.QueryRow(ctx, getActiveAuthChallengeByDigest, arg.KeyVersion, arg.TokenDigest)
	var i ControlAuthChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.AdminID,
		&i.TokenDigest,
		&i.KeyVersion,
		&i.SourceFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminPassword = `-- name: GetAdminPassword :one
SELECT admin_id, password_phc, parameter_version, changed_at FROM control_admin_passwords WHERE admin_id = $1
`

func (q *Queries) GetAdminPassword(ctx context.Context, adminID pgtype.UUID) (ControlAdminPassword, error) {
	row := q.db.QueryRow(ctx, getAdminPassword, adminID)
	var i ControlAdminPassword
	err := row.Scan(
		&i.AdminID,
		&i.PasswordPhc,
		&i.ParameterVersion,
		&i.ChangedAt,
	)
	return i, err
}

const getAdminTOTP = `-- name: GetAdminTOTP :one
SELECT admin_id, encrypted_secret, nonce, key_version, created_at, confirmed_at, last_used_step FROM control_admin_totp WHERE admin_id = $1
`

func (q *Queries) GetAdminTOTP(ctx context.Context, adminID pgtype.UUID) (ControlAdminTotp, error) {
	row := q.db.QueryRow(ctx, getAdminTOTP, adminID)
	var i ControlAdminTotp
	err := row.Scan(
		&i.AdminID,
		&i.EncryptedSecret,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.LastUsedStep,
	)
	return i, err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at FROM control_admin_users WHERE admin_id = $1
`

func (q *Queries) GetAdminUserByID(ctx context.Context, adminID pgtype.UUID) (ControlAdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, adminID)
	var i ControlAdminUser
	err := row.Scan(
		&i.AdminID,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminUserByLoginName = `-- name: GetAdminUserByLoginName :one
SELECT admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at FROM control_admin_users WHERE login_name = $1
`

func (q *Queries) GetAdminUserByLoginName(ctx context.Context, loginName string) (ControlAdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByLoginName, loginName)
	var i ControlAdminUser
	err := row.Scan(
		&i.AdminID,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT audit_id, occurred_at, category, action, result, actor_admin_id, target_admin_id, actor_fingerprint, source_fingerprint, reason, request_id, details FROM audit_logs WHERE audit_id = $1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, auditID pgtype.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, auditID)
	var i AuditLog
	err := row.Scan(
		&i.AuditID,
		&i.OccurredAt,
		&i.Category,
		&i.Action,
		&i.Result,
		&i.ActorAdminID,
		&i.TargetAdminID,
		&i.ActorFingerprint,
		&i.SourceFingerprint,
		&i.Reason,
		&i.RequestID,
		&i.Details,
	)
	return i, err
}

const getAuthFailureWindowForUpdate = `-- name: GetAuthFailureWindowForUpdate :one
SELECT dimension, key_version, subject_fingerprint, blocked_until, updated_at FROM control_auth_failure_windows
WHERE dimension = $1 AND key_version = $2 AND subject_fingerprint = $3
FOR UPDATE
`

type GetAuthFailureWindowForUpdateParams struct {
	Dimension          string `json:"dimension"`
	KeyVersion         int32  `json:"key_version"`
	SubjectFingerprint []byte `json:"subject_fingerprint"`
}

func (q *Queries) GetAuthFailureWindowForUpdate(ctx context.Context, arg GetAuthFailureWindowForUpdateParams) (ControlAuthFailureWindow, error) {
	row := q.db.QueryRow(ctx, getAuthFailureWindowForUpdate, arg.Dimension, arg.KeyVersion, arg.SubjectFingerprint)
	var i ControlAuthFailureWindow
	err := row.Scan(
		&i.Dimension,
		&i.KeyVersion,
		&i.SubjectFingerprint,
		&i.BlockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const getBootstrapState = `-- name: GetBootstrapState :one
SELECT singleton_id, state, pending_admin_id, started_at, completed_at, updated_at
FROM control_bootstrap_state
WHERE singleton_id = 1
`

func (q *Queries) GetBootstrapState(ctx context.Context) (ControlBootstrapState, error) {
	row := q.db.QueryRow(ctx, getBootstrapState)
	var i ControlBootstrapState
	err := row.Scan(
		&i.SingletonID,
		&i.State,
		&i.PendingAdminID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT CURRENT_TIMESTAMP::timestamptz AS database_time
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var database_time pgtype.Timestamptz
	err := row.Scan(&database_time)
	return database_time, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs
    (audit_id, category, action, result, actor_admin_id, target_admin_id,
     actor_fingerprint, source_fingerprint, reason, request_id, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING audit_id, occurred_at, category, action, result, actor_admin_id, target_admin_id, actor_fingerprint, source_fingerprint, reason, request_id, details
`

type InsertAuditLogParams struct {
	AuditID           pgtype.UUID `json:"audit_id"`
	Category          string      `json:"category"`
	Action            string      `json:"action"`
	Result            string      `json:"result"`
	ActorAdminID      pgtype.UUID `json:"actor_admin_id"`
	TargetAdminID     pgtype.UUID `json:"target_admin_id"`
	ActorFingerprint  []byte      `json:"actor_fingerprint"`
	SourceFingerprint []byte      `json:"source_fingerprint"`
	Reason            pgtype.Text `json:"reason"`
	RequestID         string      `json:"request_id"`
	Details           []byte      `json:"details"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.AuditID,
		arg.Category,
		arg.Action,
		arg.Result,
		arg.ActorAdminID,
		arg.TargetAdminID,
		arg.ActorFingerprint,
		arg.SourceFingerprint,
		arg.Reason,
		arg.RequestID,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.AuditID,
		&i.OccurredAt,
		&i.Category,
		&i.Action,
		&i.Result,
		&i.ActorAdminID,
		&i.TargetAdminID,
		&i.ActorFingerprint,
		&i.SourceFingerprint,
		&i.Reason,
		&i.RequestID,
		&i.Details,
	)
	return i, err
}

const isAuthFailureSubjectBlocked = `-- name: IsAuthFailureSubjectBlocked :one
SELECT EXISTS (
    SELECT 1
    FROM control_auth_failure_windows
    WHERE dimension = $1
      AND key_version = $2
      AND subject_fingerprint = $3
      AND blocked_until > CURRENT_TIMESTAMP
) AS blocked
`

type IsAuthFailureSubjectBlockedParams struct {
	Dimension          string `json:"dimension"`
	KeyVersion         int32  `json:"key_version"`
	SubjectFingerprint []byte `json:"subject_fingerprint"`
}

func (q *Queries) IsAuthFailureSubjectBlocked(ctx context.Context, arg IsAuthFailureSubjectBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAuthFailureSubjectBlocked, arg.Dimension, arg.KeyVersion, arg.SubjectFingerprint)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at FROM control_admin_users
ORDER BY login_name, admin_id
`

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ControlAdminUser, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlAdminUser{}
	for rows.Next() {
		var i ControlAdminUser
		if err := rows.Scan(
			&i.AdminID,
			&i.LoginName,
			&i.DisplayName,
			&i.AuthSource,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivatedAt,
			&i.DisabledAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveActivationTokenByDigest = `-- name: LockActiveActivationTokenByDigest :one
SELECT t.activation_token_id, t.admin_id, t.created_by_admin_id, t.token_digest, t.key_version, t.created_at, t.expires_at, t.consumed_at, t.revoked_at
FROM control_admin_activation_tokens AS t
JOIN control_admin_users AS u ON u.admin_id = t.admin_id
WHERE t.key_version = $1 AND t.token_digest = $2
  AND t.consumed_at IS NULL AND t.revoked_at IS NULL
  AND t.expires_at > CURRENT_TIMESTAMP
  AND u.status = 'pending'
FOR UPDATE OF t
`

type LockActiveActivationTokenByDigestParams struct {
	KeyVersion  int32  `json:"key_version"`
	TokenDigest []byte `json:"token_digest"`
}

func (q *Queries) LockActiveActivationTokenByDigest(ctx context.Context, arg LockActiveActivationTokenByDigestParams) (ControlAdminActivationToken, error) {
	row := q.db.QueryRow(ctx, lockActiveActivationTokenByDigest, arg.KeyVersion, arg.TokenDigest)
	var i ControlAdminActivationToken
	err := row.Scan(
		&i.ActivationTokenID,
		&i.AdminID,
		&i.CreatedByAdminID,
		&i.TokenDigest,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockActiveAdminSession = `-- name: LockActiveAdminSession :one
SELECT s.session_id, s.admin_id, s.token_digest, s.csrf_digest, s.key_version, s.mfa_method, s.mfa_completed_at, s.created_at, s.last_activity_at, s.absolute_expires_at, s.reauthenticated_at, s.revoked_at, s.revoke_reason
FROM control_admin_sessions AS s
JOIN control_admin_users AS u ON u.admin_id = s.admin_id
WHERE s.session_id = $1
  AND s.admin_id = $2
  AND s.revoked_at IS NULL
  AND s.absolute_expires_at > CURRENT_TIMESTAMP
  AND s.last_activity_at > CURRENT_TIMESTAMP - interval '30 minutes'
  AND u.status = 'enabled'
  AND u.auth_source = 'local'
  AND u.role = 'super_admin'
FOR UPDATE OF s, u
`

type LockActiveAdminSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	AdminID   pgtype.UUID `json:"admin_id"`
}

func (q *Queries) LockActiveAdminSession(ctx context.Context, arg LockActiveAdminSessionParams) (ControlAdminSession, error) {
	row := q.db.QueryRow(ctx, lockActiveAdminSession, arg.SessionID, arg.AdminID)
	var i ControlAdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.KeyVersion,
		&i.MfaMethod,
		&i.MfaCompletedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthenticatedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const lockAdminTOTP = `-- name: LockAdminTOTP :one
SELECT admin_id, encrypted_secret, nonce, key_version, created_at, confirmed_at, last_used_step FROM control_admin_totp WHERE admin_id = $1 FOR UPDATE
`

func (q *Queries) LockAdminTOTP(ctx context.Context, adminID pgtype.UUID) (ControlAdminTotp, error) {
	row := q.db.QueryRow(ctx, lockAdminTOTP, adminID)
	var i ControlAdminTotp
	err := row.Scan(
		&i.AdminID,
		&i.EncryptedSecret,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.LastUsedStep,
	)
	return i, err
}

const lockAdminUser = `-- name: LockAdminUser :one
SELECT admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at FROM control_admin_users WHERE admin_id = $1 FOR UPDATE
`

func (q *Queries) LockAdminUser(ctx context.Context, adminID pgtype.UUID) (ControlAdminUser, error) {
	row := q.db.QueryRow(ctx, lockAdminUser, adminID)
	var i ControlAdminUser
	err := row.Scan(
		&i.AdminID,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const lockBootstrapState = `-- name: LockBootstrapState :one
SELECT singleton_id, state, pending_admin_id, started_at, completed_at, updated_at
FROM control_bootstrap_state
WHERE singleton_id = 1
FOR UPDATE
`

func (q *Queries) LockBootstrapState(ctx context.Context) (ControlBootstrapState, error) {
	row := q.db.QueryRow(ctx, lockBootstrapState)
	var i ControlBootstrapState
	err := row.Scan(
		&i.SingletonID,
		&i.State,
		&i.PendingAdminID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockFreshReauthenticatedSession = `-- name: LockFreshReauthenticatedSession :one
SELECT s.session_id, s.admin_id, s.token_digest, s.csrf_digest, s.key_version, s.mfa_method, s.mfa_completed_at, s.created_at, s.last_activity_at, s.absolute_expires_at, s.reauthenticated_at, s.revoked_at, s.revoke_reason
FROM control_admin_sessions AS s
JOIN control_admin_users AS u ON u.admin_id = s.admin_id
WHERE s.session_id = $1
  AND s.admin_id = $2
  AND s.revoked_at IS NULL
  AND s.absolute_expires_at > CURRENT_TIMESTAMP
  AND s.last_activity_at > CURRENT_TIMESTAMP - interval '30 minutes'
  AND s.reauthenticated_at > CURRENT_TIMESTAMP - interval '5 minutes'
  AND u.status = 'enabled'
  AND u.auth_source = 'local'
  AND u.role = 'super_admin'
FOR UPDATE OF s, u
`

type LockFreshReauthenticatedSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	AdminID   pgtype.UUID `json:"admin_id"`
}

func (q *Queries) LockFreshReauthenticatedSession(ctx context.Context, arg LockFreshReauthenticatedSessionParams) (ControlAdminSession, error) {
	row := q.db.QueryRow(ctx, lockFreshReauthenticatedSession, arg.SessionID, arg.AdminID)
	var i ControlAdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.KeyVersion,
		&i.MfaMethod,
		&i.MfaCompletedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthenticatedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const markAdminSessionReauthenticated = `-- name: MarkAdminSessionReauthenticated :one
UPDATE control_admin_sessions
SET reauthenticated_at = CURRENT_TIMESTAMP
WHERE session_id = $1 AND revoked_at IS NULL
  AND absolute_expires_at > CURRENT_TIMESTAMP
  AND last_activity_at > CURRENT_TIMESTAMP - interval '30 minutes'
RETURNING session_id, admin_id, token_digest, csrf_digest, key_version, mfa_method, mfa_completed_at, created_at, last_activity_at, absolute_expires_at, reauthenticated_at, revoked_at, revoke_reason
`

func (q *Queries) MarkAdminSessionReauthenticated(ctx context.Context, sessionID pgtype.UUID) (ControlAdminSession, error) {
	row := q.db.QueryRow(ctx, markAdminSessionReauthenticated, sessionID)
	var i ControlAdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.KeyVersion,
		&i.MfaMethod,
		&i.MfaCompletedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthenticatedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const recordAuthFailure = `-- name: RecordAuthFailure :one
SELECT
    (recorded.result).failure_count::integer AS failure_count,
    (recorded.result).blocked_until::timestamptz AS blocked_until
FROM (
    SELECT control_record_auth_failure(
        $1,
        $2,
        $3,
        $4::integer
    ) AS result
) AS recorded
`

type RecordAuthFailureParams struct {
	Dimension          string `json:"dimension"`
	KeyVersion         int32  `json:"key_version"`
	SubjectFingerprint []byte `json:"subject_fingerprint"`
	FailureThreshold   int32  `json:"failure_threshold"`
}

type RecordAuthFailureRow struct {
	FailureCount int32              `json:"failure_count"`
	BlockedUntil pgtype.Timestamptz `json:"blocked_until"`
}

func (q *Queries) RecordAuthFailure(ctx context.Context, arg RecordAuthFailureParams) (RecordAuthFailureRow, error) {
	row := q.db.QueryRow(ctx, recordAuthFailure,
		arg.Dimension,
		arg.KeyVersion,
		arg.SubjectFingerprint,
		arg.FailureThreshold,
	)
	var i RecordAuthFailureRow
	err := row.Scan(&i.FailureCount, &i.BlockedUntil)
	return i, err
}

const resetAdminUserToPending = `-- name: ResetAdminUserToPending :one
UPDATE control_admin_users
SET status = 'pending', disabled_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE admin_id = $1 AND status IN ('enabled', 'disabled')
RETURNING admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at
`

func (q *Queries) ResetAdminUserToPending(ctx context.Context, adminID pgtype.UUID) (ControlAdminUser, error) {
	row := q.db.QueryRow(ctx, resetAdminUserToPending, adminID)
	var i ControlAdminUser
	err := row.Scan(
		&i.AdminID,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const resetPendingBootstrap = `-- name: ResetPendingBootstrap :one
UPDATE control_bootstrap_state
SET state = 'required',
    pending_admin_id = NULL,
    started_at = NULL,
    completed_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE singleton_id = 1 AND state = 'in_progress' AND pending_admin_id = $1
RETURNING singleton_id, state, pending_admin_id, started_at, completed_at, updated_at
`

func (q *Queries) ResetPendingBootstrap(ctx context.Context, pendingAdminID pgtype.UUID) (ControlBootstrapState, error) {
	row := q.db.QueryRow(ctx, resetPendingBootstrap, pendingAdminID)
	var i ControlBootstrapState
	err := row.Scan(
		&i.SingletonID,
		&i.State,
		&i.PendingAdminID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeActivationTokensForAdmin = `-- name: RevokeActivationTokensForAdmin :execrows
UPDATE control_admin_activation_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE admin_id = $1 AND consumed_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) RevokeActivationTokensForAdmin(ctx context.Context, adminID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActivationTokensForAdmin, adminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAdminSession = `-- name: RevokeAdminSession :one
UPDATE control_admin_sessions
SET revoked_at = CURRENT_TIMESTAMP, revoke_reason = $2
WHERE session_id = $1 AND revoked_at IS NULL
RETURNING session_id, admin_id, token_digest, csrf_digest, key_version, mfa_method, mfa_completed_at, created_at, last_activity_at, absolute_expires_at, reauthenticated_at, revoked_at, revoke_reason
`

type RevokeAdminSessionParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

func (q *Queries) RevokeAdminSession(ctx context.Context, arg RevokeAdminSessionParams) (ControlAdminSession, error) {
	row := q.db.QueryRow(ctx, revokeAdminSession, arg.SessionID, arg.RevokeReason)
	var i ControlAdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.KeyVersion,
		&i.MfaMethod,
		&i.MfaCompletedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthenticatedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const revokeAllAdminSessions = `-- name: RevokeAllAdminSessions :execrows
UPDATE control_admin_sessions
SET revoked_at = CURRENT_TIMESTAMP, revoke_reason = $2
WHERE admin_id = $1 AND revoked_at IS NULL
`

type RevokeAllAdminSessionsParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

func (q *Queries) RevokeAllAdminSessions(ctx context.Context, arg RevokeAllAdminSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllAdminSessions, arg.AdminID, arg.RevokeReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthChallengesForAdmin = `-- name: RevokeAuthChallengesForAdmin :execrows
UPDATE control_auth_challenges
SET revoked_at = CURRENT_TIMESTAMP
WHERE admin_id = $1 AND consumed_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthChallengesForAdmin(ctx context.Context, adminID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthChallengesForAdmin, adminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAvailableRecoveryCodes = `-- name: RevokeAvailableRecoveryCodes :execrows
UPDATE control_admin_recovery_codes
SET revoked_at = CURRENT_TIMESTAMP
WHERE admin_id = $1 AND consumed_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) RevokeAvailableRecoveryCodes(ctx context.Context, adminID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAvailableRecoveryCodes, adminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherAdminSessions = `-- name: RevokeOtherAdminSessions :execrows
UPDATE control_admin_sessions
SET revoked_at = CURRENT_TIMESTAMP, revoke_reason = $3
WHERE admin_id = $1 AND session_id <> $2 AND revoked_at IS NULL
`

type RevokeOtherAdminSessionsParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	SessionID    pgtype.UUID `json:"session_id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

func (q *Queries) RevokeOtherAdminSessions(ctx context.Context, arg RevokeOtherAdminSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOtherAdminSessions, arg.AdminID, arg.SessionID, arg.RevokeReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAdminSessionCSRF = `-- name: RotateAdminSessionCSRF :one
UPDATE control_admin_sessions
SET csrf_digest = $2
WHERE session_id = $1 AND revoked_at IS NULL
  AND absolute_expires_at > CURRENT_TIMESTAMP
  AND last_activity_at > CURRENT_TIMESTAMP - interval '30 minutes'
  AND EXISTS (
      SELECT 1 FROM control_admin_users AS u
      WHERE u.admin_id = control_admin_sessions.admin_id AND u.status = 'enabled'
  )
RETURNING session_id, admin_id, token_digest, csrf_digest, key_version, mfa_method, mfa_completed_at, created_at, last_activity_at, absolute_expires_at, reauthenticated_at, revoked_at, revoke_reason
`

type RotateAdminSessionCSRFParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	CsrfDigest []byte      `json:"csrf_digest"`
}

func (q *Queries) RotateAdminSessionCSRF(ctx context.Context, arg RotateAdminSessionCSRFParams) (ControlAdminSession, error) {
	row := q.db.QueryRow(ctx, rotateAdminSessionCSRF, arg.SessionID, arg.CsrfDigest)
	var i ControlAdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.KeyVersion,
		&i.MfaMethod,
		&i.MfaCompletedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthenticatedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const startBootstrap = `-- name: StartBootstrap :one
UPDATE control_bootstrap_state
SET state = 'in_progress',
    pending_admin_id = $1,
    started_at = CURRENT_TIMESTAMP,
    completed_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE singleton_id = 1 AND state = 'required'
RETURNING singleton_id, state, pending_admin_id, started_at, completed_at, updated_at
`

func (q *Queries) StartBootstrap(ctx context.Context, pendingAdminID pgtype.UUID) (ControlBootstrapState, error) {
	row := q.db.QueryRow(ctx, startBootstrap, pendingAdminID)
	var i ControlBootstrapState
	err := row.Scan(
		&i.SingletonID,
		&i.State,
		&i.PendingAdminID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAdminSession = `-- name: TouchAdminSession :one
UPDATE control_admin_sessions
SET last_activity_at = CURRENT_TIMESTAMP
WHERE session_id = $1 AND revoked_at IS NULL
  AND absolute_expires_at > CURRENT_TIMESTAMP
  AND last_activity_at > CURRENT_TIMESTAMP - interval '30 minutes'
  AND last_activity_at <= CURRENT_TIMESTAMP - interval '1 minute'
RETURNING session_id, admin_id, token_digest, csrf_digest, key_version, mfa_method, mfa_completed_at, created_at, last_activity_at, absolute_expires_at, reauthenticated_at, revoked_at, revoke_reason
`

func (q *Queries) TouchAdminSession(ctx context.Context, sessionID pgtype.UUID) (ControlAdminSession, error) {
	row := q.db.QueryRow(ctx, touchAdminSession, sessionID)
	var i ControlAdminSession
	err := row.Scan(
		&i.SessionID,
		&i.AdminID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.KeyVersion,
		&i.MfaMethod,
		&i.MfaCompletedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthenticatedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :one
UPDATE control_admin_users
SET last_login_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE admin_id = $1 AND status = 'enabled'
RETURNING admin_id, login_name, display_name, auth_source, role, status, created_at, updated_at, activated_at, disabled_at, last_login_at
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, adminID pgtype.UUID) (ControlAdminUser, error) {
	row := q.db.QueryRow(ctx, updateAdminLastLogin, adminID)
	var i ControlAdminUser
	err := row.Scan(
		&i.AdminID,
		&i.LoginName,
		&i.DisplayName,
		&i.AuthSource,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertAdminPassword = `-- name: UpsertAdminPassword :one
INSERT INTO control_admin_passwords (admin_id, password_phc, parameter_version)
VALUES ($1, $2, $3)
ON CONFLICT (admin_id) DO UPDATE
SET password_phc = EXCLUDED.password_phc,
    parameter_version = EXCLUDED.parameter_version,
    changed_at = CURRENT_TIMESTAMP
RETURNING admin_id, password_phc, parameter_version, changed_at
`

type UpsertAdminPasswordParams struct {
	AdminID          pgtype.UUID `json:"admin_id"`
	PasswordPhc      string      `json:"password_phc"`
	ParameterVersion int32       `json:"parameter_version"`
}

func (q *Queries) UpsertAdminPassword(ctx context.Context, arg UpsertAdminPasswordParams) (ControlAdminPassword, error) {
	row := q.db.QueryRow(ctx, upsertAdminPassword, arg.AdminID, arg.PasswordPhc, arg.ParameterVersion)
	var i ControlAdminPassword
	err := row.Scan(
		&i.AdminID,
		&i.PasswordPhc,
		&i.ParameterVersion,
		&i.ChangedAt,
	)
	return i, err
}

const upsertAdminTOTP = `-- name: UpsertAdminTOTP :one
INSERT INTO control_admin_totp (admin_id, encrypted_secret, nonce, key_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (admin_id) DO UPDATE
SET encrypted_secret = EXCLUDED.encrypted_secret,
    nonce = EXCLUDED.nonce,
    key_version = EXCLUDED.key_version,
    created_at = CURRENT_TIMESTAMP,
    confirmed_at = NULL,
    last_used_step = NULL
RETURNING admin_id, encrypted_secret, nonce, key_version, created_at, confirmed_at, last_used_step
`

type UpsertAdminTOTPParams struct {
	AdminID         pgtype.UUID `json:"admin_id"`
	EncryptedSecret []byte      `json:"encrypted_secret"`
	Nonce           []byte      `json:"nonce"`
	KeyVersion      int32       `json:"key_version"`
}

func (q *Queries) UpsertAdminTOTP(ctx context.Context, arg UpsertAdminTOTPParams) (ControlAdminTotp, error) {
	row := q.db.QueryRow(ctx, upsertAdminTOTP,
		arg.AdminID,
		arg.EncryptedSecret,
		arg.Nonce,
		arg.KeyVersion,
	)
	var i ControlAdminTotp
	err := row.Scan(
		&i.AdminID,
		&i.EncryptedSecret,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.LastUsedStep,
	)
	return i, err
}
