// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cross_node_duplicate_ownership_lifecycle.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCrossNodeDuplicateOccurrenceNode = `-- name: DeleteCrossNodeDuplicateOccurrenceNode :exec
DELETE FROM cross_node_duplicate_occurrence_nodes
WHERE occurrence_id = $1 AND instance_id = $2
`

type DeleteCrossNodeDuplicateOccurrenceNodeParams struct {
	OccurrenceID pgtype.UUID `json:"occurrence_id"`
	InstanceID   pgtype.UUID `json:"instance_id"`
}

func (q *Queries) DeleteCrossNodeDuplicateOccurrenceNode(ctx context.Context, arg DeleteCrossNodeDuplicateOccurrenceNodeParams) error {
	_, err := q.db.Exec(ctx, deleteCrossNodeDuplicateOccurrenceNode, arg.OccurrenceID, arg.InstanceID)
	return err
}

const insertCrossNodeDuplicateOccurrence = `-- name: InsertCrossNodeDuplicateOccurrence :one
INSERT INTO cross_node_duplicate_occurrences (
    environment_id, account_key, conflict_type, status, severity,
    first_seen_at, last_seen_at, evidence_state, last_fully_verified_at,
    latest_evaluation_id
) VALUES (
    $1, $2, 'cross_node_duplicate_ownership',
    'ACTIVE', 'Critical', $3, $3,
    'complete', $3, NULL
)
ON CONFLICT (environment_id, account_key, conflict_type) WHERE status = 'ACTIVE' DO NOTHING
RETURNING occurrence_id
`

type InsertCrossNodeDuplicateOccurrenceParams struct {
	EnvironmentID string             `json:"environment_id"`
	AccountKey    string             `json:"account_key"`
	EvaluationAt  pgtype.Timestamptz `json:"evaluation_at"`
}

// Optimistic detect/reopen INSERT. ON CONFLICT DO NOTHING relies on the
// partial unique index cross_node_duplicate_occurrence_active_uidx
// (environment_id, account_key, conflict_type) WHERE status='ACTIVE'; a
// conflict here never returns the existing row (PostgreSQL semantics), so
// the caller must re-run SelectActiveCrossNodeDuplicateOccurrenceForUpdate
// when zero rows come back.
func (q *Queries) InsertCrossNodeDuplicateOccurrence(ctx context.Context, arg InsertCrossNodeDuplicateOccurrenceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCrossNodeDuplicateOccurrence, arg.EnvironmentID, arg.AccountKey, arg.EvaluationAt)
	var occurrence_id pgtype.UUID
	err := row.Scan(&occurrence_id)
	return occurrence_id, err
}

const insertCrossNodeDuplicateOccurrenceEvidence = `-- name: InsertCrossNodeDuplicateOccurrenceEvidence :exec
INSERT INTO cross_node_duplicate_occurrence_evidence (
    occurrence_id, instance_id, observation_kind, source_poll_run_id,
    source_provider, source_scheduled_at, source_completed_at,
    evaluation_id, evaluation_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9
)
`

type InsertCrossNodeDuplicateOccurrenceEvidenceParams struct {
	OccurrenceID      pgtype.UUID        `json:"occurrence_id"`
	InstanceID        pgtype.UUID        `json:"instance_id"`
	ObservationKind   string             `json:"observation_kind"`
	SourcePollRunID   pgtype.UUID        `json:"source_poll_run_id"`
	SourceProvider    string             `json:"source_provider"`
	SourceScheduledAt pgtype.Timestamptz `json:"source_scheduled_at"`
	SourceCompletedAt pgtype.Timestamptz `json:"source_completed_at"`
	EvaluationID      pgtype.UUID        `json:"evaluation_id"`
	EvaluationAt      pgtype.Timestamptz `json:"evaluation_at"`
}

func (q *Queries) InsertCrossNodeDuplicateOccurrenceEvidence(ctx context.Context, arg InsertCrossNodeDuplicateOccurrenceEvidenceParams) error {
	_, err := q.db.Exec(ctx, insertCrossNodeDuplicateOccurrenceEvidence,
		arg.OccurrenceID,
		arg.InstanceID,
		arg.ObservationKind,
		arg.SourcePollRunID,
		arg.SourceProvider,
		arg.SourceScheduledAt,
		arg.SourceCompletedAt,
		arg.EvaluationID,
		arg.EvaluationAt,
	)
	return err
}

const insertCrossNodeDuplicateOccurrenceNode = `-- name: InsertCrossNodeDuplicateOccurrenceNode :exec
INSERT INTO cross_node_duplicate_occurrence_nodes (
    occurrence_id, instance_id, first_confirmed_at
) VALUES (
    $1, $2, $3
)
ON CONFLICT (occurrence_id, instance_id) DO NOTHING
`

type InsertCrossNodeDuplicateOccurrenceNodeParams struct {
	OccurrenceID     pgtype.UUID        `json:"occurrence_id"`
	InstanceID       pgtype.UUID        `json:"instance_id"`
	FirstConfirmedAt pgtype.Timestamptz `json:"first_confirmed_at"`
}

func (q *Queries) InsertCrossNodeDuplicateOccurrenceNode(ctx context.Context, arg InsertCrossNodeDuplicateOccurrenceNodeParams) error {
	_, err := q.db.Exec(ctx, insertCrossNodeDuplicateOccurrenceNode, arg.OccurrenceID, arg.InstanceID, arg.FirstConfirmedAt)
	return err
}

const listActiveCrossNodeDuplicateOccurrenceKeys = `-- name: ListActiveCrossNodeDuplicateOccurrenceKeys :many
SELECT environment_id, account_key
FROM cross_node_duplicate_occurrences
WHERE status = 'ACTIVE'
`

type ListActiveCrossNodeDuplicateOccurrenceKeysRow struct {
	EnvironmentID string `json:"environment_id"`
	AccountKey    string `json:"account_key"`
}

// Phase 4 (add-cross-node-duplicate-ownership) restart/backfill
// reconciliation (design.md §5.1): every (environment_id, account_key) that
// currently has an ACTIVE occurrence, so a reconciliation pass can also
// resolve/degrade occurrences whose account_key has dropped out of the
// current duplicate candidate set (e.g. down to a single owner, or all the
// way to zero eligible owners) since the last detect/refresh pass.
// relay_control_runtime already has SELECT on this table (migrations/00013);
// no new grant is required.
func (q *Queries) ListActiveCrossNodeDuplicateOccurrenceKeys(ctx context.Context) ([]ListActiveCrossNodeDuplicateOccurrenceKeysRow, error) {
	rows, err := q.db.Query(ctx, listActiveCrossNodeDuplicateOccurrenceKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCrossNodeDuplicateOccurrenceKeysRow{}
	for rows.Next() {
		var i ListActiveCrossNodeDuplicateOccurrenceKeysRow
		if err := rows.Scan(&i.EnvironmentID, &i.AccountKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrossNodeDuplicateOccurrenceNodes = `-- name: ListCrossNodeDuplicateOccurrenceNodes :many
SELECT instance_id, first_confirmed_at
FROM cross_node_duplicate_occurrence_nodes
WHERE occurrence_id = $1
ORDER BY instance_id
`

type ListCrossNodeDuplicateOccurrenceNodesRow struct {
	InstanceID       pgtype.UUID        `json:"instance_id"`
	FirstConfirmedAt pgtype.Timestamptz `json:"first_confirmed_at"`
}

func (q *Queries) ListCrossNodeDuplicateOccurrenceNodes(ctx context.Context, occurrenceID pgtype.UUID) ([]ListCrossNodeDuplicateOccurrenceNodesRow, error) {
	rows, err := q.db.Query(ctx, listCrossNodeDuplicateOccurrenceNodes, occurrenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCrossNodeDuplicateOccurrenceNodesRow{}
	for rows.Next() {
		var i ListCrossNodeDuplicateOccurrenceNodesRow
		if err := rows.Scan(&i.InstanceID, &i.FirstConfirmedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshCrossNodeDuplicateOccurrenceProjection = `-- name: RefreshCrossNodeDuplicateOccurrenceProjection :exec
UPDATE cross_node_duplicate_occurrences
SET last_seen_at = $1,
    evidence_state = $2,
    last_fully_verified_at = CASE
        WHEN NOT $3::boolean THEN last_fully_verified_at
        WHEN $2::text = 'complete' THEN $1
        ELSE last_fully_verified_at
    END,
    latest_evaluation_id = CASE WHEN $3::boolean
        THEN $4 ELSE latest_evaluation_id END
WHERE occurrence_id = $5 AND status = 'ACTIVE'
`

type RefreshCrossNodeDuplicateOccurrenceProjectionParams struct {
	EvaluationAt  pgtype.Timestamptz `json:"evaluation_at"`
	EvidenceState string             `json:"evidence_state"`
	HasEvidence   bool               `json:"has_evidence"`
	EvaluationID  pgtype.UUID        `json:"evaluation_id"`
	OccurrenceID  pgtype.UUID        `json:"occurrence_id"`
}

// Non-resolving pass (detect seed / refresh / add / remove / degrade): the
// occurrence stays ACTIVE, only the mutable projection columns move.
//
// has_evidence is false specifically for the zero-evidence degraded pass
// (Phase 3 review item 3): when a reconcile pass appended no evidence rows
// at all this evaluation (every retained Node was unclassifiable), the
// caller passes has_evidence=false so latest_evaluation_id (and
// last_fully_verified_at) keep pointing at the last evaluation that
// actually has evidence backing it -- the 00013 latest_evaluation_id
// consistency trigger requires an EXISTS evidence row for whatever
// latest_evaluation_id is set to, and would reject an evaluation_id with
// zero evidence rows this pass.
func (q *Queries) RefreshCrossNodeDuplicateOccurrenceProjection(ctx context.Context, arg RefreshCrossNodeDuplicateOccurrenceProjectionParams) error {
	_, err := q.db.Exec(ctx, refreshCrossNodeDuplicateOccurrenceProjection,
		arg.EvaluationAt,
		arg.EvidenceState,
		arg.HasEvidence,
		arg.EvaluationID,
		arg.OccurrenceID,
	)
	return err
}

const resolveCrossNodeDuplicateOccurrence = `-- name: ResolveCrossNodeDuplicateOccurrence :exec
UPDATE cross_node_duplicate_occurrences
SET status = 'RESOLVED',
    resolved_at = $1,
    last_seen_at = $1,
    evidence_state = 'complete',
    last_fully_verified_at = $1,
    latest_evaluation_id = $2
WHERE occurrence_id = $3 AND status = 'ACTIVE'
`

type ResolveCrossNodeDuplicateOccurrenceParams struct {
	EvaluationAt pgtype.Timestamptz `json:"evaluation_at"`
	EvaluationID pgtype.UUID        `json:"evaluation_id"`
	OccurrenceID pgtype.UUID        `json:"occurrence_id"`
}

// ACTIVE -> RESOLVED transition. resolved_at is set in the same UPDATE as
// the status change, satisfying the occurrence mutation-guard trigger
// (migrations/00013).
func (q *Queries) ResolveCrossNodeDuplicateOccurrence(ctx context.Context, arg ResolveCrossNodeDuplicateOccurrenceParams) error {
	_, err := q.db.Exec(ctx, resolveCrossNodeDuplicateOccurrence, arg.EvaluationAt, arg.EvaluationID, arg.OccurrenceID)
	return err
}

const selectActiveCrossNodeDuplicateOccurrenceForUpdate = `-- name: SelectActiveCrossNodeDuplicateOccurrenceForUpdate :one

SELECT occurrence_id, environment_id, account_key, conflict_type, status,
    severity, first_seen_at, last_seen_at, resolved_at, evidence_state,
    last_fully_verified_at, latest_evaluation_id
FROM cross_node_duplicate_occurrences
WHERE environment_id = $1
  AND account_key = $2
  AND conflict_type = 'cross_node_duplicate_ownership'
  AND status = 'ACTIVE'
FOR UPDATE
`

type SelectActiveCrossNodeDuplicateOccurrenceForUpdateParams struct {
	EnvironmentID string `json:"environment_id"`
	AccountKey    string `json:"account_key"`
}

// Phase 3 (add-cross-node-duplicate-ownership) lifecycle transaction DML.
// These queries operate directly on the tables created by migration 00013;
// relay_control_runtime already has the exact grants they need
// (SELECT/INSERT on cross_node_duplicate_occurrences plus UPDATE on the
// mutable projection columns, SELECT/INSERT/DELETE on
// cross_node_duplicate_occurrence_nodes, SELECT/INSERT on
// cross_node_duplicate_occurrence_evidence -- see migrations/00013 grants
// section). No new migration/grant is required for this file.
// Row-locks the existing ACTIVE occurrence (if any) for this semantic key
// before re-evaluating source truth, per design.md §1B.8.
func (q *Queries) SelectActiveCrossNodeDuplicateOccurrenceForUpdate(ctx context.Context, arg SelectActiveCrossNodeDuplicateOccurrenceForUpdateParams) (CrossNodeDuplicateOccurrence, error) {
	row := q.db.QueryRow(ctx, selectActiveCrossNodeDuplicateOccurrenceForUpdate, arg.EnvironmentID, arg.AccountKey)
	var i CrossNodeDuplicateOccurrence
	err := row.Scan(
		&i.OccurrenceID,
		&i.EnvironmentID,
		&i.AccountKey,
		&i.ConflictType,
		&i.Status,
		&i.Severity,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.EvidenceState,
		&i.LastFullyVerifiedAt,
		&i.LatestEvaluationID,
	)
	return i, err
}
