// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cross_node_duplicate_ownership_query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCrossNodeDuplicateCandidates = `-- name: ListCrossNodeDuplicateCandidates :many
SELECT to_jsonb(candidate) AS candidate
FROM public.control_list_cross_node_duplicate_candidates_v1() AS candidate
`

// Same eligible-owner predicate as ListEligibleOwnersByAccountKey, via the
// SECURITY DEFINER function control_list_cross_node_duplicate_candidates_v1,
// grouped by account_key and filtered to account_keys with >= 2 distinct
// eligible owner Nodes. One row per account_key (no Node-pair fan-out).
// sqlc cannot resolve individual columns of a multi-column TABLE-returning
// function without a live database connection (same limitation the existing
// QueryCurrentAccountInventoryV1 already works around); the composite row is
// therefore wrapped in to_jsonb and decoded on the Go side, exactly like
// queries/account_inventory_readonly_query.sql.
func (q *Queries) ListCrossNodeDuplicateCandidates(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listCrossNodeDuplicateCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var candidate []byte
		if err := rows.Scan(&candidate); err != nil {
			return nil, err
		}
		items = append(items, candidate)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleOwnersByAccountKey = `-- name: ListEligibleOwnersByAccountKey :many
SELECT control_list_eligible_cross_node_owners_v1
FROM public.control_list_eligible_cross_node_owners_v1($1::text)
`

// Phase 2 (add-cross-node-duplicate-ownership): calls the SECURITY DEFINER
// readonly function control_list_eligible_cross_node_owners_v1
// (migrations/00014_cross_node_duplicate_ownership_query_access.sql), which
// implements the exact eligible-owner predicate frozen in design.md Phase 1A.
// relay_control_runtime has EXECUTE on the function but no direct SELECT on
// account_inventory / account_inventory_provider_states.
func (q *Queries) ListEligibleOwnersByAccountKey(ctx context.Context, accountKey string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listEligibleOwnersByAccountKey, accountKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var control_list_eligible_cross_node_owners_v1 pgtype.UUID
		if err := rows.Scan(&control_list_eligible_cross_node_owners_v1); err != nil {
			return nil, err
		}
		items = append(items, control_list_eligible_cross_node_owners_v1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
