// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cross_node_duplicate_ownership_metrics.sql

package store

import (
	"context"
)

const countCrossNodeDuplicateOccurrencesByEnvironmentAndStatus = `-- name: CountCrossNodeDuplicateOccurrencesByEnvironmentAndStatus :many

SELECT
    environment_id,
    status,
    count(*)::bigint AS occurrence_count
FROM cross_node_duplicate_occurrences
GROUP BY environment_id, status
`

type CountCrossNodeDuplicateOccurrencesByEnvironmentAndStatusRow struct {
	EnvironmentID   string `json:"environment_id"`
	Status          string `json:"status"`
	OccurrenceCount int64  `json:"occurrence_count"`
}

// Phase 6c (add-cross-node-duplicate-ownership) minimal Prometheus metrics
// source query. Only SELECTs from the Phase 1B occurrence table (already
// granted to relay_control_runtime, see 00013) -- no new migration/grant.
// Grouped only by (environment_id, status): conflict_type and severity are
// both fixed single-valued strings for this capability
// ("cross_node_duplicate_ownership" / "Critical"), so they are not
// selected here; the metrics collector attaches them as constant labels.
// Never groups by account_key/email/occurrence_id/instance_id (forbidden
// high-cardinality Prometheus labels).
func (q *Queries) CountCrossNodeDuplicateOccurrencesByEnvironmentAndStatus(ctx context.Context) ([]CountCrossNodeDuplicateOccurrencesByEnvironmentAndStatusRow, error) {
	rows, err := q.db.Query(ctx, countCrossNodeDuplicateOccurrencesByEnvironmentAndStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCrossNodeDuplicateOccurrencesByEnvironmentAndStatusRow{}
	for rows.Next() {
		var i CountCrossNodeDuplicateOccurrencesByEnvironmentAndStatusRow
		if err := rows.Scan(&i.EnvironmentID, &i.Status, &i.OccurrenceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
