// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cross_node_duplicate_ownership_occurrence_read_model.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCrossNodeDuplicateOccurrence = `-- name: GetCrossNodeDuplicateOccurrence :one
SELECT
    occurrence.occurrence_id,
    occurrence.environment_id,
    occurrence.account_key,
    occurrence.conflict_type,
    occurrence.status,
    occurrence.severity,
    occurrence.first_seen_at,
    occurrence.last_seen_at,
    occurrence.resolved_at,
    occurrence.evidence_state,
    occurrence.last_fully_verified_at,
    occurrence.latest_evaluation_id,
    COALESCE(affected.instance_ids, ARRAY[]::uuid[])::uuid[] AS affected_node_ids
FROM cross_node_duplicate_occurrences AS occurrence
LEFT JOIN LATERAL (
    SELECT array_agg(node.instance_id ORDER BY node.instance_id) AS instance_ids
    FROM cross_node_duplicate_occurrence_nodes AS node
    WHERE node.occurrence_id = occurrence.occurrence_id
) AS affected ON true
WHERE occurrence.occurrence_id = $1::uuid
`

type GetCrossNodeDuplicateOccurrenceRow struct {
	OccurrenceID        pgtype.UUID        `json:"occurrence_id"`
	EnvironmentID       string             `json:"environment_id"`
	AccountKey          string             `json:"account_key"`
	ConflictType        string             `json:"conflict_type"`
	Status              string             `json:"status"`
	Severity            string             `json:"severity"`
	FirstSeenAt         pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	ResolvedAt          pgtype.Timestamptz `json:"resolved_at"`
	EvidenceState       string             `json:"evidence_state"`
	LastFullyVerifiedAt pgtype.Timestamptz `json:"last_fully_verified_at"`
	LatestEvaluationID  pgtype.UUID        `json:"latest_evaluation_id"`
	AffectedNodeIds     []pgtype.UUID      `json:"affected_node_ids"`
}

func (q *Queries) GetCrossNodeDuplicateOccurrence(ctx context.Context, occurrenceID pgtype.UUID) (GetCrossNodeDuplicateOccurrenceRow, error) {
	row := q.db.QueryRow(ctx, getCrossNodeDuplicateOccurrence, occurrenceID)
	var i GetCrossNodeDuplicateOccurrenceRow
	err := row.Scan(
		&i.OccurrenceID,
		&i.EnvironmentID,
		&i.AccountKey,
		&i.ConflictType,
		&i.Status,
		&i.Severity,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.EvidenceState,
		&i.LastFullyVerifiedAt,
		&i.LatestEvaluationID,
		&i.AffectedNodeIds,
	)
	return i, err
}

const listCrossNodeDuplicateOccurrenceEvidence = `-- name: ListCrossNodeDuplicateOccurrenceEvidence :many
SELECT
    evidence.observation_id,
    evidence.instance_id,
    evidence.observation_kind,
    evidence.source_provider,
    evidence.source_scheduled_at,
    evidence.source_completed_at,
    evidence.source_poll_run_id,
    evidence.evaluation_id,
    evidence.evaluation_at,
    evidence.recorded_at
FROM cross_node_duplicate_occurrence_evidence AS evidence
WHERE evidence.occurrence_id = $1::uuid
  AND (
      $2::timestamptz IS NULL
      OR (evidence.recorded_at, evidence.observation_id) < (
          $2::timestamptz,
          $3::uuid
      )
  )
ORDER BY evidence.recorded_at DESC, evidence.observation_id DESC
LIMIT $4
`

type ListCrossNodeDuplicateOccurrenceEvidenceParams struct {
	OccurrenceID       pgtype.UUID        `json:"occurrence_id"`
	AfterRecordedAt    pgtype.Timestamptz `json:"after_recorded_at"`
	AfterObservationID pgtype.UUID        `json:"after_observation_id"`
	PageSize           int32              `json:"page_size"`
}

type ListCrossNodeDuplicateOccurrenceEvidenceRow struct {
	ObservationID     pgtype.UUID        `json:"observation_id"`
	InstanceID        pgtype.UUID        `json:"instance_id"`
	ObservationKind   string             `json:"observation_kind"`
	SourceProvider    string             `json:"source_provider"`
	SourceScheduledAt pgtype.Timestamptz `json:"source_scheduled_at"`
	SourceCompletedAt pgtype.Timestamptz `json:"source_completed_at"`
	SourcePollRunID   pgtype.UUID        `json:"source_poll_run_id"`
	EvaluationID      pgtype.UUID        `json:"evaluation_id"`
	EvaluationAt      pgtype.Timestamptz `json:"evaluation_at"`
	RecordedAt        pgtype.Timestamptz `json:"recorded_at"`
}

// Bounded, keyset-paginated evidence history for one occurrence, ordered
// (recorded_at DESC, observation_id DESC) -- most recent observation first.
// This is a separate, independently-paginated query so a list-occurrence
// call never has to return unbounded evidence history inline.
func (q *Queries) ListCrossNodeDuplicateOccurrenceEvidence(ctx context.Context, arg ListCrossNodeDuplicateOccurrenceEvidenceParams) ([]ListCrossNodeDuplicateOccurrenceEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listCrossNodeDuplicateOccurrenceEvidence,
		arg.OccurrenceID,
		arg.AfterRecordedAt,
		arg.AfterObservationID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCrossNodeDuplicateOccurrenceEvidenceRow{}
	for rows.Next() {
		var i ListCrossNodeDuplicateOccurrenceEvidenceRow
		if err := rows.Scan(
			&i.ObservationID,
			&i.InstanceID,
			&i.ObservationKind,
			&i.SourceProvider,
			&i.SourceScheduledAt,
			&i.SourceCompletedAt,
			&i.SourcePollRunID,
			&i.EvaluationID,
			&i.EvaluationAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrossNodeDuplicateOccurrences = `-- name: ListCrossNodeDuplicateOccurrences :many

SELECT
    occurrence.occurrence_id,
    occurrence.environment_id,
    occurrence.account_key,
    occurrence.conflict_type,
    occurrence.status,
    occurrence.severity,
    occurrence.first_seen_at,
    occurrence.last_seen_at,
    occurrence.resolved_at,
    occurrence.evidence_state,
    occurrence.last_fully_verified_at,
    occurrence.latest_evaluation_id,
    COALESCE(affected.instance_ids, ARRAY[]::uuid[])::uuid[] AS affected_node_ids
FROM cross_node_duplicate_occurrences AS occurrence
LEFT JOIN LATERAL (
    SELECT array_agg(node.instance_id ORDER BY node.instance_id) AS instance_ids
    FROM cross_node_duplicate_occurrence_nodes AS node
    WHERE node.occurrence_id = occurrence.occurrence_id
) AS affected ON true
WHERE ($1::text IS NULL OR occurrence.status = $1)
  AND ($2::text IS NULL OR occurrence.account_key = $2)
  AND (
      $3::uuid IS NULL
      OR EXISTS (
          SELECT 1 FROM cross_node_duplicate_occurrence_nodes AS filter_node
          WHERE filter_node.occurrence_id = occurrence.occurrence_id
            AND filter_node.instance_id = $3::uuid
      )
  )
  AND (
      $4::timestamptz IS NULL
      OR (occurrence.last_seen_at, occurrence.occurrence_id) < (
          $4::timestamptz,
          $5::uuid
      )
  )
ORDER BY occurrence.last_seen_at DESC, occurrence.occurrence_id DESC
LIMIT $6
`

type ListCrossNodeDuplicateOccurrencesParams struct {
	Status            pgtype.Text        `json:"status"`
	AccountKey        pgtype.Text        `json:"account_key"`
	InstanceID        pgtype.UUID        `json:"instance_id"`
	AfterLastSeenAt   pgtype.Timestamptz `json:"after_last_seen_at"`
	AfterOccurrenceID pgtype.UUID        `json:"after_occurrence_id"`
	PageSize          int32              `json:"page_size"`
}

type ListCrossNodeDuplicateOccurrencesRow struct {
	OccurrenceID        pgtype.UUID        `json:"occurrence_id"`
	EnvironmentID       string             `json:"environment_id"`
	AccountKey          string             `json:"account_key"`
	ConflictType        string             `json:"conflict_type"`
	Status              string             `json:"status"`
	Severity            string             `json:"severity"`
	FirstSeenAt         pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	ResolvedAt          pgtype.Timestamptz `json:"resolved_at"`
	EvidenceState       string             `json:"evidence_state"`
	LastFullyVerifiedAt pgtype.Timestamptz `json:"last_fully_verified_at"`
	LatestEvaluationID  pgtype.UUID        `json:"latest_evaluation_id"`
	AffectedNodeIds     []pgtype.UUID      `json:"affected_node_ids"`
}

// Phase 5 (add-cross-node-duplicate-ownership) read-only occurrence read
// model. These queries only SELECT from the Phase 1B tables
// (cross_node_duplicate_occurrences / _nodes / _evidence,
// migrations/00013_cross_node_duplicate_ownership_foundation.sql) which
// relay_control_runtime already holds SELECT on -- no new migration/grant is
// needed here (unlike Phase 2's Account Inventory query-access boundary).
// account_key is returned as plaintext by design (frozen non-goal: no
// masked/HMAC/fingerprint handling for this capability).
// Bounded, keyset-paginated list ordered by (last_seen_at DESC,
// occurrence_id DESC) -- most recently active first. affected_nodes is
// aggregated via a LATERAL subquery so the list response never needs a
// second round-trip per occurrence. instance_id filtering uses EXISTS
// against cross_node_duplicate_occurrence_nodes rather than a JOIN, so an
// occurrence with N affected Nodes is never duplicated in the page.
func (q *Queries) ListCrossNodeDuplicateOccurrences(ctx context.Context, arg ListCrossNodeDuplicateOccurrencesParams) ([]ListCrossNodeDuplicateOccurrencesRow, error) {
	rows, err := q.db.Query(ctx, listCrossNodeDuplicateOccurrences,
		arg.Status,
		arg.AccountKey,
		arg.InstanceID,
		arg.AfterLastSeenAt,
		arg.AfterOccurrenceID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCrossNodeDuplicateOccurrencesRow{}
	for rows.Next() {
		var i ListCrossNodeDuplicateOccurrencesRow
		if err := rows.Scan(
			&i.OccurrenceID,
			&i.EnvironmentID,
			&i.AccountKey,
			&i.ConflictType,
			&i.Status,
			&i.Severity,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.EvidenceState,
			&i.LastFullyVerifiedAt,
			&i.LatestEvaluationID,
			&i.AffectedNodeIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
