// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_account_directory_ingestion.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGatewayDirectoryIngestionRun = `-- name: ClaimGatewayDirectoryIngestionRun :one
WITH db_now AS (
    SELECT clock_timestamp() AS db_now
), candidate AS (
    SELECT run.ingestion_run_id
    FROM gateway_directory_ingestion_runs AS run, db_now
    WHERE run.gateway_instance_id = $1::uuid
      AND run.status IN ('pending', 'retry_wait')
      AND run.attempt_count < 2
      AND db_now.db_now < run.scheduled_at + interval '120 seconds'
    ORDER BY run.scheduled_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
), updated AS (
    UPDATE gateway_directory_ingestion_runs AS run
    SET status = 'running',
        attempt_count = run.attempt_count + 1,
        first_started_at = COALESCE(run.first_started_at, db_now.db_now),
        last_started_at = db_now.db_now,
        lease_expires_at = db_now.db_now + interval '15 seconds',
        lease_fencing_token = $2::uuid
    FROM candidate, db_now
    WHERE run.ingestion_run_id = candidate.ingestion_run_id
    RETURNING run.ingestion_run_id, run.gateway_instance_id, run.scheduled_at, run.status, run.attempt_count, run.created_at, run.first_started_at, run.last_started_at, run.lease_expires_at, run.lease_fencing_token, run.terminal_at, run.outcome, run.last_failure_class, run.source_generated_at, run.received_at, run.content_fingerprint, run.snapshot_id, run.account_count
)
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count FROM updated
`

type ClaimGatewayDirectoryIngestionRunParams struct {
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
}

type ClaimGatewayDirectoryIngestionRunRow struct {
	IngestionRunID     pgtype.UUID        `json:"ingestion_run_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	Status             string             `json:"status"`
	AttemptCount       int16              `json:"attempt_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FirstStartedAt     pgtype.Timestamptz `json:"first_started_at"`
	LastStartedAt      pgtype.Timestamptz `json:"last_started_at"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	LeaseFencingToken  pgtype.UUID        `json:"lease_fencing_token"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
	Outcome            pgtype.Text        `json:"outcome"`
	LastFailureClass   pgtype.Text        `json:"last_failure_class"`
	SourceGeneratedAt  pgtype.Timestamptz `json:"source_generated_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ContentFingerprint []byte             `json:"content_fingerprint"`
	SnapshotID         pgtype.UUID        `json:"snapshot_id"`
	AccountCount       pgtype.Int4        `json:"account_count"`
}

func (q *Queries) ClaimGatewayDirectoryIngestionRun(ctx context.Context, arg ClaimGatewayDirectoryIngestionRunParams) (ClaimGatewayDirectoryIngestionRunRow, error) {
	row := q.db.QueryRow(ctx, claimGatewayDirectoryIngestionRun, arg.GatewayInstanceID, arg.LeaseFencingToken)
	var i ClaimGatewayDirectoryIngestionRunRow
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
	)
	return i, err
}

const createOrGetGatewayDirectoryIngestionRun = `-- name: CreateOrGetGatewayDirectoryIngestionRun :one
WITH locked_gateway AS (
    SELECT instance_id
    FROM gateway_instances
    WHERE instance_id = $1::uuid
    FOR UPDATE
), db_now AS (
    SELECT clock_timestamp() AS db_now
), current_slot AS (
    SELECT to_timestamp(floor(extract(epoch FROM db_now.db_now) / 180) * 180)::timestamptz AS scheduled_at
    FROM db_now
), active_gateway AS (
    SELECT 1
    FROM gateway_directory_ingestion_runs AS active
    JOIN locked_gateway ON active.gateway_instance_id = locked_gateway.instance_id
    WHERE active.status IN ('pending', 'running', 'retry_wait')
    LIMIT 1
), inserted AS (
    INSERT INTO gateway_directory_ingestion_runs (
        gateway_instance_id,
        scheduled_at
    ) SELECT
        locked_gateway.instance_id,
        current_slot.scheduled_at
    FROM locked_gateway
    CROSS JOIN current_slot
    WHERE NOT EXISTS (SELECT 1 FROM active_gateway)
    ON CONFLICT (gateway_instance_id, scheduled_at) DO NOTHING
    RETURNING ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count, true AS created
)
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count, created FROM inserted
UNION ALL
SELECT existing.ingestion_run_id, existing.gateway_instance_id, existing.scheduled_at, existing.status, existing.attempt_count, existing.created_at, existing.first_started_at, existing.last_started_at, existing.lease_expires_at, existing.lease_fencing_token, existing.terminal_at, existing.outcome, existing.last_failure_class, existing.source_generated_at, existing.received_at, existing.content_fingerprint, existing.snapshot_id, existing.account_count, false AS created
FROM gateway_directory_ingestion_runs AS existing
JOIN locked_gateway ON existing.gateway_instance_id = locked_gateway.instance_id
JOIN current_slot ON existing.scheduled_at = current_slot.scheduled_at
WHERE NOT EXISTS (SELECT 1 FROM active_gateway)
  AND NOT EXISTS (SELECT 1 FROM inserted)
LIMIT 1
`

type CreateOrGetGatewayDirectoryIngestionRunRow struct {
	IngestionRunID     pgtype.UUID        `json:"ingestion_run_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	Status             string             `json:"status"`
	AttemptCount       int16              `json:"attempt_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FirstStartedAt     pgtype.Timestamptz `json:"first_started_at"`
	LastStartedAt      pgtype.Timestamptz `json:"last_started_at"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	LeaseFencingToken  pgtype.UUID        `json:"lease_fencing_token"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
	Outcome            pgtype.Text        `json:"outcome"`
	LastFailureClass   pgtype.Text        `json:"last_failure_class"`
	SourceGeneratedAt  pgtype.Timestamptz `json:"source_generated_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ContentFingerprint []byte             `json:"content_fingerprint"`
	SnapshotID         pgtype.UUID        `json:"snapshot_id"`
	AccountCount       pgtype.Int4        `json:"account_count"`
	Created            bool               `json:"created"`
}

func (q *Queries) CreateOrGetGatewayDirectoryIngestionRun(ctx context.Context, gatewayInstanceID pgtype.UUID) (CreateOrGetGatewayDirectoryIngestionRunRow, error) {
	row := q.db.QueryRow(ctx, createOrGetGatewayDirectoryIngestionRun, gatewayInstanceID)
	var i CreateOrGetGatewayDirectoryIngestionRunRow
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
		&i.Created,
	)
	return i, err
}

const getGatewayDirectoryCurrentState = `-- name: GetGatewayDirectoryCurrentState :one
SELECT gateway_instance_id, current_snapshot_id, current_content_fingerprint, last_success_received_at, last_source_generated_at, last_success_run_id, updated_at
FROM gateway_directory_current_state
WHERE gateway_instance_id = $1::uuid
`

func (q *Queries) GetGatewayDirectoryCurrentState(ctx context.Context, gatewayInstanceID pgtype.UUID) (GatewayDirectoryCurrentState, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryCurrentState, gatewayInstanceID)
	var i GatewayDirectoryCurrentState
	err := row.Scan(
		&i.GatewayInstanceID,
		&i.CurrentSnapshotID,
		&i.CurrentContentFingerprint,
		&i.LastSuccessReceivedAt,
		&i.LastSourceGeneratedAt,
		&i.LastSuccessRunID,
		&i.UpdatedAt,
	)
	return i, err
}

const getGatewayDirectoryIngestionRun = `-- name: GetGatewayDirectoryIngestionRun :one
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count
FROM gateway_directory_ingestion_runs
WHERE ingestion_run_id = $1::uuid
`

func (q *Queries) GetGatewayDirectoryIngestionRun(ctx context.Context, ingestionRunID pgtype.UUID) (GatewayDirectoryIngestionRun, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryIngestionRun, ingestionRunID)
	var i GatewayDirectoryIngestionRun
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
	)
	return i, err
}

const getGatewayDirectoryIngestionRunLease = `-- name: GetGatewayDirectoryIngestionRunLease :one
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count
FROM gateway_directory_ingestion_runs
WHERE ingestion_run_id = $1::uuid
  AND gateway_instance_id = $2::uuid
  AND status = 'running'
  AND lease_fencing_token = $3::uuid
  AND lease_expires_at > clock_timestamp()
`

type GetGatewayDirectoryIngestionRunLeaseParams struct {
	IngestionRunID    pgtype.UUID `json:"ingestion_run_id"`
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
}

func (q *Queries) GetGatewayDirectoryIngestionRunLease(ctx context.Context, arg GetGatewayDirectoryIngestionRunLeaseParams) (GatewayDirectoryIngestionRun, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryIngestionRunLease, arg.IngestionRunID, arg.GatewayInstanceID, arg.LeaseFencingToken)
	var i GatewayDirectoryIngestionRun
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
	)
	return i, err
}

const getGatewayDirectoryReadTarget = `-- name: GetGatewayDirectoryReadTarget :one
SELECT instance_id, management_endpoint, reader_secret_ref
FROM gateway_instances
WHERE instance_id = $1::uuid
`

type GetGatewayDirectoryReadTargetRow struct {
	InstanceID         pgtype.UUID `json:"instance_id"`
	ManagementEndpoint string      `json:"management_endpoint"`
	ReaderSecretRef    pgtype.Text `json:"reader_secret_ref"`
}

func (q *Queries) GetGatewayDirectoryReadTarget(ctx context.Context, gatewayInstanceID pgtype.UUID) (GetGatewayDirectoryReadTargetRow, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryReadTarget, gatewayInstanceID)
	var i GetGatewayDirectoryReadTargetRow
	err := row.Scan(&i.InstanceID, &i.ManagementEndpoint, &i.ReaderSecretRef)
	return i, err
}

const getGatewayDirectorySnapshotByFingerprint = `-- name: GetGatewayDirectorySnapshotByFingerprint :one
SELECT snapshot_id, gateway_instance_id, fingerprint, fingerprint_encoding_version, schema_version, account_count, created_at
FROM gateway_directory_snapshots
WHERE gateway_instance_id = $1::uuid
  AND fingerprint = $2::bytea
`

type GetGatewayDirectorySnapshotByFingerprintParams struct {
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	Fingerprint       []byte      `json:"fingerprint"`
}

func (q *Queries) GetGatewayDirectorySnapshotByFingerprint(ctx context.Context, arg GetGatewayDirectorySnapshotByFingerprintParams) (GatewayDirectorySnapshot, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectorySnapshotByFingerprint, arg.GatewayInstanceID, arg.Fingerprint)
	var i GatewayDirectorySnapshot
	err := row.Scan(
		&i.SnapshotID,
		&i.GatewayInstanceID,
		&i.Fingerprint,
		&i.FingerprintEncodingVersion,
		&i.SchemaVersion,
		&i.AccountCount,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredGatewayDirectoryIngestionRuns = `-- name: ListExpiredGatewayDirectoryIngestionRuns :many
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count
FROM gateway_directory_ingestion_runs
WHERE status = 'running'
  AND lease_expires_at IS NOT NULL
  AND lease_expires_at <= clock_timestamp()
ORDER BY lease_expires_at, scheduled_at, gateway_instance_id
LIMIT $1::integer
`

func (q *Queries) ListExpiredGatewayDirectoryIngestionRuns(ctx context.Context, pageLimit int32) ([]GatewayDirectoryIngestionRun, error) {
	rows, err := q.db.Query(ctx, listExpiredGatewayDirectoryIngestionRuns, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayDirectoryIngestionRun{}
	for rows.Next() {
		var i GatewayDirectoryIngestionRun
		if err := rows.Scan(
			&i.IngestionRunID,
			&i.GatewayInstanceID,
			&i.ScheduledAt,
			&i.Status,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.FirstStartedAt,
			&i.LastStartedAt,
			&i.LeaseExpiresAt,
			&i.LeaseFencingToken,
			&i.TerminalAt,
			&i.Outcome,
			&i.LastFailureClass,
			&i.SourceGeneratedAt,
			&i.ReceivedAt,
			&i.ContentFingerprint,
			&i.SnapshotID,
			&i.AccountCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayDirectorySnapshotItems = `-- name: ListGatewayDirectorySnapshotItems :many
SELECT snapshot_id, account_id, name, platform, type, url, status
FROM gateway_directory_snapshot_items
WHERE snapshot_id = $1::uuid
ORDER BY account_id ASC
`

func (q *Queries) ListGatewayDirectorySnapshotItems(ctx context.Context, snapshotID pgtype.UUID) ([]GatewayDirectorySnapshotItem, error) {
	rows, err := q.db.Query(ctx, listGatewayDirectorySnapshotItems, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayDirectorySnapshotItem{}
	for rows.Next() {
		var i GatewayDirectorySnapshotItem
		if err := rows.Scan(
			&i.SnapshotID,
			&i.AccountID,
			&i.Name,
			&i.Platform,
			&i.Type,
			&i.Url,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
