// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_account_directory_ingestion.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGatewayDirectoryIngestionRun = `-- name: ClaimGatewayDirectoryIngestionRun :one
WITH db_now AS (
    SELECT clock_timestamp() AS db_now
), candidate AS (
    SELECT run.ingestion_run_id
    FROM gateway_directory_ingestion_runs AS run, db_now
    WHERE run.gateway_instance_id = $1::uuid
      AND run.status IN ('pending', 'retry_wait')
      AND run.attempt_count < 2
      AND db_now.db_now < run.scheduled_at + interval '120 seconds'
    ORDER BY run.scheduled_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
), updated AS (
    UPDATE gateway_directory_ingestion_runs AS run
    SET status = 'running',
        attempt_count = run.attempt_count + 1,
        first_started_at = COALESCE(run.first_started_at, db_now.db_now),
        last_started_at = db_now.db_now,
        lease_expires_at = db_now.db_now + interval '15 seconds',
        lease_fencing_token = $2::uuid
    FROM candidate, db_now
    WHERE run.ingestion_run_id = candidate.ingestion_run_id
    RETURNING run.ingestion_run_id, run.gateway_instance_id, run.scheduled_at, run.status, run.attempt_count, run.created_at, run.first_started_at, run.last_started_at, run.lease_expires_at, run.lease_fencing_token, run.terminal_at, run.outcome, run.last_failure_class, run.source_generated_at, run.received_at, run.content_fingerprint, run.snapshot_id, run.account_count
)
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count FROM updated
`

type ClaimGatewayDirectoryIngestionRunParams struct {
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
}

type ClaimGatewayDirectoryIngestionRunRow struct {
	IngestionRunID     pgtype.UUID        `json:"ingestion_run_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	Status             string             `json:"status"`
	AttemptCount       int16              `json:"attempt_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FirstStartedAt     pgtype.Timestamptz `json:"first_started_at"`
	LastStartedAt      pgtype.Timestamptz `json:"last_started_at"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	LeaseFencingToken  pgtype.UUID        `json:"lease_fencing_token"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
	Outcome            pgtype.Text        `json:"outcome"`
	LastFailureClass   pgtype.Text        `json:"last_failure_class"`
	SourceGeneratedAt  pgtype.Timestamptz `json:"source_generated_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ContentFingerprint []byte             `json:"content_fingerprint"`
	SnapshotID         pgtype.UUID        `json:"snapshot_id"`
	AccountCount       pgtype.Int4        `json:"account_count"`
}

func (q *Queries) ClaimGatewayDirectoryIngestionRun(ctx context.Context, arg ClaimGatewayDirectoryIngestionRunParams) (ClaimGatewayDirectoryIngestionRunRow, error) {
	row := q.db.QueryRow(ctx, claimGatewayDirectoryIngestionRun, arg.GatewayInstanceID, arg.LeaseFencingToken)
	var i ClaimGatewayDirectoryIngestionRunRow
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
	)
	return i, err
}

const createOrGetGatewayDirectoryIngestionRun = `-- name: CreateOrGetGatewayDirectoryIngestionRun :one
WITH locked_gateway AS (
    SELECT instance_id
    FROM gateway_instances
    WHERE instance_id = $1::uuid
    FOR UPDATE
), db_now AS (
    SELECT clock_timestamp() AS db_now
), current_slot AS (
    SELECT to_timestamp(floor(extract(epoch FROM db_now.db_now) / 180) * 180)::timestamptz AS scheduled_at
    FROM db_now
), active_gateway AS (
    SELECT 1
    FROM gateway_directory_ingestion_runs AS active
    JOIN locked_gateway ON active.gateway_instance_id = locked_gateway.instance_id
    WHERE active.status IN ('pending', 'running', 'retry_wait')
    LIMIT 1
), inserted AS (
    INSERT INTO gateway_directory_ingestion_runs (
        gateway_instance_id,
        scheduled_at
    ) SELECT
        locked_gateway.instance_id,
        current_slot.scheduled_at
    FROM locked_gateway
    CROSS JOIN current_slot
    WHERE NOT EXISTS (SELECT 1 FROM active_gateway)
    ON CONFLICT (gateway_instance_id, scheduled_at) DO NOTHING
    RETURNING ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count, true AS created
)
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count, created FROM inserted
UNION ALL
SELECT existing.ingestion_run_id, existing.gateway_instance_id, existing.scheduled_at, existing.status, existing.attempt_count, existing.created_at, existing.first_started_at, existing.last_started_at, existing.lease_expires_at, existing.lease_fencing_token, existing.terminal_at, existing.outcome, existing.last_failure_class, existing.source_generated_at, existing.received_at, existing.content_fingerprint, existing.snapshot_id, existing.account_count, false AS created
FROM gateway_directory_ingestion_runs AS existing
JOIN locked_gateway ON existing.gateway_instance_id = locked_gateway.instance_id
JOIN current_slot ON existing.scheduled_at = current_slot.scheduled_at
WHERE NOT EXISTS (SELECT 1 FROM active_gateway)
  AND NOT EXISTS (SELECT 1 FROM inserted)
LIMIT 1
`

type CreateOrGetGatewayDirectoryIngestionRunRow struct {
	IngestionRunID     pgtype.UUID        `json:"ingestion_run_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	Status             string             `json:"status"`
	AttemptCount       int16              `json:"attempt_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FirstStartedAt     pgtype.Timestamptz `json:"first_started_at"`
	LastStartedAt      pgtype.Timestamptz `json:"last_started_at"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	LeaseFencingToken  pgtype.UUID        `json:"lease_fencing_token"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
	Outcome            pgtype.Text        `json:"outcome"`
	LastFailureClass   pgtype.Text        `json:"last_failure_class"`
	SourceGeneratedAt  pgtype.Timestamptz `json:"source_generated_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ContentFingerprint []byte             `json:"content_fingerprint"`
	SnapshotID         pgtype.UUID        `json:"snapshot_id"`
	AccountCount       pgtype.Int4        `json:"account_count"`
	Created            bool               `json:"created"`
}

func (q *Queries) CreateOrGetGatewayDirectoryIngestionRun(ctx context.Context, gatewayInstanceID pgtype.UUID) (CreateOrGetGatewayDirectoryIngestionRunRow, error) {
	row := q.db.QueryRow(ctx, createOrGetGatewayDirectoryIngestionRun, gatewayInstanceID)
	var i CreateOrGetGatewayDirectoryIngestionRunRow
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
		&i.Created,
	)
	return i, err
}

const finalizeGatewayDirectoryIngestionRunSucceeded = `-- name: FinalizeGatewayDirectoryIngestionRunSucceeded :one
WITH final_now AS (
    SELECT clock_timestamp() AS db_now
), lease_guard AS (
    SELECT
        EXISTS (
            SELECT 1
            FROM gateway_directory_ingestion_runs AS run, final_now
            WHERE run.ingestion_run_id = $1::uuid
              AND run.gateway_instance_id = $2::uuid
              AND run.status = 'running'
              AND run.lease_fencing_token = $3::uuid
              AND run.lease_expires_at > final_now.db_now
        ) AS lease_valid,
        EXISTS (
            SELECT 1
            FROM gateway_directory_ingestion_runs AS run, final_now
            WHERE run.ingestion_run_id = $1::uuid
              AND run.gateway_instance_id = $2::uuid
              AND run.status = 'running'
              AND run.lease_fencing_token = $3::uuid
              AND run.lease_expires_at > final_now.db_now
              AND $4::timestamptz <= final_now.db_now + interval '30 seconds'
              AND $4::timestamptz >= final_now.db_now - interval '24 hours'
              AND (
                  $5::timestamptz IS NULL
                  OR $4::timestamptz >= $5::timestamptz - interval '5 minutes'
              )
        ) AS source_time_valid
), updated AS (
    UPDATE gateway_directory_ingestion_runs AS run
    SET status = 'succeeded',
        terminal_at = final_now.db_now,
        received_at = final_now.db_now,
        source_generated_at = $4::timestamptz,
        content_fingerprint = $6::bytea,
        snapshot_id = $7::uuid,
        account_count = $8::integer,
        outcome = $9::text,
        lease_expires_at = NULL,
        lease_fencing_token = NULL
    FROM final_now, lease_guard
    WHERE run.ingestion_run_id = $1::uuid
      AND run.gateway_instance_id = $2::uuid
      AND run.status = 'running'
      AND run.lease_fencing_token = $3::uuid
      AND lease_guard.lease_valid
      AND lease_guard.source_time_valid
    RETURNING 'succeeded'::text AS decision, final_now.db_now::timestamptz AS final_received_at
), source_time_invalid AS (
    SELECT 'source_time_invalid'::text AS decision, final_now.db_now::timestamptz AS final_received_at
    FROM final_now, lease_guard
    WHERE lease_guard.lease_valid
      AND NOT lease_guard.source_time_valid
), lost_lease AS (
    SELECT 'lost_lease'::text AS decision, final_now.db_now::timestamptz AS final_received_at
    FROM final_now, lease_guard
    WHERE NOT lease_guard.lease_valid
)
SELECT decision, final_received_at FROM updated
UNION ALL
SELECT decision, final_received_at FROM source_time_invalid
UNION ALL
SELECT decision, final_received_at FROM lost_lease
LIMIT 1
`

type FinalizeGatewayDirectoryIngestionRunSucceededParams struct {
	IngestionRunID            pgtype.UUID        `json:"ingestion_run_id"`
	GatewayInstanceID         pgtype.UUID        `json:"gateway_instance_id"`
	LeaseFencingToken         pgtype.UUID        `json:"lease_fencing_token"`
	SourceGeneratedAt         pgtype.Timestamptz `json:"source_generated_at"`
	PreviousSourceGeneratedAt pgtype.Timestamptz `json:"previous_source_generated_at"`
	ContentFingerprint        []byte             `json:"content_fingerprint"`
	SnapshotID                pgtype.UUID        `json:"snapshot_id"`
	AccountCount              int32              `json:"account_count"`
	Outcome                   string             `json:"outcome"`
}

type FinalizeGatewayDirectoryIngestionRunSucceededRow struct {
	Decision        string             `json:"decision"`
	FinalReceivedAt pgtype.Timestamptz `json:"final_received_at"`
}

func (q *Queries) FinalizeGatewayDirectoryIngestionRunSucceeded(ctx context.Context, arg FinalizeGatewayDirectoryIngestionRunSucceededParams) (FinalizeGatewayDirectoryIngestionRunSucceededRow, error) {
	row := q.db.QueryRow(ctx, finalizeGatewayDirectoryIngestionRunSucceeded,
		arg.IngestionRunID,
		arg.GatewayInstanceID,
		arg.LeaseFencingToken,
		arg.SourceGeneratedAt,
		arg.PreviousSourceGeneratedAt,
		arg.ContentFingerprint,
		arg.SnapshotID,
		arg.AccountCount,
		arg.Outcome,
	)
	var i FinalizeGatewayDirectoryIngestionRunSucceededRow
	err := row.Scan(&i.Decision, &i.FinalReceivedAt)
	return i, err
}

const getGatewayDirectoryAttemptNow = `-- name: GetGatewayDirectoryAttemptNow :one
SELECT clock_timestamp()::timestamptz AS db_now
`

func (q *Queries) GetGatewayDirectoryAttemptNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryAttemptNow)
	var db_now pgtype.Timestamptz
	err := row.Scan(&db_now)
	return db_now, err
}

const getGatewayDirectoryCurrentState = `-- name: GetGatewayDirectoryCurrentState :one
SELECT gateway_instance_id, current_snapshot_id, current_content_fingerprint, last_success_received_at, last_source_generated_at, last_success_run_id, updated_at
FROM gateway_directory_current_state
WHERE gateway_instance_id = $1::uuid
`

func (q *Queries) GetGatewayDirectoryCurrentState(ctx context.Context, gatewayInstanceID pgtype.UUID) (GatewayDirectoryCurrentState, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryCurrentState, gatewayInstanceID)
	var i GatewayDirectoryCurrentState
	err := row.Scan(
		&i.GatewayInstanceID,
		&i.CurrentSnapshotID,
		&i.CurrentContentFingerprint,
		&i.LastSuccessReceivedAt,
		&i.LastSourceGeneratedAt,
		&i.LastSuccessRunID,
		&i.UpdatedAt,
	)
	return i, err
}

const getGatewayDirectoryCurrentStateForUpdate = `-- name: GetGatewayDirectoryCurrentStateForUpdate :one
SELECT gateway_instance_id, current_snapshot_id, current_content_fingerprint, last_success_received_at, last_source_generated_at, last_success_run_id, updated_at
FROM gateway_directory_current_state
WHERE gateway_instance_id = $1::uuid
FOR UPDATE
`

func (q *Queries) GetGatewayDirectoryCurrentStateForUpdate(ctx context.Context, gatewayInstanceID pgtype.UUID) (GatewayDirectoryCurrentState, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryCurrentStateForUpdate, gatewayInstanceID)
	var i GatewayDirectoryCurrentState
	err := row.Scan(
		&i.GatewayInstanceID,
		&i.CurrentSnapshotID,
		&i.CurrentContentFingerprint,
		&i.LastSuccessReceivedAt,
		&i.LastSourceGeneratedAt,
		&i.LastSuccessRunID,
		&i.UpdatedAt,
	)
	return i, err
}

const getGatewayDirectoryFinalizeRunningRun = `-- name: GetGatewayDirectoryFinalizeRunningRun :one
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count
FROM gateway_directory_ingestion_runs
WHERE ingestion_run_id = $1::uuid
  AND gateway_instance_id = $2::uuid
  AND status = 'running'
  AND lease_fencing_token = $3::uuid
  AND lease_expires_at > $4::timestamptz
FOR UPDATE
`

type GetGatewayDirectoryFinalizeRunningRunParams struct {
	IngestionRunID    pgtype.UUID        `json:"ingestion_run_id"`
	GatewayInstanceID pgtype.UUID        `json:"gateway_instance_id"`
	LeaseFencingToken pgtype.UUID        `json:"lease_fencing_token"`
	DbNow             pgtype.Timestamptz `json:"db_now"`
}

func (q *Queries) GetGatewayDirectoryFinalizeRunningRun(ctx context.Context, arg GetGatewayDirectoryFinalizeRunningRunParams) (GatewayDirectoryIngestionRun, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryFinalizeRunningRun,
		arg.IngestionRunID,
		arg.GatewayInstanceID,
		arg.LeaseFencingToken,
		arg.DbNow,
	)
	var i GatewayDirectoryIngestionRun
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
	)
	return i, err
}

const getGatewayDirectoryFreshnessMetrics = `-- name: GetGatewayDirectoryFreshnessMetrics :one
WITH db_now AS (
    SELECT clock_timestamp() AS db_now
)
SELECT
    count(*) FILTER (WHERE current_state.last_success_received_at IS NULL)::bigint AS unknown_count,
    count(*) FILTER (WHERE current_state.last_success_received_at IS NOT NULL
        AND db_now.db_now - current_state.last_success_received_at <= interval '540 seconds')::bigint AS fresh_count,
    count(*) FILTER (WHERE current_state.last_success_received_at IS NOT NULL
        AND db_now.db_now - current_state.last_success_received_at > interval '540 seconds')::bigint AS stale_count
FROM gateway_instances AS gateway
LEFT JOIN gateway_directory_current_state AS current_state
    ON current_state.gateway_instance_id = gateway.instance_id,
db_now
`

type GetGatewayDirectoryFreshnessMetricsRow struct {
	UnknownCount int64 `json:"unknown_count"`
	FreshCount   int64 `json:"fresh_count"`
	StaleCount   int64 `json:"stale_count"`
}

func (q *Queries) GetGatewayDirectoryFreshnessMetrics(ctx context.Context) (GetGatewayDirectoryFreshnessMetricsRow, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryFreshnessMetrics)
	var i GetGatewayDirectoryFreshnessMetricsRow
	err := row.Scan(&i.UnknownCount, &i.FreshCount, &i.StaleCount)
	return i, err
}

const getGatewayDirectoryIngestionRun = `-- name: GetGatewayDirectoryIngestionRun :one
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count
FROM gateway_directory_ingestion_runs
WHERE ingestion_run_id = $1::uuid
`

func (q *Queries) GetGatewayDirectoryIngestionRun(ctx context.Context, ingestionRunID pgtype.UUID) (GatewayDirectoryIngestionRun, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryIngestionRun, ingestionRunID)
	var i GatewayDirectoryIngestionRun
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
	)
	return i, err
}

const getGatewayDirectoryIngestionRunLease = `-- name: GetGatewayDirectoryIngestionRunLease :one
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count
FROM gateway_directory_ingestion_runs
WHERE ingestion_run_id = $1::uuid
  AND gateway_instance_id = $2::uuid
  AND status = 'running'
  AND lease_fencing_token = $3::uuid
  AND lease_expires_at > clock_timestamp()
`

type GetGatewayDirectoryIngestionRunLeaseParams struct {
	IngestionRunID    pgtype.UUID `json:"ingestion_run_id"`
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
}

func (q *Queries) GetGatewayDirectoryIngestionRunLease(ctx context.Context, arg GetGatewayDirectoryIngestionRunLeaseParams) (GatewayDirectoryIngestionRun, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryIngestionRunLease, arg.IngestionRunID, arg.GatewayInstanceID, arg.LeaseFencingToken)
	var i GatewayDirectoryIngestionRun
	err := row.Scan(
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
	)
	return i, err
}

const getGatewayDirectoryReadTarget = `-- name: GetGatewayDirectoryReadTarget :one
SELECT instance_id, management_endpoint, reader_secret_ref
FROM gateway_instances
WHERE instance_id = $1::uuid
`

type GetGatewayDirectoryReadTargetRow struct {
	InstanceID         pgtype.UUID `json:"instance_id"`
	ManagementEndpoint string      `json:"management_endpoint"`
	ReaderSecretRef    pgtype.Text `json:"reader_secret_ref"`
}

func (q *Queries) GetGatewayDirectoryReadTarget(ctx context.Context, gatewayInstanceID pgtype.UUID) (GetGatewayDirectoryReadTargetRow, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectoryReadTarget, gatewayInstanceID)
	var i GetGatewayDirectoryReadTargetRow
	err := row.Scan(&i.InstanceID, &i.ManagementEndpoint, &i.ReaderSecretRef)
	return i, err
}

const getGatewayDirectorySnapshotByFingerprint = `-- name: GetGatewayDirectorySnapshotByFingerprint :one
SELECT snapshot_id, gateway_instance_id, fingerprint, fingerprint_encoding_version, schema_version, account_count, created_at
FROM gateway_directory_snapshots
WHERE gateway_instance_id = $1::uuid
  AND fingerprint = $2::bytea
`

type GetGatewayDirectorySnapshotByFingerprintParams struct {
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	Fingerprint       []byte      `json:"fingerprint"`
}

func (q *Queries) GetGatewayDirectorySnapshotByFingerprint(ctx context.Context, arg GetGatewayDirectorySnapshotByFingerprintParams) (GatewayDirectorySnapshot, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectorySnapshotByFingerprint, arg.GatewayInstanceID, arg.Fingerprint)
	var i GatewayDirectorySnapshot
	err := row.Scan(
		&i.SnapshotID,
		&i.GatewayInstanceID,
		&i.Fingerprint,
		&i.FingerprintEncodingVersion,
		&i.SchemaVersion,
		&i.AccountCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertGatewayDirectorySnapshot = `-- name: InsertGatewayDirectorySnapshot :one
INSERT INTO gateway_directory_snapshots (
    gateway_instance_id,
    fingerprint,
    fingerprint_encoding_version,
    schema_version,
    account_count
) VALUES (
    $1::uuid,
    $2::bytea,
    1,
    $3::integer,
    $4::integer
)
ON CONFLICT (gateway_instance_id, fingerprint) DO NOTHING
RETURNING snapshot_id, gateway_instance_id, fingerprint, fingerprint_encoding_version, schema_version, account_count, created_at
`

type InsertGatewayDirectorySnapshotParams struct {
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	Fingerprint       []byte      `json:"fingerprint"`
	SchemaVersion     int32       `json:"schema_version"`
	AccountCount      int32       `json:"account_count"`
}

func (q *Queries) InsertGatewayDirectorySnapshot(ctx context.Context, arg InsertGatewayDirectorySnapshotParams) (GatewayDirectorySnapshot, error) {
	row := q.db.QueryRow(ctx, insertGatewayDirectorySnapshot,
		arg.GatewayInstanceID,
		arg.Fingerprint,
		arg.SchemaVersion,
		arg.AccountCount,
	)
	var i GatewayDirectorySnapshot
	err := row.Scan(
		&i.SnapshotID,
		&i.GatewayInstanceID,
		&i.Fingerprint,
		&i.FingerprintEncodingVersion,
		&i.SchemaVersion,
		&i.AccountCount,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredGatewayDirectoryIngestionRuns = `-- name: ListExpiredGatewayDirectoryIngestionRuns :many
SELECT ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count
FROM gateway_directory_ingestion_runs
WHERE status = 'running'
  AND lease_expires_at IS NOT NULL
  AND lease_expires_at <= clock_timestamp()
ORDER BY lease_expires_at, scheduled_at, gateway_instance_id
LIMIT $1::integer
`

func (q *Queries) ListExpiredGatewayDirectoryIngestionRuns(ctx context.Context, pageLimit int32) ([]GatewayDirectoryIngestionRun, error) {
	rows, err := q.db.Query(ctx, listExpiredGatewayDirectoryIngestionRuns, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayDirectoryIngestionRun{}
	for rows.Next() {
		var i GatewayDirectoryIngestionRun
		if err := rows.Scan(
			&i.IngestionRunID,
			&i.GatewayInstanceID,
			&i.ScheduledAt,
			&i.Status,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.FirstStartedAt,
			&i.LastStartedAt,
			&i.LeaseExpiresAt,
			&i.LeaseFencingToken,
			&i.TerminalAt,
			&i.Outcome,
			&i.LastFailureClass,
			&i.SourceGeneratedAt,
			&i.ReceivedAt,
			&i.ContentFingerprint,
			&i.SnapshotID,
			&i.AccountCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayDirectoryFailureClassMetrics = `-- name: ListGatewayDirectoryFailureClassMetrics :many
SELECT last_failure_class, count(*)::bigint AS count
FROM gateway_directory_ingestion_runs
WHERE last_failure_class IS NOT NULL
GROUP BY last_failure_class
ORDER BY last_failure_class
`

type ListGatewayDirectoryFailureClassMetricsRow struct {
	LastFailureClass pgtype.Text `json:"last_failure_class"`
	Count            int64       `json:"count"`
}

func (q *Queries) ListGatewayDirectoryFailureClassMetrics(ctx context.Context) ([]ListGatewayDirectoryFailureClassMetricsRow, error) {
	rows, err := q.db.Query(ctx, listGatewayDirectoryFailureClassMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayDirectoryFailureClassMetricsRow{}
	for rows.Next() {
		var i ListGatewayDirectoryFailureClassMetricsRow
		if err := rows.Scan(&i.LastFailureClass, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayDirectoryRunStatusMetrics = `-- name: ListGatewayDirectoryRunStatusMetrics :many
SELECT status, count(*)::bigint AS count
FROM gateway_directory_ingestion_runs
GROUP BY status
ORDER BY status
`

type ListGatewayDirectoryRunStatusMetricsRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) ListGatewayDirectoryRunStatusMetrics(ctx context.Context) ([]ListGatewayDirectoryRunStatusMetricsRow, error) {
	rows, err := q.db.Query(ctx, listGatewayDirectoryRunStatusMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayDirectoryRunStatusMetricsRow{}
	for rows.Next() {
		var i ListGatewayDirectoryRunStatusMetricsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayDirectorySnapshotItems = `-- name: ListGatewayDirectorySnapshotItems :many
SELECT snapshot_id, account_id, name, platform, type, url, status
FROM gateway_directory_snapshot_items
WHERE snapshot_id = $1::uuid
ORDER BY account_id ASC
`

func (q *Queries) ListGatewayDirectorySnapshotItems(ctx context.Context, snapshotID pgtype.UUID) ([]GatewayDirectorySnapshotItem, error) {
	rows, err := q.db.Query(ctx, listGatewayDirectorySnapshotItems, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayDirectorySnapshotItem{}
	for rows.Next() {
		var i GatewayDirectorySnapshotItem
		if err := rows.Scan(
			&i.SnapshotID,
			&i.AccountID,
			&i.Name,
			&i.Platform,
			&i.Type,
			&i.Url,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayInstanceIDs = `-- name: ListGatewayInstanceIDs :many
SELECT instance_id
FROM gateway_instances
ORDER BY instance_id
`

func (q *Queries) ListGatewayInstanceIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listGatewayInstanceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var instance_id pgtype.UUID
		if err := rows.Scan(&instance_id); err != nil {
			return nil, err
		}
		items = append(items, instance_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGatewayDirectoryInstance = `-- name: LockGatewayDirectoryInstance :one
SELECT instance_id
FROM gateway_instances
WHERE instance_id = $1::uuid
FOR UPDATE
`

func (q *Queries) LockGatewayDirectoryInstance(ctx context.Context, gatewayInstanceID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockGatewayDirectoryInstance, gatewayInstanceID)
	var instance_id pgtype.UUID
	err := row.Scan(&instance_id)
	return instance_id, err
}

const reconcileGatewayDirectoryIngestionRun = `-- name: ReconcileGatewayDirectoryIngestionRun :one
WITH db_now AS (
    SELECT clock_timestamp() AS db_now
), candidate AS (
    SELECT
        run.ingestion_run_id,
        run.status AS previous_status,
        run.last_failure_class
    FROM gateway_directory_ingestion_runs AS run, db_now
    WHERE (
        (run.status = 'running' AND run.lease_expires_at <= db_now.db_now)
        OR (run.status = 'pending' AND db_now.db_now >= run.scheduled_at + interval '120 seconds')
        OR (run.status = 'retry_wait' AND db_now.db_now >= run.scheduled_at + interval '120 seconds')
    )
    ORDER BY run.scheduled_at ASC, run.created_at ASC, run.gateway_instance_id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
), updated AS (
    UPDATE gateway_directory_ingestion_runs AS run
    SET status = CASE
        WHEN candidate.previous_status = 'running'
             AND run.attempt_count < 2
             AND db_now.db_now < run.scheduled_at + interval '120 seconds'
        THEN 'retry_wait'
        ELSE 'failed'
    END,
    terminal_at = CASE
        WHEN candidate.previous_status = 'running'
             AND run.attempt_count < 2
             AND db_now.db_now < run.scheduled_at + interval '120 seconds'
        THEN NULL
        ELSE db_now.db_now
    END,
    lease_expires_at = NULL,
    lease_fencing_token = NULL,
    last_failure_class = CASE
        WHEN candidate.previous_status = 'running' THEN 'lease_lost'
        WHEN candidate.previous_status = 'pending' THEN 'start_deadline_expired'
        ELSE candidate.last_failure_class
    END,
    outcome = NULL,
    source_generated_at = NULL,
    received_at = NULL,
    content_fingerprint = NULL,
    snapshot_id = NULL,
    account_count = NULL
    FROM candidate, db_now
    WHERE run.ingestion_run_id = candidate.ingestion_run_id
    RETURNING run.ingestion_run_id, candidate.previous_status, run.status, run.attempt_count, run.last_failure_class
)
SELECT ingestion_run_id, previous_status, status, attempt_count, last_failure_class FROM updated
`

type ReconcileGatewayDirectoryIngestionRunRow struct {
	IngestionRunID   pgtype.UUID `json:"ingestion_run_id"`
	PreviousStatus   string      `json:"previous_status"`
	Status           string      `json:"status"`
	AttemptCount     int16       `json:"attempt_count"`
	LastFailureClass pgtype.Text `json:"last_failure_class"`
}

func (q *Queries) ReconcileGatewayDirectoryIngestionRun(ctx context.Context) (ReconcileGatewayDirectoryIngestionRunRow, error) {
	row := q.db.QueryRow(ctx, reconcileGatewayDirectoryIngestionRun)
	var i ReconcileGatewayDirectoryIngestionRunRow
	err := row.Scan(
		&i.IngestionRunID,
		&i.PreviousStatus,
		&i.Status,
		&i.AttemptCount,
		&i.LastFailureClass,
	)
	return i, err
}

const recordGatewayDirectoryAttemptFailure = `-- name: RecordGatewayDirectoryAttemptFailure :one
WITH db_now AS (
    SELECT clock_timestamp() AS db_now
), updated AS (
    UPDATE gateway_directory_ingestion_runs AS run
    SET status = CASE
        WHEN $1::boolean
             AND run.attempt_count < 2
             AND db_now.db_now < run.scheduled_at + interval '120 seconds'
        THEN 'retry_wait'
        ELSE 'failed'
    END,
    lease_expires_at = NULL,
    lease_fencing_token = NULL,
    terminal_at = CASE
        WHEN $1::boolean
             AND run.attempt_count < 2
             AND db_now.db_now < run.scheduled_at + interval '120 seconds'
        THEN NULL
        ELSE db_now.db_now
    END,
    last_failure_class = $2::text
    FROM db_now
    WHERE run.ingestion_run_id = $3::uuid
      AND run.gateway_instance_id = $4::uuid
      AND run.status = 'running'
      AND run.lease_fencing_token = $5::uuid
      AND run.lease_expires_at > db_now.db_now
    RETURNING db_now, ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count
)
SELECT db_now, ingestion_run_id, gateway_instance_id, scheduled_at, status, attempt_count, created_at, first_started_at, last_started_at, lease_expires_at, lease_fencing_token, terminal_at, outcome, last_failure_class, source_generated_at, received_at, content_fingerprint, snapshot_id, account_count FROM updated
`

type RecordGatewayDirectoryAttemptFailureParams struct {
	Retryable         bool        `json:"retryable"`
	LastFailureClass  string      `json:"last_failure_class"`
	IngestionRunID    pgtype.UUID `json:"ingestion_run_id"`
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
}

type RecordGatewayDirectoryAttemptFailureRow struct {
	DbNow              interface{}        `json:"db_now"`
	IngestionRunID     pgtype.UUID        `json:"ingestion_run_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	Status             string             `json:"status"`
	AttemptCount       int16              `json:"attempt_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FirstStartedAt     pgtype.Timestamptz `json:"first_started_at"`
	LastStartedAt      pgtype.Timestamptz `json:"last_started_at"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	LeaseFencingToken  pgtype.UUID        `json:"lease_fencing_token"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
	Outcome            pgtype.Text        `json:"outcome"`
	LastFailureClass   pgtype.Text        `json:"last_failure_class"`
	SourceGeneratedAt  pgtype.Timestamptz `json:"source_generated_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ContentFingerprint []byte             `json:"content_fingerprint"`
	SnapshotID         pgtype.UUID        `json:"snapshot_id"`
	AccountCount       pgtype.Int4        `json:"account_count"`
}

func (q *Queries) RecordGatewayDirectoryAttemptFailure(ctx context.Context, arg RecordGatewayDirectoryAttemptFailureParams) (RecordGatewayDirectoryAttemptFailureRow, error) {
	row := q.db.QueryRow(ctx, recordGatewayDirectoryAttemptFailure,
		arg.Retryable,
		arg.LastFailureClass,
		arg.IngestionRunID,
		arg.GatewayInstanceID,
		arg.LeaseFencingToken,
	)
	var i RecordGatewayDirectoryAttemptFailureRow
	err := row.Scan(
		&i.DbNow,
		&i.IngestionRunID,
		&i.GatewayInstanceID,
		&i.ScheduledAt,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.LastStartedAt,
		&i.LeaseExpiresAt,
		&i.LeaseFencingToken,
		&i.TerminalAt,
		&i.Outcome,
		&i.LastFailureClass,
		&i.SourceGeneratedAt,
		&i.ReceivedAt,
		&i.ContentFingerprint,
		&i.SnapshotID,
		&i.AccountCount,
	)
	return i, err
}

const upsertGatewayDirectoryCurrentState = `-- name: UpsertGatewayDirectoryCurrentState :one
INSERT INTO gateway_directory_current_state (
    gateway_instance_id,
    current_snapshot_id,
    current_content_fingerprint,
    last_success_received_at,
    last_source_generated_at,
    last_success_run_id,
    updated_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::bytea,
    $4::timestamptz,
    $5::timestamptz,
    $6::uuid,
    $7::timestamptz
)
ON CONFLICT (gateway_instance_id) DO UPDATE SET
    current_snapshot_id = EXCLUDED.current_snapshot_id,
    current_content_fingerprint = EXCLUDED.current_content_fingerprint,
    last_success_received_at = EXCLUDED.last_success_received_at,
    last_source_generated_at = EXCLUDED.last_source_generated_at,
    last_success_run_id = EXCLUDED.last_success_run_id,
    updated_at = EXCLUDED.updated_at
RETURNING gateway_instance_id, current_snapshot_id, current_content_fingerprint, last_success_received_at, last_source_generated_at, last_success_run_id, updated_at
`

type UpsertGatewayDirectoryCurrentStateParams struct {
	GatewayInstanceID         pgtype.UUID        `json:"gateway_instance_id"`
	CurrentSnapshotID         pgtype.UUID        `json:"current_snapshot_id"`
	CurrentContentFingerprint []byte             `json:"current_content_fingerprint"`
	LastSuccessReceivedAt     pgtype.Timestamptz `json:"last_success_received_at"`
	LastSourceGeneratedAt     pgtype.Timestamptz `json:"last_source_generated_at"`
	LastSuccessRunID          pgtype.UUID        `json:"last_success_run_id"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertGatewayDirectoryCurrentState(ctx context.Context, arg UpsertGatewayDirectoryCurrentStateParams) (GatewayDirectoryCurrentState, error) {
	row := q.db.QueryRow(ctx, upsertGatewayDirectoryCurrentState,
		arg.GatewayInstanceID,
		arg.CurrentSnapshotID,
		arg.CurrentContentFingerprint,
		arg.LastSuccessReceivedAt,
		arg.LastSourceGeneratedAt,
		arg.LastSuccessRunID,
		arg.UpdatedAt,
	)
	var i GatewayDirectoryCurrentState
	err := row.Scan(
		&i.GatewayInstanceID,
		&i.CurrentSnapshotID,
		&i.CurrentContentFingerprint,
		&i.LastSuccessReceivedAt,
		&i.LastSourceGeneratedAt,
		&i.LastSuccessRunID,
		&i.UpdatedAt,
	)
	return i, err
}
