// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_asset_foundation.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssetAdminCommandReceipt = `-- name: GetAssetAdminCommandReceipt :one
SELECT
    command_id,
    command_kind,
    intent_encoding_version,
    canonical_intent_hash,
    sanitized_result,
    response_status,
    actor_admin_id,
    committed_at,
    secret_fingerprint_key_version
FROM asset_admin_command_receipts
WHERE command_id = $1::uuid
`

func (q *Queries) GetAssetAdminCommandReceipt(ctx context.Context, commandID pgtype.UUID) (AssetAdminCommandReceipt, error) {
	row := q.db.QueryRow(ctx, getAssetAdminCommandReceipt, commandID)
	var i AssetAdminCommandReceipt
	err := row.Scan(
		&i.CommandID,
		&i.CommandKind,
		&i.IntentEncodingVersion,
		&i.CanonicalIntentHash,
		&i.SanitizedResult,
		&i.ResponseStatus,
		&i.ActorAdminID,
		&i.CommittedAt,
		&i.SecretFingerprintKeyVersion,
	)
	return i, err
}

const getGatewayAssetByInstanceID = `-- name: GetGatewayAssetByInstanceID :one
SELECT
    instance_id,
    singleton_id,
    lifecycle_status,
    display_name,
    management_endpoint,
    COALESCE(reader_secret_configured, false)::boolean AS secret_configured,
    created_at,
    updated_at,
    revision,
    retired_at,
    retired_by,
    retire_reason
FROM gateway_instances
WHERE instance_id = $1::uuid
`

type GetGatewayAssetByInstanceIDRow struct {
	InstanceID         pgtype.UUID        `json:"instance_id"`
	SingletonID        pgtype.Int2        `json:"singleton_id"`
	LifecycleStatus    string             `json:"lifecycle_status"`
	DisplayName        string             `json:"display_name"`
	ManagementEndpoint string             `json:"management_endpoint"`
	SecretConfigured   bool               `json:"secret_configured"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Revision           int64              `json:"revision"`
	RetiredAt          pgtype.Timestamptz `json:"retired_at"`
	RetiredBy          pgtype.UUID        `json:"retired_by"`
	RetireReason       pgtype.Text        `json:"retire_reason"`
}

func (q *Queries) GetGatewayAssetByInstanceID(ctx context.Context, instanceID pgtype.UUID) (GetGatewayAssetByInstanceIDRow, error) {
	row := q.db.QueryRow(ctx, getGatewayAssetByInstanceID, instanceID)
	var i GetGatewayAssetByInstanceIDRow
	err := row.Scan(
		&i.InstanceID,
		&i.SingletonID,
		&i.LifecycleStatus,
		&i.DisplayName,
		&i.ManagementEndpoint,
		&i.SecretConfigured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.RetiredAt,
		&i.RetiredBy,
		&i.RetireReason,
	)
	return i, err
}

const getGatewayReplacementByNewInstanceID = `-- name: GetGatewayReplacementByNewInstanceID :one
SELECT
    replacement_id,
    old_instance_id,
    new_instance_id,
    replaced_at,
    replaced_by,
    command_id
FROM gateway_asset_replacements
WHERE new_instance_id = $1::uuid
`

func (q *Queries) GetGatewayReplacementByNewInstanceID(ctx context.Context, newInstanceID pgtype.UUID) (GatewayAssetReplacement, error) {
	row := q.db.QueryRow(ctx, getGatewayReplacementByNewInstanceID, newInstanceID)
	var i GatewayAssetReplacement
	err := row.Scan(
		&i.ReplacementID,
		&i.OldInstanceID,
		&i.NewInstanceID,
		&i.ReplacedAt,
		&i.ReplacedBy,
		&i.CommandID,
	)
	return i, err
}

const getGatewayReplacementByOldInstanceID = `-- name: GetGatewayReplacementByOldInstanceID :one
SELECT
    replacement_id,
    old_instance_id,
    new_instance_id,
    replaced_at,
    replaced_by,
    command_id
FROM gateway_asset_replacements
WHERE old_instance_id = $1::uuid
`

func (q *Queries) GetGatewayReplacementByOldInstanceID(ctx context.Context, oldInstanceID pgtype.UUID) (GatewayAssetReplacement, error) {
	row := q.db.QueryRow(ctx, getGatewayReplacementByOldInstanceID, oldInstanceID)
	var i GatewayAssetReplacement
	err := row.Scan(
		&i.ReplacementID,
		&i.OldInstanceID,
		&i.NewInstanceID,
		&i.ReplacedAt,
		&i.ReplacedBy,
		&i.CommandID,
	)
	return i, err
}

const getRuntimeCompatibilityMarker = `-- name: GetRuntimeCompatibilityMarker :one
SELECT singleton_id, schema_version, phase6_evidence_floor, updated_at
FROM control_runtime_compatibility
WHERE singleton_id = 1
`

func (q *Queries) GetRuntimeCompatibilityMarker(ctx context.Context) (ControlRuntimeCompatibility, error) {
	row := q.db.QueryRow(ctx, getRuntimeCompatibilityMarker)
	var i ControlRuntimeCompatibility
	err := row.Scan(
		&i.SingletonID,
		&i.SchemaVersion,
		&i.Phase6EvidenceFloor,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssetAdminCommandReceipt = `-- name: InsertAssetAdminCommandReceipt :one
INSERT INTO asset_admin_command_receipts (
    command_id,
    command_kind,
    intent_encoding_version,
    canonical_intent_hash,
    sanitized_result,
    response_status,
    actor_admin_id,
    committed_at,
    secret_fingerprint_key_version
) VALUES (
    $1::uuid,
    $2::text,
    $3::smallint,
    $4::bytea,
    $5::jsonb,
    $6::smallint,
    $7::uuid,
    $8::timestamptz,
    $9::smallint
)
RETURNING
    command_id,
    command_kind,
    intent_encoding_version,
    canonical_intent_hash,
    sanitized_result,
    response_status,
    actor_admin_id,
    committed_at,
    secret_fingerprint_key_version
`

type InsertAssetAdminCommandReceiptParams struct {
	CommandID                   pgtype.UUID        `json:"command_id"`
	CommandKind                 string             `json:"command_kind"`
	IntentEncodingVersion       int16              `json:"intent_encoding_version"`
	CanonicalIntentHash         []byte             `json:"canonical_intent_hash"`
	SanitizedResult             []byte             `json:"sanitized_result"`
	ResponseStatus              int16              `json:"response_status"`
	ActorAdminID                pgtype.UUID        `json:"actor_admin_id"`
	CommittedAt                 pgtype.Timestamptz `json:"committed_at"`
	SecretFingerprintKeyVersion pgtype.Int2        `json:"secret_fingerprint_key_version"`
}

func (q *Queries) InsertAssetAdminCommandReceipt(ctx context.Context, arg InsertAssetAdminCommandReceiptParams) (AssetAdminCommandReceipt, error) {
	row := q.db.QueryRow(ctx, insertAssetAdminCommandReceipt,
		arg.CommandID,
		arg.CommandKind,
		arg.IntentEncodingVersion,
		arg.CanonicalIntentHash,
		arg.SanitizedResult,
		arg.ResponseStatus,
		arg.ActorAdminID,
		arg.CommittedAt,
		arg.SecretFingerprintKeyVersion,
	)
	var i AssetAdminCommandReceipt
	err := row.Scan(
		&i.CommandID,
		&i.CommandKind,
		&i.IntentEncodingVersion,
		&i.CanonicalIntentHash,
		&i.SanitizedResult,
		&i.ResponseStatus,
		&i.ActorAdminID,
		&i.CommittedAt,
		&i.SecretFingerprintKeyVersion,
	)
	return i, err
}

const lockGatewayAssetForUpdate = `-- name: LockGatewayAssetForUpdate :one
SELECT
    instance_id,
    singleton_id,
    lifecycle_status,
    display_name,
    management_endpoint,
    COALESCE(reader_secret_configured, false)::boolean AS secret_configured,
    created_at,
    updated_at,
    revision,
    retired_at,
    retired_by,
    retire_reason
FROM gateway_instances
WHERE instance_id = $1::uuid
FOR UPDATE
`

type LockGatewayAssetForUpdateRow struct {
	InstanceID         pgtype.UUID        `json:"instance_id"`
	SingletonID        pgtype.Int2        `json:"singleton_id"`
	LifecycleStatus    string             `json:"lifecycle_status"`
	DisplayName        string             `json:"display_name"`
	ManagementEndpoint string             `json:"management_endpoint"`
	SecretConfigured   bool               `json:"secret_configured"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Revision           int64              `json:"revision"`
	RetiredAt          pgtype.Timestamptz `json:"retired_at"`
	RetiredBy          pgtype.UUID        `json:"retired_by"`
	RetireReason       pgtype.Text        `json:"retire_reason"`
}

func (q *Queries) LockGatewayAssetForUpdate(ctx context.Context, instanceID pgtype.UUID) (LockGatewayAssetForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockGatewayAssetForUpdate, instanceID)
	var i LockGatewayAssetForUpdateRow
	err := row.Scan(
		&i.InstanceID,
		&i.SingletonID,
		&i.LifecycleStatus,
		&i.DisplayName,
		&i.ManagementEndpoint,
		&i.SecretConfigured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.RetiredAt,
		&i.RetiredBy,
		&i.RetireReason,
	)
	return i, err
}
