// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimExpiredAsyncJob = `-- name: ClaimExpiredAsyncJob :one
SELECT
    claimed.job_id, claimed.idempotency_key, claimed.job_kind, claimed.payload_schema_version, claimed.operation_id, claimed.payload, claimed.payload_hash, claimed.status, claimed.priority, claimed.attempt_count, claimed.verification_attempt, claimed.max_attempts, claimed.max_verification_attempts, claimed.timeout_seconds, claimed.lease_seconds, claimed.heartbeat_interval_seconds, claimed.replay_safe, claimed.rollback_allowed, claimed.available_at, claimed.deadline_at, claimed.started_at, claimed.completed_at, claimed.cancel_requested_at, claimed.error_code, claimed.error_summary, claimed.lease_owner, claimed.lease_fencing_token, claimed.lease_expires_at, claimed.created_at, claimed.updated_at,
    (claimed.deadline_at <= clock_timestamp())::boolean AS deadline_exceeded
FROM public.control_claim_expired_async_job(
    $1::text,
    $2::uuid
) AS claimed
`

type ClaimExpiredAsyncJobParams struct {
	LeaseOwner        string      `json:"lease_owner"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
}

type ClaimExpiredAsyncJobRow struct {
	JobID                    pgtype.UUID        `json:"job_id"`
	IdempotencyKey           string             `json:"idempotency_key"`
	JobKind                  string             `json:"job_kind"`
	PayloadSchemaVersion     int32              `json:"payload_schema_version"`
	OperationID              pgtype.UUID        `json:"operation_id"`
	Payload                  []byte             `json:"payload"`
	PayloadHash              []byte             `json:"payload_hash"`
	Status                   string             `json:"status"`
	Priority                 int16              `json:"priority"`
	AttemptCount             int32              `json:"attempt_count"`
	VerificationAttempt      int32              `json:"verification_attempt"`
	MaxAttempts              int32              `json:"max_attempts"`
	MaxVerificationAttempts  int32              `json:"max_verification_attempts"`
	TimeoutSeconds           int32              `json:"timeout_seconds"`
	LeaseSeconds             int32              `json:"lease_seconds"`
	HeartbeatIntervalSeconds int32              `json:"heartbeat_interval_seconds"`
	ReplaySafe               bool               `json:"replay_safe"`
	RollbackAllowed          bool               `json:"rollback_allowed"`
	AvailableAt              pgtype.Timestamptz `json:"available_at"`
	DeadlineAt               pgtype.Timestamptz `json:"deadline_at"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelRequestedAt        pgtype.Timestamptz `json:"cancel_requested_at"`
	ErrorCode                pgtype.Text        `json:"error_code"`
	ErrorSummary             pgtype.Text        `json:"error_summary"`
	LeaseOwner               pgtype.Text        `json:"lease_owner"`
	LeaseFencingToken        pgtype.UUID        `json:"lease_fencing_token"`
	LeaseExpiresAt           pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeadlineExceeded         bool               `json:"deadline_exceeded"`
}

func (q *Queries) ClaimExpiredAsyncJob(ctx context.Context, arg ClaimExpiredAsyncJobParams) (ClaimExpiredAsyncJobRow, error) {
	row := q.db.QueryRow(ctx, claimExpiredAsyncJob, arg.LeaseOwner, arg.LeaseFencingToken)
	var i ClaimExpiredAsyncJobRow
	err := row.Scan(
		&i.JobID,
		&i.IdempotencyKey,
		&i.JobKind,
		&i.PayloadSchemaVersion,
		&i.OperationID,
		&i.Payload,
		&i.PayloadHash,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.VerificationAttempt,
		&i.MaxAttempts,
		&i.MaxVerificationAttempts,
		&i.TimeoutSeconds,
		&i.LeaseSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.ReplaySafe,
		&i.RollbackAllowed,
		&i.AvailableAt,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeadlineExceeded,
	)
	return i, err
}

const claimOutboxEvent = `-- name: ClaimOutboxEvent :one
SELECT event_id, event_key, job_id, operation_id, topic, envelope, status, attempt_count, max_attempts, available_at, sent_at, error_code, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_claim_outbox_event(
    $1::text,
    $2::uuid,
    $3::integer
)
`

type ClaimOutboxEventParams struct {
	LeaseOwner        string      `json:"lease_owner"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
	LeaseSeconds      int32       `json:"lease_seconds"`
}

func (q *Queries) ClaimOutboxEvent(ctx context.Context, arg ClaimOutboxEventParams) (OperationOutbox, error) {
	row := q.db.QueryRow(ctx, claimOutboxEvent, arg.LeaseOwner, arg.LeaseFencingToken, arg.LeaseSeconds)
	var i OperationOutbox
	err := row.Scan(
		&i.EventID,
		&i.EventKey,
		&i.JobID,
		&i.OperationID,
		&i.Topic,
		&i.Envelope,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.SentAt,
		&i.ErrorCode,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimRunnableAsyncJob = `-- name: ClaimRunnableAsyncJob :one
SELECT job_id, idempotency_key, job_kind, payload_schema_version, operation_id, payload, payload_hash, status, priority, attempt_count, verification_attempt, max_attempts, max_verification_attempts, timeout_seconds, lease_seconds, heartbeat_interval_seconds, replay_safe, rollback_allowed, available_at, deadline_at, started_at, completed_at, cancel_requested_at, error_code, error_summary, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_claim_async_job(
    $1::text,
    $2::uuid
)
`

type ClaimRunnableAsyncJobParams struct {
	LeaseOwner        string      `json:"lease_owner"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
}

func (q *Queries) ClaimRunnableAsyncJob(ctx context.Context, arg ClaimRunnableAsyncJobParams) (AsyncJob, error) {
	row := q.db.QueryRow(ctx, claimRunnableAsyncJob, arg.LeaseOwner, arg.LeaseFencingToken)
	var i AsyncJob
	err := row.Scan(
		&i.JobID,
		&i.IdempotencyKey,
		&i.JobKind,
		&i.PayloadSchemaVersion,
		&i.OperationID,
		&i.Payload,
		&i.PayloadHash,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.VerificationAttempt,
		&i.MaxAttempts,
		&i.MaxVerificationAttempts,
		&i.TimeoutSeconds,
		&i.LeaseSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.ReplaySafe,
		&i.RollbackAllowed,
		&i.AvailableAt,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueAsyncJob = `-- name: EnqueueAsyncJob :one
SELECT job_id, idempotency_key, job_kind, payload_schema_version, operation_id, payload, payload_hash, status, priority, attempt_count, verification_attempt, max_attempts, max_verification_attempts, timeout_seconds, lease_seconds, heartbeat_interval_seconds, replay_safe, rollback_allowed, available_at, deadline_at, started_at, completed_at, cancel_requested_at, error_code, error_summary, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_enqueue_async_job(
    $1::uuid,
    $2::text,
    $3::text,
    $4::integer,
    $5::uuid,
    $6::jsonb,
    $7::bytea,
    $8::smallint,
    $9::uuid,
    $10::text,
    $11::boolean
)
`

type EnqueueAsyncJobParams struct {
	JobID                pgtype.UUID `json:"job_id"`
	IdempotencyKey       string      `json:"idempotency_key"`
	JobKind              string      `json:"job_kind"`
	PayloadSchemaVersion int32       `json:"payload_schema_version"`
	OperationID          pgtype.UUID `json:"operation_id"`
	Payload              []byte      `json:"payload"`
	PayloadHash          []byte      `json:"payload_hash"`
	Priority             int16       `json:"priority"`
	OutboxEventID        pgtype.UUID `json:"outbox_event_id"`
	OutboxEventKey       string      `json:"outbox_event_key"`
	PublisherEnabled     bool        `json:"publisher_enabled"`
}

func (q *Queries) EnqueueAsyncJob(ctx context.Context, arg EnqueueAsyncJobParams) (AsyncJob, error) {
	row := q.db.QueryRow(ctx, enqueueAsyncJob,
		arg.JobID,
		arg.IdempotencyKey,
		arg.JobKind,
		arg.PayloadSchemaVersion,
		arg.OperationID,
		arg.Payload,
		arg.PayloadHash,
		arg.Priority,
		arg.OutboxEventID,
		arg.OutboxEventKey,
		arg.PublisherEnabled,
	)
	var i AsyncJob
	err := row.Scan(
		&i.JobID,
		&i.IdempotencyKey,
		&i.JobKind,
		&i.PayloadSchemaVersion,
		&i.OperationID,
		&i.Payload,
		&i.PayloadHash,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.VerificationAttempt,
		&i.MaxAttempts,
		&i.MaxVerificationAttempts,
		&i.TimeoutSeconds,
		&i.LeaseSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.ReplaySafe,
		&i.RollbackAllowed,
		&i.AvailableAt,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsyncJobByIdempotencyKey = `-- name: GetAsyncJobByIdempotencyKey :one
SELECT job_id, idempotency_key, job_kind, payload_schema_version, operation_id, payload, payload_hash, status, priority, attempt_count, verification_attempt, max_attempts, max_verification_attempts, timeout_seconds, lease_seconds, heartbeat_interval_seconds, replay_safe, rollback_allowed, available_at, deadline_at, started_at, completed_at, cancel_requested_at, error_code, error_summary, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_get_async_job_by_idempotency_key($1)
`

func (q *Queries) GetAsyncJobByIdempotencyKey(ctx context.Context, lookupKey string) (AsyncJob, error) {
	row := q.db.QueryRow(ctx, getAsyncJobByIdempotencyKey, lookupKey)
	var i AsyncJob
	err := row.Scan(
		&i.JobID,
		&i.IdempotencyKey,
		&i.JobKind,
		&i.PayloadSchemaVersion,
		&i.OperationID,
		&i.Payload,
		&i.PayloadHash,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.VerificationAttempt,
		&i.MaxAttempts,
		&i.MaxVerificationAttempts,
		&i.TimeoutSeconds,
		&i.LeaseSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.ReplaySafe,
		&i.RollbackAllowed,
		&i.AvailableAt,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsyncJobMetrics = `-- name: GetAsyncJobMetrics :one
SELECT
    count(*) FILTER (WHERE status = 'pending')::bigint AS pending,
    count(*) FILTER (WHERE status = 'running')::bigint AS running,
    count(*) FILTER (WHERE status = 'verifying')::bigint AS verifying,
    count(*) FILTER (WHERE status = 'retry_wait')::bigint AS retry_wait,
    count(*) FILTER (WHERE status = 'rolling_back')::bigint AS rolling_back,
    count(*) FILTER (WHERE status = 'succeeded')::bigint AS succeeded,
    count(*) FILTER (WHERE status = 'failed')::bigint AS failed,
    count(*) FILTER (WHERE status = 'rolled_back')::bigint AS rolled_back,
    count(*) FILTER (WHERE status = 'cancelled')::bigint AS cancelled,
    COALESCE(extract(epoch FROM (
        clock_timestamp() - (min(created_at) FILTER (
            WHERE status IN ('pending', 'retry_wait') AND available_at <= clock_timestamp()
        ))
    )), 0)::double precision
        AS oldest_pending_seconds,
    count(*) FILTER (WHERE status IN ('running', 'verifying', 'rolling_back')
        AND lease_expires_at <= clock_timestamp())::bigint AS expired_leases
FROM async_jobs
`

type GetAsyncJobMetricsRow struct {
	Pending              int64   `json:"pending"`
	Running              int64   `json:"running"`
	Verifying            int64   `json:"verifying"`
	RetryWait            int64   `json:"retry_wait"`
	RollingBack          int64   `json:"rolling_back"`
	Succeeded            int64   `json:"succeeded"`
	Failed               int64   `json:"failed"`
	RolledBack           int64   `json:"rolled_back"`
	Cancelled            int64   `json:"cancelled"`
	OldestPendingSeconds float64 `json:"oldest_pending_seconds"`
	ExpiredLeases        int64   `json:"expired_leases"`
}

func (q *Queries) GetAsyncJobMetrics(ctx context.Context) (GetAsyncJobMetricsRow, error) {
	row := q.db.QueryRow(ctx, getAsyncJobMetrics)
	var i GetAsyncJobMetricsRow
	err := row.Scan(
		&i.Pending,
		&i.Running,
		&i.Verifying,
		&i.RetryWait,
		&i.RollingBack,
		&i.Succeeded,
		&i.Failed,
		&i.RolledBack,
		&i.Cancelled,
		&i.OldestPendingSeconds,
		&i.ExpiredLeases,
	)
	return i, err
}

const getAsyncJobPublic = `-- name: GetAsyncJobPublic :one
SELECT
    job.job_id,
    job.operation_id,
    job.job_kind,
    job.status,
    job.attempt_count,
    job.max_attempts,
    job.available_at,
    job.started_at,
    job.completed_at,
    (job.cancel_requested_at IS NOT NULL)::boolean AS cancel_requested,
    job.error_code,
    COALESCE(outbox.status, 'none')::text AS outbox_status,
    job.created_at,
    job.updated_at
FROM async_jobs AS job
LEFT JOIN LATERAL (
    SELECT event.status
    FROM operation_outbox AS event
    WHERE event.job_id = job.job_id
    ORDER BY event.created_at DESC, event.event_id DESC
    LIMIT 1
) AS outbox ON true
WHERE job.job_id = $1
`

type GetAsyncJobPublicRow struct {
	JobID           pgtype.UUID        `json:"job_id"`
	OperationID     pgtype.UUID        `json:"operation_id"`
	JobKind         string             `json:"job_kind"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	MaxAttempts     int32              `json:"max_attempts"`
	AvailableAt     pgtype.Timestamptz `json:"available_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CancelRequested bool               `json:"cancel_requested"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	OutboxStatus    string             `json:"outbox_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAsyncJobPublic(ctx context.Context, jobID pgtype.UUID) (GetAsyncJobPublicRow, error) {
	row := q.db.QueryRow(ctx, getAsyncJobPublic, jobID)
	var i GetAsyncJobPublicRow
	err := row.Scan(
		&i.JobID,
		&i.OperationID,
		&i.JobKind,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequested,
		&i.ErrorCode,
		&i.OutboxStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboxOldestPendingSeconds = `-- name: GetOutboxOldestPendingSeconds :one
SELECT COALESCE(
    extract(epoch FROM (
        clock_timestamp() - (min(created_at) FILTER (
            WHERE status IN ('pending', 'retry_wait') AND available_at <= clock_timestamp()
        ))
    )),
    0
)::double precision AS oldest_pending_seconds
FROM operation_outbox
`

func (q *Queries) GetOutboxOldestPendingSeconds(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, getOutboxOldestPendingSeconds)
	var oldest_pending_seconds float64
	err := row.Scan(&oldest_pending_seconds)
	return oldest_pending_seconds, err
}

const listActiveAsyncJobKinds = `-- name: ListActiveAsyncJobKinds :many
SELECT
    job_kind,
    payload_schema_version,
    default_timeout_seconds,
    lease_seconds,
    heartbeat_interval_seconds,
    default_max_attempts,
    default_max_verification_attempts,
    replay_safe,
    rollback_allowed
FROM async_job_kinds
WHERE lifecycle_status = 'active'
ORDER BY job_kind
`

type ListActiveAsyncJobKindsRow struct {
	JobKind                        string `json:"job_kind"`
	PayloadSchemaVersion           int32  `json:"payload_schema_version"`
	DefaultTimeoutSeconds          int32  `json:"default_timeout_seconds"`
	LeaseSeconds                   int32  `json:"lease_seconds"`
	HeartbeatIntervalSeconds       int32  `json:"heartbeat_interval_seconds"`
	DefaultMaxAttempts             int32  `json:"default_max_attempts"`
	DefaultMaxVerificationAttempts int32  `json:"default_max_verification_attempts"`
	ReplaySafe                     bool   `json:"replay_safe"`
	RollbackAllowed                bool   `json:"rollback_allowed"`
}

func (q *Queries) ListActiveAsyncJobKinds(ctx context.Context) ([]ListActiveAsyncJobKindsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAsyncJobKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAsyncJobKindsRow{}
	for rows.Next() {
		var i ListActiveAsyncJobKindsRow
		if err := rows.Scan(
			&i.JobKind,
			&i.PayloadSchemaVersion,
			&i.DefaultTimeoutSeconds,
			&i.LeaseSeconds,
			&i.HeartbeatIntervalSeconds,
			&i.DefaultMaxAttempts,
			&i.DefaultMaxVerificationAttempts,
			&i.ReplaySafe,
			&i.RollbackAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAsyncJobEventsPublic = `-- name: ListAsyncJobEventsPublic :many
SELECT
    sequence,
    event_type,
    from_status,
    to_status,
    attempt,
    reason_code,
    error_code,
    actor_type,
    occurred_at
FROM async_job_events
WHERE job_id = $1
ORDER BY sequence
`

type ListAsyncJobEventsPublicRow struct {
	Sequence   int64              `json:"sequence"`
	EventType  string             `json:"event_type"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Attempt    int32              `json:"attempt"`
	ReasonCode pgtype.Text        `json:"reason_code"`
	ErrorCode  pgtype.Text        `json:"error_code"`
	ActorType  string             `json:"actor_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListAsyncJobEventsPublic(ctx context.Context, jobID pgtype.UUID) ([]ListAsyncJobEventsPublicRow, error) {
	rows, err := q.db.Query(ctx, listAsyncJobEventsPublic, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAsyncJobEventsPublicRow{}
	for rows.Next() {
		var i ListAsyncJobEventsPublicRow
		if err := rows.Scan(
			&i.Sequence,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.Attempt,
			&i.ReasonCode,
			&i.ErrorCode,
			&i.ActorType,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAsyncJobsPublic = `-- name: ListAsyncJobsPublic :many
SELECT
    job.job_id,
    job.operation_id,
    job.job_kind,
    job.status,
    job.attempt_count,
    job.max_attempts,
    job.available_at,
    job.started_at,
    job.completed_at,
    (job.cancel_requested_at IS NOT NULL)::boolean AS cancel_requested,
    job.error_code,
    COALESCE(outbox.status, 'none')::text AS outbox_status,
    job.created_at,
    job.updated_at
FROM async_jobs AS job
LEFT JOIN LATERAL (
    SELECT event.status
    FROM operation_outbox AS event
    WHERE event.job_id = job.job_id
    ORDER BY event.created_at DESC, event.event_id DESC
    LIMIT 1
) AS outbox ON true
WHERE ($1::text IS NULL OR job.job_kind = $1)
  AND ($2::text IS NULL OR job.status = $2)
  AND ($3::timestamptz IS NULL OR job.created_at >= $3)
  AND ($4::timestamptz IS NULL OR job.created_at < $4)
  AND (
      $5::timestamptz IS NULL
      OR (job.created_at, job.job_id) < (
          $5::timestamptz,
          $6::uuid
      )
  )
ORDER BY job.created_at DESC, job.job_id DESC
LIMIT $7
`

type ListAsyncJobsPublicParams struct {
	JobKind        pgtype.Text        `json:"job_kind"`
	Status         pgtype.Text        `json:"status"`
	CreatedFrom    pgtype.Timestamptz `json:"created_from"`
	CreatedTo      pgtype.Timestamptz `json:"created_to"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterJobID     pgtype.UUID        `json:"after_job_id"`
	PageSize       int32              `json:"page_size"`
}

type ListAsyncJobsPublicRow struct {
	JobID           pgtype.UUID        `json:"job_id"`
	OperationID     pgtype.UUID        `json:"operation_id"`
	JobKind         string             `json:"job_kind"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	MaxAttempts     int32              `json:"max_attempts"`
	AvailableAt     pgtype.Timestamptz `json:"available_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CancelRequested bool               `json:"cancel_requested"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	OutboxStatus    string             `json:"outbox_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAsyncJobsPublic(ctx context.Context, arg ListAsyncJobsPublicParams) ([]ListAsyncJobsPublicRow, error) {
	rows, err := q.db.Query(ctx, listAsyncJobsPublic,
		arg.JobKind,
		arg.Status,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.AfterCreatedAt,
		arg.AfterJobID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAsyncJobsPublicRow{}
	for rows.Next() {
		var i ListAsyncJobsPublicRow
		if err := rows.Scan(
			&i.JobID,
			&i.OperationID,
			&i.JobKind,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CancelRequested,
			&i.ErrorCode,
			&i.OutboxStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAsyncJob = `-- name: LockAsyncJob :one
SELECT job_id, idempotency_key, job_kind, payload_schema_version, operation_id, payload, payload_hash, status, priority, attempt_count, verification_attempt, max_attempts, max_verification_attempts, timeout_seconds, lease_seconds, heartbeat_interval_seconds, replay_safe, rollback_allowed, available_at, deadline_at, started_at, completed_at, cancel_requested_at, error_code, error_summary, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_lock_async_job($1::uuid)
`

func (q *Queries) LockAsyncJob(ctx context.Context, jobID pgtype.UUID) (AsyncJob, error) {
	row := q.db.QueryRow(ctx, lockAsyncJob, jobID)
	var i AsyncJob
	err := row.Scan(
		&i.JobID,
		&i.IdempotencyKey,
		&i.JobKind,
		&i.PayloadSchemaVersion,
		&i.OperationID,
		&i.Payload,
		&i.PayloadHash,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.VerificationAttempt,
		&i.MaxAttempts,
		&i.MaxVerificationAttempts,
		&i.TimeoutSeconds,
		&i.LeaseSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.ReplaySafe,
		&i.RollbackAllowed,
		&i.AvailableAt,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewAsyncJobLease = `-- name: RenewAsyncJobLease :one
SELECT job_id, idempotency_key, job_kind, payload_schema_version, operation_id, payload, payload_hash, status, priority, attempt_count, verification_attempt, max_attempts, max_verification_attempts, timeout_seconds, lease_seconds, heartbeat_interval_seconds, replay_safe, rollback_allowed, available_at, deadline_at, started_at, completed_at, cancel_requested_at, error_code, error_summary, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_renew_async_job_lease(
    $1::uuid,
    $2::uuid,
    $3::integer
)
`

type RenewAsyncJobLeaseParams struct {
	JobID             pgtype.UUID `json:"job_id"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
	LeaseSeconds      int32       `json:"lease_seconds"`
}

func (q *Queries) RenewAsyncJobLease(ctx context.Context, arg RenewAsyncJobLeaseParams) (AsyncJob, error) {
	row := q.db.QueryRow(ctx, renewAsyncJobLease, arg.JobID, arg.LeaseFencingToken, arg.LeaseSeconds)
	var i AsyncJob
	err := row.Scan(
		&i.JobID,
		&i.IdempotencyKey,
		&i.JobKind,
		&i.PayloadSchemaVersion,
		&i.OperationID,
		&i.Payload,
		&i.PayloadHash,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.VerificationAttempt,
		&i.MaxAttempts,
		&i.MaxVerificationAttempts,
		&i.TimeoutSeconds,
		&i.LeaseSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.ReplaySafe,
		&i.RollbackAllowed,
		&i.AvailableAt,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewOutboxEventLease = `-- name: RenewOutboxEventLease :one
SELECT event_id, event_key, job_id, operation_id, topic, envelope, status, attempt_count, max_attempts, available_at, sent_at, error_code, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_renew_outbox_lease(
    $1::uuid,
    $2::uuid,
    $3::integer
)
`

type RenewOutboxEventLeaseParams struct {
	EventID           pgtype.UUID `json:"event_id"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
	LeaseSeconds      int32       `json:"lease_seconds"`
}

func (q *Queries) RenewOutboxEventLease(ctx context.Context, arg RenewOutboxEventLeaseParams) (OperationOutbox, error) {
	row := q.db.QueryRow(ctx, renewOutboxEventLease, arg.EventID, arg.LeaseFencingToken, arg.LeaseSeconds)
	var i OperationOutbox
	err := row.Scan(
		&i.EventID,
		&i.EventKey,
		&i.JobID,
		&i.OperationID,
		&i.Topic,
		&i.Envelope,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.SentAt,
		&i.ErrorCode,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestAsyncJobCancel = `-- name: RequestAsyncJobCancel :one
SELECT job_id, idempotency_key, job_kind, payload_schema_version, operation_id, payload, payload_hash, status, priority, attempt_count, verification_attempt, max_attempts, max_verification_attempts, timeout_seconds, lease_seconds, heartbeat_interval_seconds, replay_safe, rollback_allowed, available_at, deadline_at, started_at, completed_at, cancel_requested_at, error_code, error_summary, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_request_async_job_cancel(
    $1::uuid,
    $2::text
)
`

type RequestAsyncJobCancelParams struct {
	JobID      pgtype.UUID `json:"job_id"`
	ReasonCode string      `json:"reason_code"`
}

func (q *Queries) RequestAsyncJobCancel(ctx context.Context, arg RequestAsyncJobCancelParams) (AsyncJob, error) {
	row := q.db.QueryRow(ctx, requestAsyncJobCancel, arg.JobID, arg.ReasonCode)
	var i AsyncJob
	err := row.Scan(
		&i.JobID,
		&i.IdempotencyKey,
		&i.JobKind,
		&i.PayloadSchemaVersion,
		&i.OperationID,
		&i.Payload,
		&i.PayloadHash,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.VerificationAttempt,
		&i.MaxAttempts,
		&i.MaxVerificationAttempts,
		&i.TimeoutSeconds,
		&i.LeaseSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.ReplaySafe,
		&i.RollbackAllowed,
		&i.AvailableAt,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionAsyncJobFenced = `-- name: TransitionAsyncJobFenced :one
SELECT job_id, idempotency_key, job_kind, payload_schema_version, operation_id, payload, payload_hash, status, priority, attempt_count, verification_attempt, max_attempts, max_verification_attempts, timeout_seconds, lease_seconds, heartbeat_interval_seconds, replay_safe, rollback_allowed, available_at, deadline_at, started_at, completed_at, cancel_requested_at, error_code, error_summary, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_transition_async_job_fenced(
    $1::uuid,
    $2::text,
    $3::uuid,
    $4::text,
    $5::text,
    $6::integer,
    $7::text,
    $8::text,
    $9::text,
    $10::text,
    $11::boolean
)
`

type TransitionAsyncJobFencedParams struct {
	JobID             pgtype.UUID `json:"job_id"`
	ExpectedStatus    string      `json:"expected_status"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
	TargetStatus      string      `json:"target_status"`
	EventType         string      `json:"event_type"`
	RetryDelaySeconds int32       `json:"retry_delay_seconds"`
	ReasonCode        pgtype.Text `json:"reason_code"`
	ErrorCode         pgtype.Text `json:"error_code"`
	ErrorSummary      pgtype.Text `json:"error_summary"`
	ActorType         string      `json:"actor_type"`
	ReleaseLease      bool        `json:"release_lease"`
}

func (q *Queries) TransitionAsyncJobFenced(ctx context.Context, arg TransitionAsyncJobFencedParams) (AsyncJob, error) {
	row := q.db.QueryRow(ctx, transitionAsyncJobFenced,
		arg.JobID,
		arg.ExpectedStatus,
		arg.LeaseFencingToken,
		arg.TargetStatus,
		arg.EventType,
		arg.RetryDelaySeconds,
		arg.ReasonCode,
		arg.ErrorCode,
		arg.ErrorSummary,
		arg.ActorType,
		arg.ReleaseLease,
	)
	var i AsyncJob
	err := row.Scan(
		&i.JobID,
		&i.IdempotencyKey,
		&i.JobKind,
		&i.PayloadSchemaVersion,
		&i.OperationID,
		&i.Payload,
		&i.PayloadHash,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.VerificationAttempt,
		&i.MaxAttempts,
		&i.MaxVerificationAttempts,
		&i.TimeoutSeconds,
		&i.LeaseSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.ReplaySafe,
		&i.RollbackAllowed,
		&i.AvailableAt,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionOutboxEventFenced = `-- name: TransitionOutboxEventFenced :one
SELECT event_id, event_key, job_id, operation_id, topic, envelope, status, attempt_count, max_attempts, available_at, sent_at, error_code, lease_owner, lease_fencing_token, lease_expires_at, created_at, updated_at FROM public.control_transition_outbox_fenced(
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::integer,
    $5::text
)
`

type TransitionOutboxEventFencedParams struct {
	EventID           pgtype.UUID `json:"event_id"`
	LeaseFencingToken pgtype.UUID `json:"lease_fencing_token"`
	TargetStatus      string      `json:"target_status"`
	RetryDelaySeconds int32       `json:"retry_delay_seconds"`
	ErrorCode         pgtype.Text `json:"error_code"`
}

func (q *Queries) TransitionOutboxEventFenced(ctx context.Context, arg TransitionOutboxEventFencedParams) (OperationOutbox, error) {
	row := q.db.QueryRow(ctx, transitionOutboxEventFenced,
		arg.EventID,
		arg.LeaseFencingToken,
		arg.TargetStatus,
		arg.RetryDelaySeconds,
		arg.ErrorCode,
	)
	var i OperationOutbox
	err := row.Scan(
		&i.EventID,
		&i.EventKey,
		&i.JobID,
		&i.OperationID,
		&i.Topic,
		&i.Envelope,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.SentAt,
		&i.ErrorCode,
		&i.LeaseOwner,
		&i.LeaseFencingToken,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
