// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AsyncJob struct {
	JobID                    pgtype.UUID        `json:"job_id"`
	IdempotencyKey           string             `json:"idempotency_key"`
	JobKind                  string             `json:"job_kind"`
	PayloadSchemaVersion     int32              `json:"payload_schema_version"`
	OperationID              pgtype.UUID        `json:"operation_id"`
	Payload                  []byte             `json:"payload"`
	PayloadHash              []byte             `json:"payload_hash"`
	Status                   string             `json:"status"`
	Priority                 int16              `json:"priority"`
	AttemptCount             int32              `json:"attempt_count"`
	VerificationAttempt      int32              `json:"verification_attempt"`
	MaxAttempts              int32              `json:"max_attempts"`
	MaxVerificationAttempts  int32              `json:"max_verification_attempts"`
	TimeoutSeconds           int32              `json:"timeout_seconds"`
	LeaseSeconds             int32              `json:"lease_seconds"`
	HeartbeatIntervalSeconds int32              `json:"heartbeat_interval_seconds"`
	ReplaySafe               bool               `json:"replay_safe"`
	RollbackAllowed          bool               `json:"rollback_allowed"`
	AvailableAt              pgtype.Timestamptz `json:"available_at"`
	DeadlineAt               pgtype.Timestamptz `json:"deadline_at"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelRequestedAt        pgtype.Timestamptz `json:"cancel_requested_at"`
	ErrorCode                pgtype.Text        `json:"error_code"`
	ErrorSummary             pgtype.Text        `json:"error_summary"`
	LeaseOwner               pgtype.Text        `json:"lease_owner"`
	LeaseFencingToken        pgtype.UUID        `json:"lease_fencing_token"`
	LeaseExpiresAt           pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type AsyncJobEvent struct {
	JobID      pgtype.UUID        `json:"job_id"`
	Sequence   int64              `json:"sequence"`
	EventType  string             `json:"event_type"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Attempt    int32              `json:"attempt"`
	ReasonCode pgtype.Text        `json:"reason_code"`
	ErrorCode  pgtype.Text        `json:"error_code"`
	ActorType  string             `json:"actor_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type AsyncJobKind struct {
	JobKind                        string             `json:"job_kind"`
	PayloadSchemaVersion           int32              `json:"payload_schema_version"`
	DefaultTimeoutSeconds          int32              `json:"default_timeout_seconds"`
	LeaseSeconds                   int32              `json:"lease_seconds"`
	HeartbeatIntervalSeconds       int32              `json:"heartbeat_interval_seconds"`
	DefaultMaxAttempts             int32              `json:"default_max_attempts"`
	DefaultMaxVerificationAttempts int32              `json:"default_max_verification_attempts"`
	ReplaySafe                     bool               `json:"replay_safe"`
	RollbackAllowed                bool               `json:"rollback_allowed"`
	LifecycleStatus                string             `json:"lifecycle_status"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	AuditID           pgtype.UUID        `json:"audit_id"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	Category          string             `json:"category"`
	Action            string             `json:"action"`
	Result            string             `json:"result"`
	ActorAdminID      pgtype.UUID        `json:"actor_admin_id"`
	TargetAdminID     pgtype.UUID        `json:"target_admin_id"`
	ActorFingerprint  []byte             `json:"actor_fingerprint"`
	SourceFingerprint []byte             `json:"source_fingerprint"`
	Reason            pgtype.Text        `json:"reason"`
	RequestID         string             `json:"request_id"`
	Details           []byte             `json:"details"`
}

type ControlAdminActivationToken struct {
	ActivationTokenID pgtype.UUID        `json:"activation_token_id"`
	AdminID           pgtype.UUID        `json:"admin_id"`
	CreatedByAdminID  pgtype.UUID        `json:"created_by_admin_id"`
	TokenDigest       []byte             `json:"token_digest"`
	KeyVersion        int32              `json:"key_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type ControlAdminPassword struct {
	AdminID          pgtype.UUID        `json:"admin_id"`
	PasswordPhc      string             `json:"password_phc"`
	ParameterVersion int32              `json:"parameter_version"`
	ChangedAt        pgtype.Timestamptz `json:"changed_at"`
}

type ControlAdminRecoveryCode struct {
	RecoveryCodeID pgtype.UUID        `json:"recovery_code_id"`
	AdminID        pgtype.UUID        `json:"admin_id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	CodeDigest     []byte             `json:"code_digest"`
	KeyVersion     int32              `json:"key_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type ControlAdminSafetyGuard struct {
	SingletonID int16 `json:"singleton_id"`
}

type ControlAdminSession struct {
	SessionID         pgtype.UUID        `json:"session_id"`
	AdminID           pgtype.UUID        `json:"admin_id"`
	TokenDigest       []byte             `json:"token_digest"`
	CsrfDigest        []byte             `json:"csrf_digest"`
	KeyVersion        int32              `json:"key_version"`
	MfaMethod         string             `json:"mfa_method"`
	MfaCompletedAt    pgtype.Timestamptz `json:"mfa_completed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastActivityAt    pgtype.Timestamptz `json:"last_activity_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	ReauthenticatedAt pgtype.Timestamptz `json:"reauthenticated_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason      pgtype.Text        `json:"revoke_reason"`
}

type ControlAdminTotp struct {
	AdminID         pgtype.UUID        `json:"admin_id"`
	EncryptedSecret []byte             `json:"encrypted_secret"`
	Nonce           []byte             `json:"nonce"`
	KeyVersion      int32              `json:"key_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	LastUsedStep    pgtype.Int8        `json:"last_used_step"`
}

type ControlAdminUser struct {
	AdminID     pgtype.UUID        `json:"admin_id"`
	LoginName   string             `json:"login_name"`
	DisplayName string             `json:"display_name"`
	AuthSource  string             `json:"auth_source"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type ControlAuthChallenge struct {
	ChallengeID       pgtype.UUID        `json:"challenge_id"`
	AdminID           pgtype.UUID        `json:"admin_id"`
	TokenDigest       []byte             `json:"token_digest"`
	KeyVersion        int32              `json:"key_version"`
	SourceFingerprint []byte             `json:"source_fingerprint"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type ControlAuthFailureEvent struct {
	FailureEventID     int64              `json:"failure_event_id"`
	Dimension          string             `json:"dimension"`
	KeyVersion         int32              `json:"key_version"`
	SubjectFingerprint []byte             `json:"subject_fingerprint"`
	OccurredAt         pgtype.Timestamptz `json:"occurred_at"`
}

type ControlAuthFailureWindow struct {
	Dimension          string             `json:"dimension"`
	KeyVersion         int32              `json:"key_version"`
	SubjectFingerprint []byte             `json:"subject_fingerprint"`
	BlockedUntil       pgtype.Timestamptz `json:"blocked_until"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ControlBootstrapState struct {
	SingletonID    int16              `json:"singleton_id"`
	State          string             `json:"state"`
	PendingAdminID pgtype.UUID        `json:"pending_admin_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DriverCapability struct {
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	Capability            string             `json:"capability"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

// Singleton identity for this Control deployment and its independent database.
type Environment struct {
	SingletonID     int16              `json:"singleton_id"`
	EnvironmentID   string             `json:"environment_id"`
	Name            string             `json:"name"`
	EnvironmentType string             `json:"environment_type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type GatewayInstance struct {
	SingletonID            int16              `json:"singleton_id"`
	InstanceID             pgtype.UUID        `json:"instance_id"`
	DisplayName            string             `json:"display_name"`
	ManagementEndpoint     string             `json:"management_endpoint"`
	ReaderSecretRef        pgtype.Text        `json:"reader_secret_ref"`
	ReaderSecretConfigured pgtype.Bool        `json:"reader_secret_configured"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type NodeCapability struct {
	InstanceID            pgtype.UUID        `json:"instance_id"`
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	Capability            string             `json:"capability"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type NodeDriver struct {
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	DisplayName           string             `json:"display_name"`
	LifecycleStatus       string             `json:"lifecycle_status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type OperationOutbox struct {
	EventID           pgtype.UUID        `json:"event_id"`
	EventKey          string             `json:"event_key"`
	JobID             pgtype.UUID        `json:"job_id"`
	OperationID       pgtype.UUID        `json:"operation_id"`
	Topic             string             `json:"topic"`
	Envelope          []byte             `json:"envelope"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	MaxAttempts       int32              `json:"max_attempts"`
	AvailableAt       pgtype.Timestamptz `json:"available_at"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	ErrorCode         pgtype.Text        `json:"error_code"`
	LeaseOwner        pgtype.Text        `json:"lease_owner"`
	LeaseFencingToken pgtype.UUID        `json:"lease_fencing_token"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProviderInventoryPolicyActivation struct {
	ActivationID          pgtype.UUID                      `json:"activation_id"`
	NodeType              string                           `json:"node_type"`
	DriverContractVersion string                           `json:"driver_contract_version"`
	PolicyVersionID       pgtype.UUID                      `json:"policy_version_id"`
	EffectiveFrom         pgtype.Timestamptz               `json:"effective_from"`
	EffectiveTo           pgtype.Timestamptz               `json:"effective_to"`
	ActiveRange           pgtype.Range[pgtype.Timestamptz] `json:"active_range"`
	ActivatedBy           string                           `json:"activated_by"`
	CreatedAt             pgtype.Timestamptz               `json:"created_at"`
}

type ProviderInventoryPolicyBinding struct {
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	PolicyVersionID       pgtype.UUID        `json:"policy_version_id"`
	BoundBy               string             `json:"bound_by"`
	BoundAt               pgtype.Timestamptz `json:"bound_at"`
}

type ProviderInventoryPolicyVersion struct {
	PolicyVersionID       pgtype.UUID        `json:"policy_version_id"`
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	ActiveProviders       []string           `json:"active_providers"`
	OutOfScopeProviders   []string           `json:"out_of_scope_providers"`
	ContentHash           []byte             `json:"content_hash"`
	CreatedBy             string             `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type RelayNodeAsset struct {
	InstanceID             pgtype.UUID        `json:"instance_id"`
	DisplayName            string             `json:"display_name"`
	NodeType               string             `json:"node_type"`
	DriverContractVersion  string             `json:"driver_contract_version"`
	ManagementEndpoint     string             `json:"management_endpoint"`
	ReaderSecretRef        pgtype.Text        `json:"reader_secret_ref"`
	ReaderSecretConfigured pgtype.Bool        `json:"reader_secret_configured"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type RelayNodeInventoryMonitoringActivation struct {
	MonitoringActivationID pgtype.UUID                      `json:"monitoring_activation_id"`
	InstanceID             pgtype.UUID                      `json:"instance_id"`
	EffectiveFrom          pgtype.Timestamptz               `json:"effective_from"`
	EffectiveTo            pgtype.Timestamptz               `json:"effective_to"`
	ActiveRange            pgtype.Range[pgtype.Timestamptz] `json:"active_range"`
	Reason                 string                           `json:"reason"`
	Actor                  string                           `json:"actor"`
	EndReason              pgtype.Text                      `json:"end_reason"`
	EndActor               pgtype.Text                      `json:"end_actor"`
	EndRecordedAt          pgtype.Timestamptz               `json:"end_recorded_at"`
	CreatedAt              pgtype.Timestamptz               `json:"created_at"`
}
