// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountInventory struct {
	InstanceID              pgtype.UUID        `json:"instance_id"`
	Provider                string             `json:"provider"`
	AccountKey              string             `json:"account_key"`
	NormalizedEmail         string             `json:"normalized_email"`
	BasicStatus             string             `json:"basic_status"`
	SuccessCount            int64              `json:"success_count"`
	FailedCount             int64              `json:"failed_count"`
	RecentRequestCount      int64              `json:"recent_request_count"`
	LastRefreshAt           pgtype.Timestamptz `json:"last_refresh_at"`
	NextRetryAt             pgtype.Timestamptz `json:"next_retry_at"`
	SourceUpdatedAt         pgtype.Timestamptz `json:"source_updated_at"`
	Lifecycle               string             `json:"lifecycle"`
	ConsecutiveMissingCount int32              `json:"consecutive_missing_count"`
	MissingSince            pgtype.Timestamptz `json:"missing_since"`
	OutOfScopeSince         pgtype.Timestamptz `json:"out_of_scope_since"`
	FirstSeenAt             pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	CurrentPollRunID        pgtype.UUID        `json:"current_poll_run_id"`
	CurrentScheduledAt      pgtype.Timestamptz `json:"current_scheduled_at"`
	SourceObservedAt        pgtype.Timestamptz `json:"source_observed_at"`
	SourceNodeVersion       string             `json:"source_node_version"`
	SourceNodeCommit        string             `json:"source_node_commit"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type AccountInventoryCompactionRun struct {
	CompactionRunID            pgtype.UUID        `json:"compaction_run_id"`
	SummaryDate                pgtype.Date        `json:"summary_date"`
	InstanceID                 pgtype.UUID        `json:"instance_id"`
	ProviderPolicyVersion      pgtype.UUID        `json:"provider_policy_version"`
	Status                     string             `json:"status"`
	FailedFrom                 pgtype.Text        `json:"failed_from"`
	ClaimOwner                 pgtype.Text        `json:"claim_owner"`
	LeaseExpiresAt             pgtype.Timestamptz `json:"lease_expires_at"`
	FencingToken               pgtype.UUID        `json:"fencing_token"`
	AttemptCount               int32              `json:"attempt_count"`
	ChecksumVersion            pgtype.Int2        `json:"checksum_version"`
	SourceSnapshotCount        pgtype.Int8        `json:"source_snapshot_count"`
	SourcePollCount            pgtype.Int8        `json:"source_poll_count"`
	SourceProviderResultCount  pgtype.Int8        `json:"source_provider_result_count"`
	SourceDuplicateCount       pgtype.Int8        `json:"source_duplicate_count"`
	SourceChecksum             []byte             `json:"source_checksum"`
	DeletedSnapshotCount       int64              `json:"deleted_snapshot_count"`
	DeletedPollCount           int64              `json:"deleted_poll_count"`
	DeletedProviderResultCount int64              `json:"deleted_provider_result_count"`
	DeletedDuplicateCount      int64              `json:"deleted_duplicate_count"`
	FailureReason              pgtype.Text        `json:"failure_reason"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	SummarizedAt               pgtype.Timestamptz `json:"summarized_at"`
	DeletingAt                 pgtype.Timestamptz `json:"deleting_at"`
	CompletedAt                pgtype.Timestamptz `json:"completed_at"`
	FailedAt                   pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type AccountInventoryDailyAccountRollup struct {
	AccountRollupID   pgtype.UUID        `json:"account_rollup_id"`
	RollupRunID       pgtype.UUID        `json:"rollup_run_id"`
	SummaryDate       pgtype.Date        `json:"summary_date"`
	InstanceID        pgtype.UUID        `json:"instance_id"`
	Provider          string             `json:"provider"`
	AccountKey        string             `json:"account_key"`
	FirstScheduledAt  pgtype.Timestamptz `json:"first_scheduled_at"`
	LastScheduledAt   pgtype.Timestamptz `json:"last_scheduled_at"`
	FirstObservedAt   pgtype.Timestamptz `json:"first_observed_at"`
	LastObservedAt    pgtype.Timestamptz `json:"last_observed_at"`
	LastBasicStatus   string             `json:"last_basic_status"`
	SampleCount       int32              `json:"sample_count"`
	DisabledCount     int32              `json:"disabled_count"`
	UnavailableCount  int32              `json:"unavailable_count"`
	ErrorCount        int32              `json:"error_count"`
	ActiveCount       int32              `json:"active_count"`
	UnknownCount      int32              `json:"unknown_count"`
	FirstSuccessCount int64              `json:"first_success_count"`
	LastSuccessCount  int64              `json:"last_success_count"`
	SuccessResetCount int32              `json:"success_reset_count"`
	FirstFailedCount  int64              `json:"first_failed_count"`
	LastFailedCount   int64              `json:"last_failed_count"`
	FailedResetCount  int32              `json:"failed_reset_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AccountInventoryDailyProviderRollup struct {
	ProviderRollupID             pgtype.UUID        `json:"provider_rollup_id"`
	RollupRunID                  pgtype.UUID        `json:"rollup_run_id"`
	SummaryDate                  pgtype.Date        `json:"summary_date"`
	InstanceID                   pgtype.UUID        `json:"instance_id"`
	Provider                     string             `json:"provider"`
	ExpectedPollCount            int32              `json:"expected_poll_count"`
	TransportSuccessCount        int32              `json:"transport_success_count"`
	ContractValidCount           int32              `json:"contract_valid_count"`
	SnapshotCompleteCount        int32              `json:"snapshot_complete_count"`
	PromotionAppliedCount        int32              `json:"promotion_applied_count"`
	PromotionSkippedCount        int32              `json:"promotion_skipped_count"`
	PolicyChangedCount           int32              `json:"policy_changed_count"`
	AbandonedCount               int32              `json:"abandoned_count"`
	DegradedCount                int32              `json:"degraded_count"`
	FirstPromotionAt             pgtype.Timestamptz `json:"first_promotion_at"`
	LastPromotionAt              pgtype.Timestamptz `json:"last_promotion_at"`
	CoverageNumerator            int32              `json:"coverage_numerator"`
	CoverageDenominator          int32              `json:"coverage_denominator"`
	CoverageRatio                pgtype.Numeric     `json:"coverage_ratio"`
	CoverageThresholdBasisPoints int32              `json:"coverage_threshold_basis_points"`
	CoverageStatus               string             `json:"coverage_status"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
}

type AccountInventoryDailyProviderSummary struct {
	ProviderSummaryID            pgtype.UUID        `json:"provider_summary_id"`
	CompactionRunID              pgtype.UUID        `json:"compaction_run_id"`
	SummaryDate                  pgtype.Date        `json:"summary_date"`
	InstanceID                   pgtype.UUID        `json:"instance_id"`
	Provider                     string             `json:"provider"`
	ProviderPolicyVersion        pgtype.UUID        `json:"provider_policy_version"`
	ExpectedPollCount            int32              `json:"expected_poll_count"`
	TransportSuccessCount        int32              `json:"transport_success_count"`
	ContractValidCount           int32              `json:"contract_valid_count"`
	SnapshotCompleteCount        int32              `json:"snapshot_complete_count"`
	PromotionAppliedCount        int32              `json:"promotion_applied_count"`
	PromotionSkippedCount        int32              `json:"promotion_skipped_count"`
	PolicyChangedCount           int32              `json:"policy_changed_count"`
	AbandonedCount               int32              `json:"abandoned_count"`
	DegradedCount                int32              `json:"degraded_count"`
	FirstPromotionAt             pgtype.Timestamptz `json:"first_promotion_at"`
	LastPromotionAt              pgtype.Timestamptz `json:"last_promotion_at"`
	CoverageNumerator            int32              `json:"coverage_numerator"`
	CoverageDenominator          int32              `json:"coverage_denominator"`
	CoverageRatio                pgtype.Numeric     `json:"coverage_ratio"`
	CoverageThresholdBasisPoints int32              `json:"coverage_threshold_basis_points"`
	CoverageStatus               string             `json:"coverage_status"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
}

type AccountInventoryDailyRollupRun struct {
	RollupRunID           pgtype.UUID        `json:"rollup_run_id"`
	SummaryDate           pgtype.Date        `json:"summary_date"`
	InstanceID            pgtype.UUID        `json:"instance_id"`
	Status                string             `json:"status"`
	ClaimOwner            pgtype.Text        `json:"claim_owner"`
	LeaseExpiresAt        pgtype.Timestamptz `json:"lease_expires_at"`
	FencingToken          pgtype.UUID        `json:"fencing_token"`
	CompletedFencingToken pgtype.UUID        `json:"completed_fencing_token"`
	AttemptCount          int32              `json:"attempt_count"`
	ExpectedSegmentCount  pgtype.Int4        `json:"expected_segment_count"`
	CompletedSegmentCount pgtype.Int4        `json:"completed_segment_count"`
	ChecksumVersion       pgtype.Int2        `json:"checksum_version"`
	SegmentChecksum       []byte             `json:"segment_checksum"`
	FailureReason         pgtype.Text        `json:"failure_reason"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	FailedAt              pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AccountInventoryDailySummary struct {
	SummaryID             pgtype.UUID        `json:"summary_id"`
	CompactionRunID       pgtype.UUID        `json:"compaction_run_id"`
	SummaryDate           pgtype.Date        `json:"summary_date"`
	InstanceID            pgtype.UUID        `json:"instance_id"`
	Provider              string             `json:"provider"`
	AccountKey            string             `json:"account_key"`
	ProviderPolicyVersion pgtype.UUID        `json:"provider_policy_version"`
	FirstScheduledAt      pgtype.Timestamptz `json:"first_scheduled_at"`
	LastScheduledAt       pgtype.Timestamptz `json:"last_scheduled_at"`
	FirstObservedAt       pgtype.Timestamptz `json:"first_observed_at"`
	LastObservedAt        pgtype.Timestamptz `json:"last_observed_at"`
	LastBasicStatus       string             `json:"last_basic_status"`
	SampleCount           int32              `json:"sample_count"`
	DisabledCount         int32              `json:"disabled_count"`
	UnavailableCount      int32              `json:"unavailable_count"`
	ErrorCount            int32              `json:"error_count"`
	ActiveCount           int32              `json:"active_count"`
	UnknownCount          int32              `json:"unknown_count"`
	FirstSuccessCount     int64              `json:"first_success_count"`
	LastSuccessCount      int64              `json:"last_success_count"`
	SuccessResetCount     int32              `json:"success_reset_count"`
	FirstFailedCount      int64              `json:"first_failed_count"`
	LastFailedCount       int64              `json:"last_failed_count"`
	FailedResetCount      int32              `json:"failed_reset_count"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type AccountInventoryHistoryRetiredDay struct {
	SummaryDate pgtype.Date        `json:"summary_date"`
	InstanceID  pgtype.UUID        `json:"instance_id"`
	RetiredAt   pgtype.Timestamptz `json:"retired_at"`
}

type AccountInventoryPollDuplicate struct {
	PollRunID       pgtype.UUID        `json:"poll_run_id"`
	InstanceID      pgtype.UUID        `json:"instance_id"`
	Provider        string             `json:"provider"`
	AccountKey      string             `json:"account_key"`
	OccurrenceCount int32              `json:"occurrence_count"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
}

type AccountInventoryPollProviderResult struct {
	PollRunID              pgtype.UUID `json:"poll_run_id"`
	Provider               string      `json:"provider"`
	IdentifiableCount      int32       `json:"identifiable_count"`
	MissingIdentityCount   int32       `json:"missing_identity_count"`
	DuplicateIdentityCount int32       `json:"duplicate_identity_count"`
	IdentityComplete       bool        `json:"identity_complete"`
	SnapshotComplete       bool        `json:"snapshot_complete"`
	Degraded               bool        `json:"degraded"`
	Reason                 string      `json:"reason"`
	PromotionApplied       bool        `json:"promotion_applied"`
	PromotionSkippedReason pgtype.Text `json:"promotion_skipped_reason"`
}

type AccountInventoryPollRun struct {
	PollRunID                pgtype.UUID        `json:"poll_run_id"`
	InstanceID               pgtype.UUID        `json:"instance_id"`
	NodeType                 string             `json:"node_type"`
	DriverContractVersion    string             `json:"driver_contract_version"`
	ScheduledAt              pgtype.Timestamptz `json:"scheduled_at"`
	ProviderPolicyVersion    pgtype.UUID        `json:"provider_policy_version"`
	Status                   string             `json:"status"`
	AttemptCount             int32              `json:"attempt_count"`
	MaxAttempts              int32              `json:"max_attempts"`
	PollStartGraceSeconds    int32              `json:"poll_start_grace_seconds"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	FirstStartedAt           pgtype.Timestamptz `json:"first_started_at"`
	LastStartedAt            pgtype.Timestamptz `json:"last_started_at"`
	LeaseExpiresAt           pgtype.Timestamptz `json:"lease_expires_at"`
	LeaseFencingToken        pgtype.UUID        `json:"lease_fencing_token"`
	FinalizedAt              pgtype.Timestamptz `json:"finalized_at"`
	AbandonedAt              pgtype.Timestamptz `json:"abandoned_at"`
	ExecutionReason          pgtype.Text        `json:"execution_reason"`
	ObservedAt               pgtype.Timestamptz `json:"observed_at"`
	TransportSuccess         pgtype.Bool        `json:"transport_success"`
	ResponseShapeValid       pgtype.Bool        `json:"response_shape_valid"`
	ContractValid            pgtype.Bool        `json:"contract_valid"`
	InventoryMode            pgtype.Text        `json:"inventory_mode"`
	NodeIdentityComplete     pgtype.Bool        `json:"node_identity_complete"`
	SnapshotComplete         pgtype.Bool        `json:"snapshot_complete"`
	Degraded                 pgtype.Bool        `json:"degraded"`
	Result                   pgtype.Text        `json:"result"`
	Reason                   pgtype.Text        `json:"reason"`
	SourceRecordCount        pgtype.Int4        `json:"source_record_count"`
	IdentifiableRecordCount  pgtype.Int4        `json:"identifiable_record_count"`
	UnidentifiedRecordCount  pgtype.Int4        `json:"unidentified_record_count"`
	UnsupportedProviderCount pgtype.Int4        `json:"unsupported_provider_count"`
	OutOfScopeProviderCount  pgtype.Int4        `json:"out_of_scope_provider_count"`
	NodeVersion              pgtype.Text        `json:"node_version"`
	NodeCommit               pgtype.Text        `json:"node_commit"`
	PromotionSkippedReason   pgtype.Text        `json:"promotion_skipped_reason"`
}

type AccountInventoryProviderState struct {
	InstanceID         pgtype.UUID        `json:"instance_id"`
	Provider           string             `json:"provider"`
	CurrentPollRunID   pgtype.UUID        `json:"current_poll_run_id"`
	CurrentScheduledAt pgtype.Timestamptz `json:"current_scheduled_at"`
	LastCompleteAt     pgtype.Timestamptz `json:"last_complete_at"`
	SourceObservedAt   pgtype.Timestamptz `json:"source_observed_at"`
	SourceNodeVersion  string             `json:"source_node_version"`
	SourceNodeCommit   string             `json:"source_node_commit"`
	State              string             `json:"state"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	MonitoringStatus   string             `json:"monitoring_status"`
	OutOfScopeSince    pgtype.Timestamptz `json:"out_of_scope_since"`
	HealthScheduledAt  pgtype.Timestamptz `json:"health_scheduled_at"`
	HealthDegraded     bool               `json:"health_degraded"`
	HealthReason       string             `json:"health_reason"`
}

type AccountInventoryScopeTransitionAudit struct {
	AuditID               pgtype.UUID        `json:"audit_id"`
	ActivationID          pgtype.UUID        `json:"activation_id"`
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	Actor                 string             `json:"actor"`
	Reason                string             `json:"reason"`
	MovedOutProviders     []string           `json:"moved_out_providers"`
	ReactivatedProviders  []string           `json:"reactivated_providers"`
	TransitionedAt        pgtype.Timestamptz `json:"transitioned_at"`
}

type AccountInventorySnapshotItem struct {
	PollRunID          pgtype.UUID        `json:"poll_run_id"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	Provider           string             `json:"provider"`
	AccountKey         string             `json:"account_key"`
	NormalizedEmail    string             `json:"normalized_email"`
	BasicStatus        string             `json:"basic_status"`
	SuccessCount       int64              `json:"success_count"`
	FailedCount        int64              `json:"failed_count"`
	RecentRequestCount int64              `json:"recent_request_count"`
	LastRefreshAt      pgtype.Timestamptz `json:"last_refresh_at"`
	NextRetryAt        pgtype.Timestamptz `json:"next_retry_at"`
	SourceUpdatedAt    pgtype.Timestamptz `json:"source_updated_at"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
}

type AsyncJob struct {
	JobID                    pgtype.UUID        `json:"job_id"`
	IdempotencyKey           string             `json:"idempotency_key"`
	JobKind                  string             `json:"job_kind"`
	PayloadSchemaVersion     int32              `json:"payload_schema_version"`
	OperationID              pgtype.UUID        `json:"operation_id"`
	Payload                  []byte             `json:"payload"`
	PayloadHash              []byte             `json:"payload_hash"`
	Status                   string             `json:"status"`
	Priority                 int16              `json:"priority"`
	AttemptCount             int32              `json:"attempt_count"`
	VerificationAttempt      int32              `json:"verification_attempt"`
	MaxAttempts              int32              `json:"max_attempts"`
	MaxVerificationAttempts  int32              `json:"max_verification_attempts"`
	TimeoutSeconds           int32              `json:"timeout_seconds"`
	LeaseSeconds             int32              `json:"lease_seconds"`
	HeartbeatIntervalSeconds int32              `json:"heartbeat_interval_seconds"`
	ReplaySafe               bool               `json:"replay_safe"`
	RollbackAllowed          bool               `json:"rollback_allowed"`
	AvailableAt              pgtype.Timestamptz `json:"available_at"`
	DeadlineAt               pgtype.Timestamptz `json:"deadline_at"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelRequestedAt        pgtype.Timestamptz `json:"cancel_requested_at"`
	ErrorCode                pgtype.Text        `json:"error_code"`
	ErrorSummary             pgtype.Text        `json:"error_summary"`
	LeaseOwner               pgtype.Text        `json:"lease_owner"`
	LeaseFencingToken        pgtype.UUID        `json:"lease_fencing_token"`
	LeaseExpiresAt           pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type AsyncJobEvent struct {
	JobID      pgtype.UUID        `json:"job_id"`
	Sequence   int64              `json:"sequence"`
	EventType  string             `json:"event_type"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Attempt    int32              `json:"attempt"`
	ReasonCode pgtype.Text        `json:"reason_code"`
	ErrorCode  pgtype.Text        `json:"error_code"`
	ActorType  string             `json:"actor_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type AsyncJobKind struct {
	JobKind                        string             `json:"job_kind"`
	PayloadSchemaVersion           int32              `json:"payload_schema_version"`
	DefaultTimeoutSeconds          int32              `json:"default_timeout_seconds"`
	LeaseSeconds                   int32              `json:"lease_seconds"`
	HeartbeatIntervalSeconds       int32              `json:"heartbeat_interval_seconds"`
	DefaultMaxAttempts             int32              `json:"default_max_attempts"`
	DefaultMaxVerificationAttempts int32              `json:"default_max_verification_attempts"`
	ReplaySafe                     bool               `json:"replay_safe"`
	RollbackAllowed                bool               `json:"rollback_allowed"`
	LifecycleStatus                string             `json:"lifecycle_status"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	AuditID           pgtype.UUID        `json:"audit_id"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	Category          string             `json:"category"`
	Action            string             `json:"action"`
	Result            string             `json:"result"`
	ActorAdminID      pgtype.UUID        `json:"actor_admin_id"`
	TargetAdminID     pgtype.UUID        `json:"target_admin_id"`
	ActorFingerprint  []byte             `json:"actor_fingerprint"`
	SourceFingerprint []byte             `json:"source_fingerprint"`
	Reason            pgtype.Text        `json:"reason"`
	RequestID         string             `json:"request_id"`
	Details           []byte             `json:"details"`
}

type ControlAdminActivationToken struct {
	ActivationTokenID pgtype.UUID        `json:"activation_token_id"`
	AdminID           pgtype.UUID        `json:"admin_id"`
	CreatedByAdminID  pgtype.UUID        `json:"created_by_admin_id"`
	TokenDigest       []byte             `json:"token_digest"`
	KeyVersion        int32              `json:"key_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type ControlAdminPassword struct {
	AdminID          pgtype.UUID        `json:"admin_id"`
	PasswordPhc      string             `json:"password_phc"`
	ParameterVersion int32              `json:"parameter_version"`
	ChangedAt        pgtype.Timestamptz `json:"changed_at"`
}

type ControlAdminRecoveryCode struct {
	RecoveryCodeID pgtype.UUID        `json:"recovery_code_id"`
	AdminID        pgtype.UUID        `json:"admin_id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	CodeDigest     []byte             `json:"code_digest"`
	KeyVersion     int32              `json:"key_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type ControlAdminSafetyGuard struct {
	SingletonID int16 `json:"singleton_id"`
}

type ControlAdminSession struct {
	SessionID         pgtype.UUID        `json:"session_id"`
	AdminID           pgtype.UUID        `json:"admin_id"`
	TokenDigest       []byte             `json:"token_digest"`
	CsrfDigest        []byte             `json:"csrf_digest"`
	KeyVersion        int32              `json:"key_version"`
	MfaMethod         string             `json:"mfa_method"`
	MfaCompletedAt    pgtype.Timestamptz `json:"mfa_completed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastActivityAt    pgtype.Timestamptz `json:"last_activity_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	ReauthenticatedAt pgtype.Timestamptz `json:"reauthenticated_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason      pgtype.Text        `json:"revoke_reason"`
}

type ControlAdminTotp struct {
	AdminID         pgtype.UUID        `json:"admin_id"`
	EncryptedSecret []byte             `json:"encrypted_secret"`
	Nonce           []byte             `json:"nonce"`
	KeyVersion      int32              `json:"key_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	LastUsedStep    pgtype.Int8        `json:"last_used_step"`
}

type ControlAdminUser struct {
	AdminID     pgtype.UUID        `json:"admin_id"`
	LoginName   string             `json:"login_name"`
	DisplayName string             `json:"display_name"`
	AuthSource  string             `json:"auth_source"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type ControlAuthChallenge struct {
	ChallengeID       pgtype.UUID        `json:"challenge_id"`
	AdminID           pgtype.UUID        `json:"admin_id"`
	TokenDigest       []byte             `json:"token_digest"`
	KeyVersion        int32              `json:"key_version"`
	SourceFingerprint []byte             `json:"source_fingerprint"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type ControlAuthFailureEvent struct {
	FailureEventID     int64              `json:"failure_event_id"`
	Dimension          string             `json:"dimension"`
	KeyVersion         int32              `json:"key_version"`
	SubjectFingerprint []byte             `json:"subject_fingerprint"`
	OccurredAt         pgtype.Timestamptz `json:"occurred_at"`
}

type ControlAuthFailureWindow struct {
	Dimension          string             `json:"dimension"`
	KeyVersion         int32              `json:"key_version"`
	SubjectFingerprint []byte             `json:"subject_fingerprint"`
	BlockedUntil       pgtype.Timestamptz `json:"blocked_until"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ControlBootstrapState struct {
	SingletonID    int16              `json:"singleton_id"`
	State          string             `json:"state"`
	PendingAdminID pgtype.UUID        `json:"pending_admin_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DriverCapability struct {
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	Capability            string             `json:"capability"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

// Singleton identity for this Control deployment and its independent database.
type Environment struct {
	SingletonID     int16              `json:"singleton_id"`
	EnvironmentID   string             `json:"environment_id"`
	Name            string             `json:"name"`
	EnvironmentType string             `json:"environment_type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type GatewayDirectoryCurrentState struct {
	GatewayInstanceID         pgtype.UUID        `json:"gateway_instance_id"`
	CurrentSnapshotID         pgtype.UUID        `json:"current_snapshot_id"`
	CurrentContentFingerprint []byte             `json:"current_content_fingerprint"`
	LastSuccessReceivedAt     pgtype.Timestamptz `json:"last_success_received_at"`
	LastSourceGeneratedAt     pgtype.Timestamptz `json:"last_source_generated_at"`
	LastSuccessRunID          pgtype.UUID        `json:"last_success_run_id"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type GatewayDirectoryIngestionRun struct {
	IngestionRunID     pgtype.UUID        `json:"ingestion_run_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	Status             string             `json:"status"`
	AttemptCount       int16              `json:"attempt_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FirstStartedAt     pgtype.Timestamptz `json:"first_started_at"`
	LastStartedAt      pgtype.Timestamptz `json:"last_started_at"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	LeaseFencingToken  pgtype.UUID        `json:"lease_fencing_token"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
	Outcome            pgtype.Text        `json:"outcome"`
	LastFailureClass   pgtype.Text        `json:"last_failure_class"`
	SourceGeneratedAt  pgtype.Timestamptz `json:"source_generated_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ContentFingerprint []byte             `json:"content_fingerprint"`
	SnapshotID         pgtype.UUID        `json:"snapshot_id"`
	AccountCount       pgtype.Int4        `json:"account_count"`
}

type GatewayDirectorySnapshot struct {
	SnapshotID                 pgtype.UUID        `json:"snapshot_id"`
	GatewayInstanceID          pgtype.UUID        `json:"gateway_instance_id"`
	Fingerprint                []byte             `json:"fingerprint"`
	FingerprintEncodingVersion int16              `json:"fingerprint_encoding_version"`
	SchemaVersion              int32              `json:"schema_version"`
	AccountCount               int32              `json:"account_count"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type GatewayDirectorySnapshotItem struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	AccountID  int64       `json:"account_id"`
	Name       string      `json:"name"`
	Platform   string      `json:"platform"`
	Type       string      `json:"type"`
	Url        pgtype.Text `json:"url"`
	Status     string      `json:"status"`
}

type GatewayInstance struct {
	SingletonID            int16              `json:"singleton_id"`
	InstanceID             pgtype.UUID        `json:"instance_id"`
	DisplayName            string             `json:"display_name"`
	ManagementEndpoint     string             `json:"management_endpoint"`
	ReaderSecretRef        pgtype.Text        `json:"reader_secret_ref"`
	ReaderSecretConfigured pgtype.Bool        `json:"reader_secret_configured"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type NodeCapability struct {
	InstanceID            pgtype.UUID        `json:"instance_id"`
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	Capability            string             `json:"capability"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type NodeDriver struct {
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	DisplayName           string             `json:"display_name"`
	LifecycleStatus       string             `json:"lifecycle_status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type OperationOutbox struct {
	EventID           pgtype.UUID        `json:"event_id"`
	EventKey          string             `json:"event_key"`
	JobID             pgtype.UUID        `json:"job_id"`
	OperationID       pgtype.UUID        `json:"operation_id"`
	Topic             string             `json:"topic"`
	Envelope          []byte             `json:"envelope"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	MaxAttempts       int32              `json:"max_attempts"`
	AvailableAt       pgtype.Timestamptz `json:"available_at"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	ErrorCode         pgtype.Text        `json:"error_code"`
	LeaseOwner        pgtype.Text        `json:"lease_owner"`
	LeaseFencingToken pgtype.UUID        `json:"lease_fencing_token"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProviderInventoryPolicyActivation struct {
	ActivationID          pgtype.UUID                      `json:"activation_id"`
	NodeType              string                           `json:"node_type"`
	DriverContractVersion string                           `json:"driver_contract_version"`
	PolicyVersionID       pgtype.UUID                      `json:"policy_version_id"`
	EffectiveFrom         pgtype.Timestamptz               `json:"effective_from"`
	EffectiveTo           pgtype.Timestamptz               `json:"effective_to"`
	ActiveRange           pgtype.Range[pgtype.Timestamptz] `json:"active_range"`
	ActivatedBy           string                           `json:"activated_by"`
	CreatedAt             pgtype.Timestamptz               `json:"created_at"`
}

type ProviderInventoryPolicyBinding struct {
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	PolicyVersionID       pgtype.UUID        `json:"policy_version_id"`
	BoundBy               string             `json:"bound_by"`
	BoundAt               pgtype.Timestamptz `json:"bound_at"`
}

type ProviderInventoryPolicyVersion struct {
	PolicyVersionID       pgtype.UUID        `json:"policy_version_id"`
	NodeType              string             `json:"node_type"`
	DriverContractVersion string             `json:"driver_contract_version"`
	ActiveProviders       []string           `json:"active_providers"`
	OutOfScopeProviders   []string           `json:"out_of_scope_providers"`
	ContentHash           []byte             `json:"content_hash"`
	CreatedBy             string             `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type RelayNodeAsset struct {
	InstanceID             pgtype.UUID        `json:"instance_id"`
	DisplayName            string             `json:"display_name"`
	NodeType               string             `json:"node_type"`
	DriverContractVersion  string             `json:"driver_contract_version"`
	ManagementEndpoint     string             `json:"management_endpoint"`
	ReaderSecretRef        pgtype.Text        `json:"reader_secret_ref"`
	ReaderSecretConfigured pgtype.Bool        `json:"reader_secret_configured"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type RelayNodeGatewayAccountBinding struct {
	BindingID          pgtype.UUID        `json:"binding_id"`
	RelayNodeID        pgtype.UUID        `json:"relay_node_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	GatewayAccountID   int64              `json:"gateway_account_id"`
	EvidenceSnapshotID pgtype.UUID        `json:"evidence_snapshot_id"`
	BoundAt            pgtype.Timestamptz `json:"bound_at"`
	BoundBy            pgtype.UUID        `json:"bound_by"`
	BindReason         string             `json:"bind_reason"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	EndedBy            pgtype.UUID        `json:"ended_by"`
	EndReason          pgtype.Text        `json:"end_reason"`
}

type RelayNodeInventoryMonitoringActivation struct {
	MonitoringActivationID pgtype.UUID                      `json:"monitoring_activation_id"`
	InstanceID             pgtype.UUID                      `json:"instance_id"`
	EffectiveFrom          pgtype.Timestamptz               `json:"effective_from"`
	EffectiveTo            pgtype.Timestamptz               `json:"effective_to"`
	ActiveRange            pgtype.Range[pgtype.Timestamptz] `json:"active_range"`
	Reason                 string                           `json:"reason"`
	Actor                  string                           `json:"actor"`
	EndReason              pgtype.Text                      `json:"end_reason"`
	EndActor               pgtype.Text                      `json:"end_actor"`
	EndRecordedAt          pgtype.Timestamptz               `json:"end_recorded_at"`
	CreatedAt              pgtype.Timestamptz               `json:"created_at"`
}
