// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_monitoring.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestNodeDisableFence = `-- name: GetLatestNodeDisableFence :one
SELECT command_id, committed_at
FROM public.asset_admin_command_receipts
WHERE command_kind = 'node.monitoring_disable'
  AND sanitized_result->>'instance_id' = $1::text
ORDER BY committed_at DESC
LIMIT 1
`

type GetLatestNodeDisableFenceRow struct {
	CommandID   pgtype.UUID        `json:"command_id"`
	CommittedAt pgtype.Timestamptz `json:"committed_at"`
}

func (q *Queries) GetLatestNodeDisableFence(ctx context.Context, instanceID string) (GetLatestNodeDisableFenceRow, error) {
	row := q.db.QueryRow(ctx, getLatestNodeDisableFence, instanceID)
	var i GetLatestNodeDisableFenceRow
	err := row.Scan(&i.CommandID, &i.CommittedAt)
	return i, err
}

const getNodeMonitoringActivations = `-- name: GetNodeMonitoringActivations :many
SELECT monitoring_activation_id, instance_id, effective_from, effective_to,
       reason, actor, created_at, end_reason, end_actor, end_recorded_at,
       cancelled_at, cancelled_by, cancel_reason, active_range
FROM public.relay_node_inventory_monitoring_activations
WHERE instance_id = $1::uuid
ORDER BY effective_from, monitoring_activation_id
`

type GetNodeMonitoringActivationsRow struct {
	MonitoringActivationID pgtype.UUID                      `json:"monitoring_activation_id"`
	InstanceID             pgtype.UUID                      `json:"instance_id"`
	EffectiveFrom          pgtype.Timestamptz               `json:"effective_from"`
	EffectiveTo            pgtype.Timestamptz               `json:"effective_to"`
	Reason                 string                           `json:"reason"`
	Actor                  string                           `json:"actor"`
	CreatedAt              pgtype.Timestamptz               `json:"created_at"`
	EndReason              pgtype.Text                      `json:"end_reason"`
	EndActor               pgtype.Text                      `json:"end_actor"`
	EndRecordedAt          pgtype.Timestamptz               `json:"end_recorded_at"`
	CancelledAt            pgtype.Timestamptz               `json:"cancelled_at"`
	CancelledBy            pgtype.UUID                      `json:"cancelled_by"`
	CancelReason           pgtype.Text                      `json:"cancel_reason"`
	ActiveRange            pgtype.Range[pgtype.Timestamptz] `json:"active_range"`
}

func (q *Queries) GetNodeMonitoringActivations(ctx context.Context, instanceID pgtype.UUID) ([]GetNodeMonitoringActivationsRow, error) {
	rows, err := q.db.Query(ctx, getNodeMonitoringActivations, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNodeMonitoringActivationsRow{}
	for rows.Next() {
		var i GetNodeMonitoringActivationsRow
		if err := rows.Scan(
			&i.MonitoringActivationID,
			&i.InstanceID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Reason,
			&i.Actor,
			&i.CreatedAt,
			&i.EndReason,
			&i.EndActor,
			&i.EndRecordedAt,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.ActiveRange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
