// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relay_node_gateway_account_bindings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCurrentRelayNodeGatewayAccountBinding = `-- name: CloseCurrentRelayNodeGatewayAccountBinding :one
UPDATE relay_node_gateway_account_bindings
SET ended_at = $1::timestamptz,
    ended_by = $2::uuid,
    end_reason = $3::text
WHERE binding_id = $4::uuid
  AND relay_node_id = $5::uuid
  AND gateway_instance_id = $6::uuid
  AND gateway_account_id = $7::bigint
  AND ended_at IS NULL
RETURNING binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
`

type CloseCurrentRelayNodeGatewayAccountBindingParams struct {
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	EndedBy           pgtype.UUID        `json:"ended_by"`
	EndReason         string             `json:"end_reason"`
	BindingID         pgtype.UUID        `json:"binding_id"`
	RelayNodeID       pgtype.UUID        `json:"relay_node_id"`
	GatewayInstanceID pgtype.UUID        `json:"gateway_instance_id"`
	GatewayAccountID  int64              `json:"gateway_account_id"`
}

func (q *Queries) CloseCurrentRelayNodeGatewayAccountBinding(ctx context.Context, arg CloseCurrentRelayNodeGatewayAccountBindingParams) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, closeCurrentRelayNodeGatewayAccountBinding,
		arg.EndedAt,
		arg.EndedBy,
		arg.EndReason,
		arg.BindingID,
		arg.RelayNodeID,
		arg.GatewayInstanceID,
		arg.GatewayAccountID,
	)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const getCurrentRelayNodeGatewayAccountBindingByAccount = `-- name: GetCurrentRelayNodeGatewayAccountBindingByAccount :one
SELECT binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
FROM relay_node_gateway_account_bindings
WHERE gateway_instance_id = $1::uuid
  AND gateway_account_id = $2::bigint
  AND ended_at IS NULL
`

type GetCurrentRelayNodeGatewayAccountBindingByAccountParams struct {
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	GatewayAccountID  int64       `json:"gateway_account_id"`
}

func (q *Queries) GetCurrentRelayNodeGatewayAccountBindingByAccount(ctx context.Context, arg GetCurrentRelayNodeGatewayAccountBindingByAccountParams) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, getCurrentRelayNodeGatewayAccountBindingByAccount, arg.GatewayInstanceID, arg.GatewayAccountID)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const getCurrentRelayNodeGatewayAccountBindingByNode = `-- name: GetCurrentRelayNodeGatewayAccountBindingByNode :one
SELECT binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
FROM relay_node_gateway_account_bindings
WHERE relay_node_id = $1::uuid
  AND ended_at IS NULL
`

func (q *Queries) GetCurrentRelayNodeGatewayAccountBindingByNode(ctx context.Context, relayNodeID pgtype.UUID) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, getCurrentRelayNodeGatewayAccountBindingByNode, relayNodeID)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const getRelayBindingDBTime = `-- name: GetRelayBindingDBTime :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) GetRelayBindingDBTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getRelayBindingDBTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const insertOpenRelayNodeGatewayAccountBinding = `-- name: InsertOpenRelayNodeGatewayAccountBinding :one
INSERT INTO relay_node_gateway_account_bindings (
    relay_node_id,
    gateway_instance_id,
    gateway_account_id,
    evidence_snapshot_id,
    bound_at,
    bound_by,
    bind_reason
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::bigint,
    $4::uuid,
    $5::timestamptz,
    $6::uuid,
    $7::text
)
RETURNING binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
`

type InsertOpenRelayNodeGatewayAccountBindingParams struct {
	RelayNodeID        pgtype.UUID        `json:"relay_node_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	GatewayAccountID   int64              `json:"gateway_account_id"`
	EvidenceSnapshotID pgtype.UUID        `json:"evidence_snapshot_id"`
	BoundAt            pgtype.Timestamptz `json:"bound_at"`
	BoundBy            pgtype.UUID        `json:"bound_by"`
	BindReason         string             `json:"bind_reason"`
}

func (q *Queries) InsertOpenRelayNodeGatewayAccountBinding(ctx context.Context, arg InsertOpenRelayNodeGatewayAccountBindingParams) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, insertOpenRelayNodeGatewayAccountBinding,
		arg.RelayNodeID,
		arg.GatewayInstanceID,
		arg.GatewayAccountID,
		arg.EvidenceSnapshotID,
		arg.BoundAt,
		arg.BoundBy,
		arg.BindReason,
	)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const lockCurrentRelayNodeGatewayAccountBindingByNode = `-- name: LockCurrentRelayNodeGatewayAccountBindingByNode :one
SELECT binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
FROM relay_node_gateway_account_bindings
WHERE relay_node_id = $1::uuid
  AND ended_at IS NULL
FOR UPDATE
`

func (q *Queries) LockCurrentRelayNodeGatewayAccountBindingByNode(ctx context.Context, relayNodeID pgtype.UUID) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, lockCurrentRelayNodeGatewayAccountBindingByNode, relayNodeID)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}
