// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relay_node_gateway_account_bindings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCurrentRelayNodeGatewayAccountBinding = `-- name: CloseCurrentRelayNodeGatewayAccountBinding :one
UPDATE relay_node_gateway_account_bindings
SET ended_at = $1::timestamptz,
    ended_by = $2::uuid,
    end_reason = $3::text
WHERE binding_id = $4::uuid
  AND relay_node_id = $5::uuid
  AND gateway_instance_id = $6::uuid
  AND gateway_account_id = $7::bigint
  AND ended_at IS NULL
RETURNING binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
`

type CloseCurrentRelayNodeGatewayAccountBindingParams struct {
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	EndedBy           pgtype.UUID        `json:"ended_by"`
	EndReason         string             `json:"end_reason"`
	BindingID         pgtype.UUID        `json:"binding_id"`
	RelayNodeID       pgtype.UUID        `json:"relay_node_id"`
	GatewayInstanceID pgtype.UUID        `json:"gateway_instance_id"`
	GatewayAccountID  int64              `json:"gateway_account_id"`
}

func (q *Queries) CloseCurrentRelayNodeGatewayAccountBinding(ctx context.Context, arg CloseCurrentRelayNodeGatewayAccountBindingParams) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, closeCurrentRelayNodeGatewayAccountBinding,
		arg.EndedAt,
		arg.EndedBy,
		arg.EndReason,
		arg.BindingID,
		arg.RelayNodeID,
		arg.GatewayInstanceID,
		arg.GatewayAccountID,
	)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const getCurrentRelayNodeGatewayAccountBindingByAccount = `-- name: GetCurrentRelayNodeGatewayAccountBindingByAccount :one
SELECT binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
FROM relay_node_gateway_account_bindings
WHERE gateway_instance_id = $1::uuid
  AND gateway_account_id = $2::bigint
  AND ended_at IS NULL
`

type GetCurrentRelayNodeGatewayAccountBindingByAccountParams struct {
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	GatewayAccountID  int64       `json:"gateway_account_id"`
}

func (q *Queries) GetCurrentRelayNodeGatewayAccountBindingByAccount(ctx context.Context, arg GetCurrentRelayNodeGatewayAccountBindingByAccountParams) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, getCurrentRelayNodeGatewayAccountBindingByAccount, arg.GatewayInstanceID, arg.GatewayAccountID)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const getCurrentRelayNodeGatewayAccountBindingByNode = `-- name: GetCurrentRelayNodeGatewayAccountBindingByNode :one
SELECT binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
FROM relay_node_gateway_account_bindings
WHERE relay_node_id = $1::uuid
  AND ended_at IS NULL
`

func (q *Queries) GetCurrentRelayNodeGatewayAccountBindingByNode(ctx context.Context, relayNodeID pgtype.UUID) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, getCurrentRelayNodeGatewayAccountBindingByNode, relayNodeID)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const getGatewayDirectorySnapshotItem = `-- name: GetGatewayDirectorySnapshotItem :one
SELECT snapshot_id, account_id, name, platform, type, url, status
FROM gateway_directory_snapshot_items
WHERE snapshot_id = $1::uuid
  AND account_id = $2::bigint
`

type GetGatewayDirectorySnapshotItemParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	AccountID  int64       `json:"account_id"`
}

func (q *Queries) GetGatewayDirectorySnapshotItem(ctx context.Context, arg GetGatewayDirectorySnapshotItemParams) (GatewayDirectorySnapshotItem, error) {
	row := q.db.QueryRow(ctx, getGatewayDirectorySnapshotItem, arg.SnapshotID, arg.AccountID)
	var i GatewayDirectorySnapshotItem
	err := row.Scan(
		&i.SnapshotID,
		&i.AccountID,
		&i.Name,
		&i.Platform,
		&i.Type,
		&i.Url,
		&i.Status,
	)
	return i, err
}

const getNodeCentricBindingView = `-- name: GetNodeCentricBindingView :one
WITH db_now AS (
    SELECT clock_timestamp()::timestamptz AS db_now
)
SELECT
    node.instance_id AS relay_node_id,
    binding.binding_id,
    binding.gateway_instance_id,
    binding.gateway_account_id,
    binding.evidence_snapshot_id,
    binding.bound_at,
    binding.bound_by,
    binding.bind_reason,
    current_state.current_snapshot_id,
    current_state.last_success_received_at,
    current_item.account_id AS current_account_id,
    current_item.name AS current_name,
    current_item.platform AS current_platform,
    current_item.type AS current_type,
    current_item.url AS current_url,
    current_item.status AS current_status,
    evidence_item.account_id AS evidence_account_id,
    evidence_item.name AS evidence_name,
    evidence_item.platform AS evidence_platform,
    evidence_item.type AS evidence_type,
    evidence_item.url AS evidence_url,
    evidence_item.status AS evidence_status,
    db_now.db_now AS db_now
FROM relay_node_assets AS node
CROSS JOIN db_now
LEFT JOIN relay_node_gateway_account_bindings AS binding
    ON binding.relay_node_id = node.instance_id AND binding.ended_at IS NULL
LEFT JOIN gateway_directory_current_state AS current_state
    ON current_state.gateway_instance_id = binding.gateway_instance_id
LEFT JOIN gateway_directory_snapshot_items AS current_item
    ON current_item.snapshot_id = current_state.current_snapshot_id
    AND current_item.account_id = binding.gateway_account_id
LEFT JOIN gateway_directory_snapshot_items AS evidence_item
    ON evidence_item.snapshot_id = binding.evidence_snapshot_id
    AND evidence_item.account_id = binding.gateway_account_id
WHERE node.instance_id = $1::uuid
`

type GetNodeCentricBindingViewRow struct {
	RelayNodeID           pgtype.UUID        `json:"relay_node_id"`
	BindingID             pgtype.UUID        `json:"binding_id"`
	GatewayInstanceID     pgtype.UUID        `json:"gateway_instance_id"`
	GatewayAccountID      pgtype.Int8        `json:"gateway_account_id"`
	EvidenceSnapshotID    pgtype.UUID        `json:"evidence_snapshot_id"`
	BoundAt               pgtype.Timestamptz `json:"bound_at"`
	BoundBy               pgtype.UUID        `json:"bound_by"`
	BindReason            pgtype.Text        `json:"bind_reason"`
	CurrentSnapshotID     pgtype.UUID        `json:"current_snapshot_id"`
	LastSuccessReceivedAt pgtype.Timestamptz `json:"last_success_received_at"`
	CurrentAccountID      pgtype.Int8        `json:"current_account_id"`
	CurrentName           pgtype.Text        `json:"current_name"`
	CurrentPlatform       pgtype.Text        `json:"current_platform"`
	CurrentType           pgtype.Text        `json:"current_type"`
	CurrentUrl            pgtype.Text        `json:"current_url"`
	CurrentStatus         pgtype.Text        `json:"current_status"`
	EvidenceAccountID     pgtype.Int8        `json:"evidence_account_id"`
	EvidenceName          pgtype.Text        `json:"evidence_name"`
	EvidencePlatform      pgtype.Text        `json:"evidence_platform"`
	EvidenceType          pgtype.Text        `json:"evidence_type"`
	EvidenceUrl           pgtype.Text        `json:"evidence_url"`
	EvidenceStatus        pgtype.Text        `json:"evidence_status"`
	DbNow                 pgtype.Timestamptz `json:"db_now"`
}

func (q *Queries) GetNodeCentricBindingView(ctx context.Context, relayNodeID pgtype.UUID) (GetNodeCentricBindingViewRow, error) {
	row := q.db.QueryRow(ctx, getNodeCentricBindingView, relayNodeID)
	var i GetNodeCentricBindingViewRow
	err := row.Scan(
		&i.RelayNodeID,
		&i.BindingID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.CurrentSnapshotID,
		&i.LastSuccessReceivedAt,
		&i.CurrentAccountID,
		&i.CurrentName,
		&i.CurrentPlatform,
		&i.CurrentType,
		&i.CurrentUrl,
		&i.CurrentStatus,
		&i.EvidenceAccountID,
		&i.EvidenceName,
		&i.EvidencePlatform,
		&i.EvidenceType,
		&i.EvidenceUrl,
		&i.EvidenceStatus,
		&i.DbNow,
	)
	return i, err
}

const getRelayBindingDBTime = `-- name: GetRelayBindingDBTime :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) GetRelayBindingDBTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getRelayBindingDBTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const insertOpenRelayNodeGatewayAccountBinding = `-- name: InsertOpenRelayNodeGatewayAccountBinding :one
INSERT INTO relay_node_gateway_account_bindings (
    relay_node_id,
    gateway_instance_id,
    gateway_account_id,
    evidence_snapshot_id,
    bound_at,
    bound_by,
    bind_reason
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::bigint,
    $4::uuid,
    $5::timestamptz,
    $6::uuid,
    $7::text
)
RETURNING binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
`

type InsertOpenRelayNodeGatewayAccountBindingParams struct {
	RelayNodeID        pgtype.UUID        `json:"relay_node_id"`
	GatewayInstanceID  pgtype.UUID        `json:"gateway_instance_id"`
	GatewayAccountID   int64              `json:"gateway_account_id"`
	EvidenceSnapshotID pgtype.UUID        `json:"evidence_snapshot_id"`
	BoundAt            pgtype.Timestamptz `json:"bound_at"`
	BoundBy            pgtype.UUID        `json:"bound_by"`
	BindReason         string             `json:"bind_reason"`
}

func (q *Queries) InsertOpenRelayNodeGatewayAccountBinding(ctx context.Context, arg InsertOpenRelayNodeGatewayAccountBindingParams) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, insertOpenRelayNodeGatewayAccountBinding,
		arg.RelayNodeID,
		arg.GatewayInstanceID,
		arg.GatewayAccountID,
		arg.EvidenceSnapshotID,
		arg.BoundAt,
		arg.BoundBy,
		arg.BindReason,
	)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const listGatewayAccountCentricBindingViews = `-- name: ListGatewayAccountCentricBindingViews :many
WITH db_now AS (
    SELECT clock_timestamp()::timestamptz AS db_now
), target_gateway AS (
    SELECT instance_id
    FROM gateway_instances
    WHERE instance_id = $1::uuid
)
SELECT
    target_gateway.instance_id AS gateway_instance_id,
    current_state.current_snapshot_id,
    current_state.last_success_received_at,
    items.account_id AS gateway_account_id,
    items.name,
    items.platform,
    items.type,
    items.url,
    items.status,
    binding.binding_id,
    binding.relay_node_id,
    binding.evidence_snapshot_id,
    binding.bound_at,
    binding.bound_by,
    binding.bind_reason,
    db_now.db_now AS db_now
FROM target_gateway
CROSS JOIN db_now
LEFT JOIN gateway_directory_current_state AS current_state
    ON current_state.gateway_instance_id = target_gateway.instance_id
LEFT JOIN gateway_directory_snapshot_items AS items
    ON items.snapshot_id = current_state.current_snapshot_id
LEFT JOIN relay_node_gateway_account_bindings AS binding
    ON binding.gateway_instance_id = target_gateway.instance_id
    AND binding.gateway_account_id = items.account_id
    AND binding.ended_at IS NULL
ORDER BY items.account_id ASC
`

type ListGatewayAccountCentricBindingViewsRow struct {
	GatewayInstanceID     pgtype.UUID        `json:"gateway_instance_id"`
	CurrentSnapshotID     pgtype.UUID        `json:"current_snapshot_id"`
	LastSuccessReceivedAt pgtype.Timestamptz `json:"last_success_received_at"`
	GatewayAccountID      pgtype.Int8        `json:"gateway_account_id"`
	Name                  pgtype.Text        `json:"name"`
	Platform              pgtype.Text        `json:"platform"`
	Type                  pgtype.Text        `json:"type"`
	Url                   pgtype.Text        `json:"url"`
	Status                pgtype.Text        `json:"status"`
	BindingID             pgtype.UUID        `json:"binding_id"`
	RelayNodeID           pgtype.UUID        `json:"relay_node_id"`
	EvidenceSnapshotID    pgtype.UUID        `json:"evidence_snapshot_id"`
	BoundAt               pgtype.Timestamptz `json:"bound_at"`
	BoundBy               pgtype.UUID        `json:"bound_by"`
	BindReason            pgtype.Text        `json:"bind_reason"`
	DbNow                 pgtype.Timestamptz `json:"db_now"`
}

func (q *Queries) ListGatewayAccountCentricBindingViews(ctx context.Context, gatewayInstanceID pgtype.UUID) ([]ListGatewayAccountCentricBindingViewsRow, error) {
	rows, err := q.db.Query(ctx, listGatewayAccountCentricBindingViews, gatewayInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayAccountCentricBindingViewsRow{}
	for rows.Next() {
		var i ListGatewayAccountCentricBindingViewsRow
		if err := rows.Scan(
			&i.GatewayInstanceID,
			&i.CurrentSnapshotID,
			&i.LastSuccessReceivedAt,
			&i.GatewayAccountID,
			&i.Name,
			&i.Platform,
			&i.Type,
			&i.Url,
			&i.Status,
			&i.BindingID,
			&i.RelayNodeID,
			&i.EvidenceSnapshotID,
			&i.BoundAt,
			&i.BoundBy,
			&i.BindReason,
			&i.DbNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedGatewayAccountBindings = `-- name: ListUnresolvedGatewayAccountBindings :many
WITH db_now AS (
    SELECT clock_timestamp()::timestamptz AS db_now
), target_gateway AS (
    SELECT instance_id
    FROM gateway_instances
    WHERE instance_id = $1::uuid
)
SELECT
    binding.binding_id,
    binding.relay_node_id,
    binding.gateway_instance_id,
    binding.gateway_account_id,
    binding.evidence_snapshot_id,
    binding.bound_at,
    binding.bound_by,
    binding.bind_reason,
    current_state.current_snapshot_id,
    current_state.last_success_received_at,
    evidence_item.name AS evidence_name,
    evidence_item.platform AS evidence_platform,
    evidence_item.type AS evidence_type,
    evidence_item.url AS evidence_url,
    evidence_item.status AS evidence_status,
    db_now.db_now AS db_now
FROM target_gateway
CROSS JOIN db_now
JOIN gateway_directory_current_state AS current_state
    ON current_state.gateway_instance_id = target_gateway.instance_id
JOIN relay_node_gateway_account_bindings AS binding
    ON binding.gateway_instance_id = target_gateway.instance_id
    AND binding.ended_at IS NULL
LEFT JOIN gateway_directory_snapshot_items AS current_item
    ON current_item.snapshot_id = current_state.current_snapshot_id
    AND current_item.account_id = binding.gateway_account_id
LEFT JOIN gateway_directory_snapshot_items AS evidence_item
    ON evidence_item.snapshot_id = binding.evidence_snapshot_id
    AND evidence_item.account_id = binding.gateway_account_id
WHERE current_item.account_id IS NULL
ORDER BY binding.gateway_account_id ASC, binding.relay_node_id ASC
`

type ListUnresolvedGatewayAccountBindingsRow struct {
	BindingID             pgtype.UUID        `json:"binding_id"`
	RelayNodeID           pgtype.UUID        `json:"relay_node_id"`
	GatewayInstanceID     pgtype.UUID        `json:"gateway_instance_id"`
	GatewayAccountID      int64              `json:"gateway_account_id"`
	EvidenceSnapshotID    pgtype.UUID        `json:"evidence_snapshot_id"`
	BoundAt               pgtype.Timestamptz `json:"bound_at"`
	BoundBy               pgtype.UUID        `json:"bound_by"`
	BindReason            string             `json:"bind_reason"`
	CurrentSnapshotID     pgtype.UUID        `json:"current_snapshot_id"`
	LastSuccessReceivedAt pgtype.Timestamptz `json:"last_success_received_at"`
	EvidenceName          pgtype.Text        `json:"evidence_name"`
	EvidencePlatform      pgtype.Text        `json:"evidence_platform"`
	EvidenceType          pgtype.Text        `json:"evidence_type"`
	EvidenceUrl           pgtype.Text        `json:"evidence_url"`
	EvidenceStatus        pgtype.Text        `json:"evidence_status"`
	DbNow                 pgtype.Timestamptz `json:"db_now"`
}

func (q *Queries) ListUnresolvedGatewayAccountBindings(ctx context.Context, gatewayInstanceID pgtype.UUID) ([]ListUnresolvedGatewayAccountBindingsRow, error) {
	rows, err := q.db.Query(ctx, listUnresolvedGatewayAccountBindings, gatewayInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnresolvedGatewayAccountBindingsRow{}
	for rows.Next() {
		var i ListUnresolvedGatewayAccountBindingsRow
		if err := rows.Scan(
			&i.BindingID,
			&i.RelayNodeID,
			&i.GatewayInstanceID,
			&i.GatewayAccountID,
			&i.EvidenceSnapshotID,
			&i.BoundAt,
			&i.BoundBy,
			&i.BindReason,
			&i.CurrentSnapshotID,
			&i.LastSuccessReceivedAt,
			&i.EvidenceName,
			&i.EvidencePlatform,
			&i.EvidenceType,
			&i.EvidenceUrl,
			&i.EvidenceStatus,
			&i.DbNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCurrentRelayNodeGatewayAccountBindingByAccount = `-- name: LockCurrentRelayNodeGatewayAccountBindingByAccount :one
SELECT binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
FROM relay_node_gateway_account_bindings
WHERE gateway_instance_id = $1::uuid
  AND gateway_account_id = $2::bigint
  AND ended_at IS NULL
FOR UPDATE
`

type LockCurrentRelayNodeGatewayAccountBindingByAccountParams struct {
	GatewayInstanceID pgtype.UUID `json:"gateway_instance_id"`
	GatewayAccountID  int64       `json:"gateway_account_id"`
}

func (q *Queries) LockCurrentRelayNodeGatewayAccountBindingByAccount(ctx context.Context, arg LockCurrentRelayNodeGatewayAccountBindingByAccountParams) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, lockCurrentRelayNodeGatewayAccountBindingByAccount, arg.GatewayInstanceID, arg.GatewayAccountID)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const lockCurrentRelayNodeGatewayAccountBindingByNode = `-- name: LockCurrentRelayNodeGatewayAccountBindingByNode :one
SELECT binding_id, relay_node_id, gateway_instance_id, gateway_account_id, evidence_snapshot_id, bound_at, bound_by, bind_reason, ended_at, ended_by, end_reason
FROM relay_node_gateway_account_bindings
WHERE relay_node_id = $1::uuid
  AND ended_at IS NULL
FOR UPDATE
`

func (q *Queries) LockCurrentRelayNodeGatewayAccountBindingByNode(ctx context.Context, relayNodeID pgtype.UUID) (RelayNodeGatewayAccountBinding, error) {
	row := q.db.QueryRow(ctx, lockCurrentRelayNodeGatewayAccountBindingByNode, relayNodeID)
	var i RelayNodeGatewayAccountBinding
	err := row.Scan(
		&i.BindingID,
		&i.RelayNodeID,
		&i.GatewayInstanceID,
		&i.GatewayAccountID,
		&i.EvidenceSnapshotID,
		&i.BoundAt,
		&i.BoundBy,
		&i.BindReason,
		&i.EndedAt,
		&i.EndedBy,
		&i.EndReason,
	)
	return i, err
}

const lockGatewayAssetForBinding = `-- name: LockGatewayAssetForBinding :one
SELECT instance_id, lifecycle_status, singleton_id
FROM gateway_instances
WHERE instance_id = $1::uuid
FOR UPDATE
`

type LockGatewayAssetForBindingRow struct {
	InstanceID      pgtype.UUID `json:"instance_id"`
	LifecycleStatus string      `json:"lifecycle_status"`
	SingletonID     pgtype.Int2 `json:"singleton_id"`
}

func (q *Queries) LockGatewayAssetForBinding(ctx context.Context, instanceID pgtype.UUID) (LockGatewayAssetForBindingRow, error) {
	row := q.db.QueryRow(ctx, lockGatewayAssetForBinding, instanceID)
	var i LockGatewayAssetForBindingRow
	err := row.Scan(&i.InstanceID, &i.LifecycleStatus, &i.SingletonID)
	return i, err
}

const lockGatewayDirectoryCurrentState = `-- name: LockGatewayDirectoryCurrentState :one
SELECT gateway_instance_id, current_snapshot_id, current_content_fingerprint, last_success_received_at, last_source_generated_at, last_success_run_id, updated_at
FROM gateway_directory_current_state
WHERE gateway_instance_id = $1::uuid
FOR UPDATE
`

func (q *Queries) LockGatewayDirectoryCurrentState(ctx context.Context, gatewayInstanceID pgtype.UUID) (GatewayDirectoryCurrentState, error) {
	row := q.db.QueryRow(ctx, lockGatewayDirectoryCurrentState, gatewayInstanceID)
	var i GatewayDirectoryCurrentState
	err := row.Scan(
		&i.GatewayInstanceID,
		&i.CurrentSnapshotID,
		&i.CurrentContentFingerprint,
		&i.LastSuccessReceivedAt,
		&i.LastSourceGeneratedAt,
		&i.LastSuccessRunID,
		&i.UpdatedAt,
	)
	return i, err
}

const lockRelayNodeAssetForBinding = `-- name: LockRelayNodeAssetForBinding :one
SELECT instance_id
FROM relay_node_assets
WHERE instance_id = $1::uuid
FOR UPDATE
`

func (q *Queries) LockRelayNodeAssetForBinding(ctx context.Context, instanceID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockRelayNodeAssetForBinding, instanceID)
	var instance_id pgtype.UUID
	err := row.Scan(&instance_id)
	return instance_id, err
}
