#!/bin/sh
set -eu

: "${CONTROL_COMPAT_GATE:?CONTROL_COMPAT_GATE is required}"
: "${CONTROL_ARTIFACT:?CONTROL_ARTIFACT is required}"
: "${CONTROL_COMPAT_MANIFEST:?CONTROL_COMPAT_MANIFEST is required}"
: "${CONTROL_COMPAT_PUBLIC_KEY:?CONTROL_COMPAT_PUBLIC_KEY is required}"

exec "$CONTROL_COMPAT_GATE" \
  --manifest "$CONTROL_COMPAT_MANIFEST" \
  --public-key "$CONTROL_COMPAT_PUBLIC_KEY" \
  --artifact "$CONTROL_ARTIFACT" \
  --database-url-env "${CONTROL_COMPAT_DATABASE_URL_ENV:-DATABASE_URL}" \
  -- "$CONTROL_ARTIFACT" "$@"
