const canonicalTranslation = {
  common: {
    locale: {
      label: "语言",
    },
    readState: {
      loading: "加载中",
      unavailable: "暂不可用",
      empty: "暂无记录",
      retry: "重试",
    },
    shell: {
      authLoading: "正在读取安全状态",
      routeLoading: "正在加载页面",
      authUnavailable: "Control 认证服务暂时不可用",
      authUnavailableDescription: "管理面已安全关闭；请检查 Control 与 PostgreSQL 状态。",
    },
  },
  management: {
    title: "Relay Station Control",
    sessionDescription: "{{displayName}} · {{loginName}}",
    navJobs: "持久任务",
    navAssets: "资产注册表",
    navTopology: "Node Topology",
    navProblems: "Problems",
    logout: "注销",
    csrfInvalid: "安全凭据已刷新。为避免重复执行，本次操作没有自动重放，请确认状态后重试。",
    reauthenticationRequired: "此操作需要先在“重新认证”页签验证密码与 MFA，证明有效期为 5 分钟。",
    reauthenticationSuccess: "重新认证成功，高风险操作窗口已开启 5 分钟。",
    passwordChanged: "密码已修改，其他会话已撤销。",
    administratorDisabled: "管理员已禁用，其会话与未使用令牌均已撤销。",
    highRiskValidUntil: "重新认证有效至 {{date}}",
    highRiskLocked: "高风险操作当前锁定",
    tabs: { session: "会话", reauth: "重新认证", password: "修改密码", admins: "管理员", recovery: "恢复码" },
    session: {
      current: "当前会话",
      idleUntil: "空闲到期：{{date}}",
      absoluteUntil: "绝对到期：{{date}}",
      mfa: "MFA：{{value}}",
      completed: "已完成",
      incomplete: "未完成",
      recoveryRemaining: "剩余恢复码：{{count}}",
      refresh: "刷新会话与 CSRF",
    },
    reauth: { currentPassword: "当前密码", mfaMethod: "MFA 方式", mfaCode: "MFA 验证码", submit: "重新认证" },
    password: { current: "当前密码", next: "新密码", mfaMethod: "MFA 方式", mfaCode: "MFA 验证码", submit: "修改密码并轮换会话" },
    admins: {
      loginName: "登录名", displayName: "实名", createDisplayName: "实名显示名", role: "角色", status: "状态", lastLogin: "最近登录",
      createTitle: "创建待激活管理员", reason: "操作原因", create: "创建并显示一次性令牌",
      actionTitle: "对选中管理员执行高风险操作", reasonPlaceholder: "操作原因（10–500 字符）",
      disable: "禁用", disableConfirmTitle: "确认禁用管理员？", disableConfirmContent: "目标的全部会话与未使用令牌将被撤销。",
      token: "重新生成激活令牌", resetMfa: "重置 MFA", resetConfirmTitle: "确认重置 MFA？", resetConfirmContent: "目标将回到待激活状态并失去现有会话。",
    },
    recovery: {
      description: "重新生成会立即撤销全部旧恢复码，新码只显示一次。",
      regenerate: "重新生成恢复码", confirmTitle: "重新生成恢复码？", confirmContent: "所有旧恢复码将立即失效。",
    },
  },
  assets: {
    title: "资产注册表",
    description: "Gateway 生命周期管理与资产状态视图",
    management: "管理员控制台",
    environment: "环境",
    gateway: "Gateway",
    policy: "当前 Provider 策略",
    drivers: "Driver 与 capability",
    nodes: "Relay Node",
    readFailed: "读取失败",
    unavailable: "当前数据不可用；未显示旧数据或内部错误。",
    retry: "重试",
    emptyGateway: "尚未登记 Gateway",
    emptyDriver: "尚未登记 Driver",
    selectDriver: "请先登记 Driver",
    emptyPolicy: "尚未配置当前 Provider 策略",
    emptyNodes: "当前过滤条件下没有 Relay Node",
  },
  topology: {
    title: "Node Topology",
    description: "Node 及其只读关联观察",
    management: "管理员控制台",
  },
  operations: {
    guidance: "操作只提交逻辑账号身份；物理目标由服务端基于最新 Node 快照选择。",
    applied: "已应用", noop: "无需变更", unknown: "远端结果不确定", failed: "执行失败",
    unknownTitle: "执行结果未知", unknownDescription: "请求可能已被远端应用，也可能未应用。系统不会自动重试，以避免重复操作。请结合当前账户状态人工判断后再决定是否发起新的命令。",
    commandId: "Command ID", operation: "操作", executionState: "执行状态", resultError: "结果/错误", created: "创建时间", updated: "更新时间",
    disable: "Disable", enable: "Enable", remove: "Remove", uploadNew: "Upload New", replaceExisting: "Replace Existing",
    removeTitle: "确认移除此账户？", removeDescription: "该操作会删除 Node 上对应的单个凭据文件，无法由 Control 自动恢复。", confirmRemove: "确认移除",
    replaceTitle: "确认替换现有凭据？", replaceDescription: "Replace 使用远端原生的尽力而为、后写入覆盖语义。", confirmReplace: "确认替换",
    lookupPlaceholder: "输入 Command ID 查看操作结果", read: "读取操作", unknownOverride: "未知结果 Override", overrideType: "Override 类型", overrideReason: "Override reason", overrideDetail: "Override detail", optionalDetail: "可选说明", submitOverride: "执行 Override", confirmOverride: "确认 Override",
    uploadAccount: "Upload New Account", uploadDescription: "无需已有 Inventory 账号。服务端会根据逻辑身份生成并验证远端目标。", uploadProvider: "Upload New Provider", uploadEmail: "Upload New Email", accountEmail: "账户邮箱", chooseCredential: "选择 credential JSON（最大 1 MiB）",
    credentialTooLarge: "凭据文件不能超过 1 MiB", keep: "Keep existing", set: "Set new credential", clear: "Clear credential",
  },
  auth: {
    errors: {
      unavailable: "请求暂时无法完成，请稍后再试。",
      rateLimited: "尝试次数过多，请稍后再试。",
      challengeExpired: "验证已过期，请重新登录。",
      lastAdministratorProtected: "不能禁用最后一个可用管理员。",
      selfDisableForbidden: "不能禁用当前登录账号。",
      reauthenticationRequired: "请先完成重新认证。",
      unauthorized: "认证失败，请检查输入后重试。",
      csrfInvalid: "安全凭据已变化，请刷新会话后重试。",
      requestIncomplete: "请求未完成（请求 ID：{{requestId}}）",
    },
    login: {
      title: "管理员登录",
      securityHint: "所有认证失败使用统一提示，不确认账号状态。",
      loginName: "登录名",
      password: "密码",
      continue: "继续",
      activationLink: "使用激活令牌设置新账号",
      mfaRequired: "需要第二步验证",
      challengeValidUntil: "挑战有效至 {{date}}",
      totp: "TOTP 验证码",
      totpMethod: "TOTP",
      recoveryCode: "恢复码",
      verify: "验证并登录",
      backToPassword: "返回密码登录",
      recoveryWarning: "恢复码成功使用后将立即失效；登录后请检查剩余数量。",
      expired: "验证已过期，请重新登录。",
    },
    bootstrap: {
      title: "初始化 Control",
      inProgress: "存在未完成的初始化，请重新输入相同资料继续，或使用运行时 Secret 重置。",
      newInstallation: "创建首个实名超级管理员。",
      secret: "运行时 Bootstrap Secret",
      loginName: "登录名",
      displayName: "实名显示名",
      password: "密码",
      start: "开始或继续初始化",
      resetPending: "重置未完成流程",
      addAuthenticator: "请立即添加到认证器",
      totpMemoryOnly: "此 TOTP 配置仅在当前页面内存中保留。",
      copyUri: "复制 TOTP 配置 URI",
      confirm: "确认并永久完成",
      reset: "重置",
      totpCode: "TOTP 验证码",
    },
    activation: {
      title: "激活管理员账号",
      tokenHint: "请手工粘贴令牌。页面不会从 URL、历史记录或浏览器存储读取令牌。",
      token: "一次性激活令牌",
      start: "开始激活",
      newPassword: "新密码",
      totpCode: "TOTP 验证码",
      complete: "完成激活",
      backToLogin: "返回登录",
      leaveHint: "离开此页后不会保留。",
    },
    oneTime: {
      recoveryTitle: "保存恢复码",
      activationTitle: "复制激活令牌",
      onlyShownOnce: "只显示这一次",
      recoveryDescription: "每个恢复码只能使用一次。请保存到密码管理器或离线安全位置。",
      activationDescription: "令牌只应通过可信渠道交给对应管理员，禁止放入 URL。",
      validUntil: "有效至 {{date}}",
      confirmation: "我已安全保存，理解离开后无法再次查看",
      leave: "确认并离开",
      noCache: "本页设置禁止缓存；离开时材料会从应用内存移除。",
    },
  },
} as const;

type LeafKeys<T> = {
  [Key in keyof T & string]: T[Key] extends Record<string, unknown>
    ? `${Key}.${LeafKeys<T[Key]>}`
    : Key;
}[keyof T & string];

type ResourceShape<T> = {
  [Key in keyof T]: T[Key] extends Record<string, unknown> ? ResourceShape<T[Key]> : string;
};

export type TranslationKey = LeafKeys<typeof canonicalTranslation>;
export type TranslationResource = ResourceShape<typeof canonicalTranslation>;

export const resources = {
  "zh-CN": {
    translation: canonicalTranslation,
  },
  en: {
    translation: {
      common: {
        locale: {
          label: "Language",
        },
        readState: {
          loading: "Loading",
          unavailable: "Unavailable",
          empty: "No records",
          retry: "Retry",
        },
        shell: {
          authLoading: "Reading security state",
          routeLoading: "Loading page",
          authUnavailable: "Control authentication service is temporarily unavailable",
          authUnavailableDescription: "The management surface is safely closed; check Control and PostgreSQL status.",
        },
      },
      management: {
        title: "Relay Station Control",
        sessionDescription: "{{displayName}} · {{loginName}}",
        navJobs: "Persistent jobs",
        navAssets: "Asset registry",
        navTopology: "Node Topology",
        navProblems: "Problems",
        logout: "Sign out",
        csrfInvalid: "The security credential was refreshed. This operation was not replayed; confirm the state and try again.",
        reauthenticationRequired: "Complete reauthentication in the Reauthentication tab first; it is valid for 5 minutes.",
        reauthenticationSuccess: "Reauthentication succeeded. The high-risk operation window is open for 5 minutes.",
        passwordChanged: "The password changed and other sessions were revoked.",
        administratorDisabled: "The administrator was disabled; its sessions and unused tokens were revoked.",
        highRiskValidUntil: "Reauthentication valid until {{date}}",
        highRiskLocked: "High-risk operations are currently locked",
        tabs: { session: "Session", reauth: "Reauthentication", password: "Change password", admins: "Administrators", recovery: "Recovery codes" },
        session: {
          current: "Current session", idleUntil: "Idle expiry: {{date}}", absoluteUntil: "Absolute expiry: {{date}}",
          mfa: "MFA: {{value}}", completed: "complete", incomplete: "incomplete", recoveryRemaining: "Recovery codes remaining: {{count}}", refresh: "Refresh session and CSRF",
        },
        reauth: { currentPassword: "Current password", mfaMethod: "MFA method", mfaCode: "MFA code", submit: "Reauthenticate" },
        password: { current: "Current password", next: "New password", mfaMethod: "MFA method", mfaCode: "MFA code", submit: "Change password and rotate sessions" },
        admins: {
          loginName: "Login name", displayName: "Name", createDisplayName: "Display name", role: "Role", status: "Status", lastLogin: "Last login",
          createTitle: "Create pending administrator", reason: "Reason", create: "Create and show one-time token",
          actionTitle: "Run high-risk operation on selected administrator", reasonPlaceholder: "Reason (10–500 characters)",
          disable: "Disable", disableConfirmTitle: "Disable administrator?", disableConfirmContent: "All sessions and unused tokens for this target will be revoked.",
          token: "Regenerate activation token", resetMfa: "Reset MFA", resetConfirmTitle: "Reset MFA?", resetConfirmContent: "The target will return to pending activation and lose its current sessions.",
        },
        recovery: {
          description: "Regenerating codes immediately revokes all previous codes. The new codes are shown once.",
          regenerate: "Regenerate recovery codes", confirmTitle: "Regenerate recovery codes?", confirmContent: "All previous recovery codes will immediately become invalid.",
        },
      },
      assets: {
        title: "Asset registry",
        description: "Gateway lifecycle management and asset state view",
        management: "Management console",
        environment: "Environment",
        gateway: "Gateway",
        policy: "Current provider policy",
        drivers: "Driver and capabilities",
        nodes: "Relay Node",
        readFailed: "Failed to read",
        unavailable: "The current data is unavailable; stale data and internal errors are not shown.",
        retry: "Retry",
        emptyGateway: "No Gateway registered",
        emptyDriver: "No Driver registered",
        selectDriver: "Register a Driver first",
        emptyPolicy: "No current provider policy configured",
        emptyNodes: "No Relay Node matches the current filters",
      },
      topology: {
        title: "Node Topology",
        description: "Read-only observation of Nodes and their relationships",
        management: "Management console",
      },
      operations: {
        guidance: "Operations submit only the logical account identity; the server selects the physical target from the latest Node snapshot.",
        applied: "Applied", noop: "No change", unknown: "Remote outcome unknown", failed: "Failed",
        unknownTitle: "Outcome unknown", unknownDescription: "The request may or may not have been applied remotely. The system will not retry automatically to avoid duplicate operations. Inspect the current account state before issuing a new command.",
        commandId: "Command ID", operation: "Operation", executionState: "Execution state", resultError: "Result/error", created: "Created", updated: "Updated",
        disable: "Disable", enable: "Enable", remove: "Remove", uploadNew: "Upload New", replaceExisting: "Replace Existing",
        removeTitle: "Remove this account?", removeDescription: "This deletes the corresponding single credential file on the Node; Control cannot restore it automatically.", confirmRemove: "Confirm removal",
        replaceTitle: "Replace the existing credential?", replaceDescription: "Replace uses the remote native best-effort, last-write-wins overwrite semantics.", confirmReplace: "Confirm replacement",
        lookupPlaceholder: "Enter a Command ID to view the operation result", read: "Read operation", unknownOverride: "Outcome unknown override", overrideType: "Override type", overrideReason: "Override reason", overrideDetail: "Override detail", optionalDetail: "Optional detail", submitOverride: "Run override", confirmOverride: "Confirm override",
        uploadAccount: "Upload New Account", uploadDescription: "No existing Inventory account is required. The server generates and validates the remote target from the logical identity.", uploadProvider: "Upload New Provider", uploadEmail: "Upload New Email", accountEmail: "Account email", chooseCredential: "Choose credential JSON (max 1 MiB)",
        credentialTooLarge: "Credential file cannot exceed 1 MiB", keep: "Keep existing", set: "Set new credential", clear: "Clear credential",
      },
      auth: {
        errors: {
          unavailable: "The request could not be completed. Try again later.",
          rateLimited: "Too many attempts. Try again later.",
          challengeExpired: "The verification expired. Sign in again.",
          lastAdministratorProtected: "The last available administrator cannot be disabled.",
          selfDisableForbidden: "The current signed-in account cannot be disabled.",
          reauthenticationRequired: "Complete reauthentication first.",
          unauthorized: "Authentication failed. Check the input and try again.",
          csrfInvalid: "The security credential changed. Refresh the session and try again.",
          requestIncomplete: "The request was not completed (request ID: {{requestId}})",
        },
        login: {
          title: "Administrator sign in",
          securityHint: "All authentication failures use one response and do not confirm account state.",
          loginName: "Login name",
          password: "Password",
          continue: "Continue",
          activationLink: "Set up a new account with an activation token",
          mfaRequired: "Second-step verification required",
          challengeValidUntil: "Challenge valid until {{date}}",
          totp: "TOTP code",
          totpMethod: "TOTP",
          recoveryCode: "Recovery code",
          verify: "Verify and sign in",
          backToPassword: "Back to password sign-in",
          recoveryWarning: "A recovery code becomes invalid after use; check the remaining count after sign-in.",
          expired: "The verification expired. Sign in again.",
        },
        bootstrap: {
          title: "Initialize Control",
          inProgress: "An incomplete initialization exists. Enter the same details to continue, or reset it with the runtime Secret.",
          newInstallation: "Create the first named super administrator.",
          secret: "Runtime Bootstrap Secret",
          loginName: "Login name",
          displayName: "Display name",
          password: "Password",
          start: "Start or continue initialization",
          resetPending: "Reset incomplete flow",
          addAuthenticator: "Add this to an authenticator now",
          totpMemoryOnly: "This TOTP configuration remains only in page memory.",
          copyUri: "Copy TOTP configuration URI",
          confirm: "Confirm and complete permanently",
          reset: "Reset",
          totpCode: "TOTP code",
        },
        activation: {
          title: "Activate administrator account",
          tokenHint: "Paste the token manually. The page never reads it from the URL, history, or browser storage.",
          token: "One-time activation token",
          start: "Start activation",
          newPassword: "New password",
          totpCode: "TOTP code",
          complete: "Complete activation",
          backToLogin: "Back to sign-in",
          leaveHint: "It will not be retained after leaving this page.",
        },
        oneTime: {
          recoveryTitle: "Save recovery codes",
          activationTitle: "Copy activation token",
          onlyShownOnce: "Shown only once",
          recoveryDescription: "Each recovery code can be used once. Save them in a password manager or another secure offline location.",
          activationDescription: "Give the token only to the intended administrator through a trusted channel; never put it in a URL.",
          validUntil: "Valid until {{date}}",
          confirmation: "I saved it securely and understand it cannot be viewed again after leaving",
          leave: "Confirm and leave",
          noCache: "This page is configured not to cache; leaving removes the material from application memory.",
        },
      },
    } satisfies TranslationResource,
  },
} satisfies Record<"zh-CN" | "en", { translation: TranslationResource }>;
