const stage3TopologyZh = {
  provider: "Provider", relayNode: "Relay Node", nodeFirstPage: "Node 首页", nodeNextPage: "下一页 Node", evidenceFirstPage: "Evidence 首页", evidenceNextPage: "Evidence 下一页",
  readUnavailable: "读取不可用（unavailable）", retry: "重试", evidenceNote: "Evidence 记录 authoritative evaluation 涉及关系，不等于历史 confirmed owner。", node: "Node", type: "类型", sourceTime: "来源时间", evaluationTime: "评估时间", recordedTime: "记录时间", firstPage: "首页", nextPage: "下一页", empty: "当前没有登记 Node", selectNode: "选择 Relay Node", nodeListUnavailable: "Node 清单读取不可用", nodeNotFound: "Node 不存在", nodeReadUnavailable: "Node 读取不可用", inventoryEvidence: "Inventory evidence", instanceId: "Instance ID", monitoring: "监控", accountQuality: "账号清单与质量", providerExact: "Provider 精确筛选", providerPlaceholder: "Provider（精确）", lifecycle: "质量生命周期", allLifecycle: "全部生命周期", basicStatus: "最后报告基础状态", allBasicStatus: "全部基础状态", emailExact: "邮箱精确筛选", emailPlaceholder: "邮箱（精确匹配）", qualityWindow: "质量窗口", recent15m: "最近 15 分钟", recent1h: "最近 1 小时", quality: "质量分类", allQuality: "全部质量", good: "Good", degraded: "Degraded", bad: "Bad", unknown: "Unknown", perPage: "每页账号数", pageSuffix: " / 页", query: "查询", readingQuality: "正在读取账号质量", noAccounts: "没有 Inventory 账号或匹配账号", previousAccounts: "账号上一页", nextAccounts: "账号下一页", noInstance: "请选择 Node 查看只读拓扑", providerSnapshot: "Provider snapshot 与 latest health", refreshProvider: "刷新 Provider", observedAt: "来源时间", noProviders: "没有应监控或已持有 state 的 Provider", monitoringScope: "监控范围", snapshot: "Snapshot", health: "Health", notYetObserved: "not-yet-observed", normal: "normal", reason: "原因", gatewayContext: "Gateway Usage Context", refreshBinding: "刷新 Binding", bindingTruth: "Binding truth", bindingResolution: "Binding resolution", directoryFreshness: "Directory freshness", contextSource: "Context source", gateway: "Gateway", accountId: "Account ID", accountContext: "Account context", boundAt: "绑定时间", lastSuccess: "最近成功观测", observedTime: "观察时间", ownershipCurrent: "Ownership Fact · 当前 duplicate", refreshCurrent: "刷新 Current", ownershipHistory: "Ownership Fact · 历史评估涉及", historyStatus: "历史状态", historyPlaceholder: "History 全部状态", refreshHistory: "刷新 History", historicalInvolvement: "historical involvement", emptyOccurrence: "没有符合条件的 occurrence", current: "current", affectedNodes: "当前 affected Nodes", emptySet: "当前集合为空", account: "账号", statusSeverity: "状态 / 严重度", evidenceHealth: "Evidence health", latestVerified: "最近完整验证", recentObservation: "最近观察 / 恢复", freshness: "Snapshot freshness", latestSnapshot: "最近完整快照", healthObservation: "健康观测", unavailableAccountList: "Control 暂时无法读取账号清单。", invalidAccountFilter: "筛选条件或分页凭据无效，请清除筛选并重新查询。", forbiddenAccountList: "当前会话无权读取账号清单。", unsupportedAccountList: "所选 Node 不支持账号清单查询。"
} as const;
const stage3TopologyEn = {
  provider: "Provider", relayNode: "Relay Node", nodeFirstPage: "Node first page", nodeNextPage: "Node next page", evidenceFirstPage: "Evidence first page", evidenceNextPage: "Evidence next page",
  readUnavailable: "Unavailable", retry: "Retry", evidenceNote: "Evidence records authoritative relationship evaluation; it is not historical confirmed ownership.", node: "Node", type: "Type", sourceTime: "Source time", evaluationTime: "Evaluation time", recordedTime: "Recorded time", firstPage: "First page", nextPage: "Next page", empty: "No Node is registered", selectNode: "Select Relay Node", nodeListUnavailable: "Node list unavailable", nodeNotFound: "Node not found", nodeReadUnavailable: "Node unavailable", inventoryEvidence: "Inventory evidence", instanceId: "Instance ID", monitoring: "Monitoring", accountQuality: "Account inventory and quality", providerExact: "Filter Provider exactly", providerPlaceholder: "Provider (exact)", lifecycle: "Quality lifecycle", allLifecycle: "All lifecycles", basicStatus: "Last reported basic status", allBasicStatus: "All basic statuses", emailExact: "Filter email exactly", emailPlaceholder: "Email (exact match)", qualityWindow: "Quality window", recent15m: "Last 15 minutes", recent1h: "Last hour", quality: "Quality", allQuality: "All quality", good: "Good", degraded: "Degraded", bad: "Bad", unknown: "Unknown", perPage: "Accounts per page", pageSuffix: " / page", query: "Query", readingQuality: "Reading account quality", noAccounts: "No Inventory account matches", previousAccounts: "Previous accounts", nextAccounts: "Next accounts", noInstance: "Select a Node to view read-only topology", providerSnapshot: "Provider snapshot and latest health", refreshProvider: "Refresh Provider", observedAt: "Observed at", noProviders: "No monitored or state-bearing Provider", monitoringScope: "Monitoring scope", snapshot: "Snapshot", health: "Health", notYetObserved: "not-yet-observed", normal: "normal", reason: "Reason", gatewayContext: "Gateway Usage Context", refreshBinding: "Refresh Binding", bindingTruth: "Binding truth", bindingResolution: "Binding resolution", directoryFreshness: "Directory freshness", contextSource: "Context source", gateway: "Gateway", accountId: "Account ID", accountContext: "Account context", boundAt: "Bound at", lastSuccess: "Last successful observation", observedTime: "Observed at", ownershipCurrent: "Ownership Fact · current duplicate", refreshCurrent: "Refresh Current", ownershipHistory: "Ownership Fact · historical involvement", historyStatus: "History status", historyPlaceholder: "All history statuses", refreshHistory: "Refresh History", historicalInvolvement: "historical involvement", emptyOccurrence: "No matching occurrence", current: "current", affectedNodes: "Affected Nodes", emptySet: "The current set is empty", account: "Account", statusSeverity: "Status / severity", evidenceHealth: "Evidence health", latestVerified: "Latest complete verification", recentObservation: "Recent observation / recovery", freshness: "Snapshot freshness", latestSnapshot: "Latest complete snapshot", healthObservation: "Health observation", unavailableAccountList: "Control cannot read the account list right now.", invalidAccountFilter: "The filter or pagination credential is invalid. Clear the filters and query again.", forbiddenAccountList: "The current session cannot read the account list.", unsupportedAccountList: "The selected Node does not support account-list queries."
} as const;
const stage3AccountsZh = {
  node: "节点", model: "模型", time: "时间", result: "结果", failure: "失败", latency: "延迟", requestId: "请求 ID", requestHistoryCard: "账号请求历史", unselectedHistory: "请选择账号查看请求历史", noHistory: "最近 7 天暂无请求历史", severity: "严重度", confirmed: "确认时间",
  account: "账号", provider: "Provider", status: "状态", quality: "质量", good: "良好", degraded: "降级", bad: "异常", unknown: "未知", availability: "可用性", reason: "原因", since: "自", recentRequests: "最近请求", successRate: "成功率", requests: "请求数", p95: "P95", recentFailure: "最近失败", details: "详情", viewDetails: "查看详情", noRequests: "无请求", recentRequestsAria: "最近 7 天最近 10 次请求", success: "成功", failed: "失败", noAccounts: "当前过滤条件下没有账号", readingAccounts: "正在读取账号", unavailable: "读取不可用", retry: "重试", recentRequestsDescription: "最近请求：7 天内最新 10 次，左旧右新；成功绿色，失败红色。请求质量按所选窗口独立计算。", accountDetails: "账号详情", requestHistory: "请求历史", availabilityEvents: "可用性事件", accountOperations: "账户操作", inventory: "采集信息", accountKey: "账号标识", lifecycle: "生命周期", basicStatus: "基础状态", consecutiveMissing: "连续缺失", firstSeen: "首次出现", lastSeen: "最近出现", lastRefresh: "最近刷新", nextRetry: "下次重试", providerSnapshot: "Provider 快照", snapshotFreshness: "快照新鲜度", providerHealth: "Provider 状态", tokenHealth: "Token 状态", expectedValidUntil: "预计有效至", availabilityReason: "可用性原因", availabilitySince: "可用性起始时间", availabilityState: "可用性", unknownAvailabilityNote: "当前可用性为 {{state}}；既有 ACTIVE 可用性事件仍保留在事件历史中。", notLoaded: "该账号不在当前列表页，采集信息未加载。", eventStatus: "可用性事件状态", active: "活动", resolved: "已解决", readingEvents: "正在读取可用性事件", activeEmpty: "当前没有活动可用性事件", resolvedEmpty: "当前没有已解决可用性事件", firstPage: "可用性首页", nextPage: "可用性下一页", incidentAccount: "账号", incidentReason: "原因", incidentStatus: "状态", hits: "次数", firstSeenLabel: "首次出现", lastSeenLabel: "最近出现", incidents: "账号质量问题", incidentProvider: "问题 Provider", allProviders: "全部 Provider", incidentReasonFilter: "问题原因", allReasons: "全部原因", refreshIncidents: "刷新问题", providerUnavailable: "Provider 筛选来源不可用", providerUnavailableDescription: "无法安全加载 Provider 过滤项。", readingIncidents: "正在读取问题", nodeNotFound: "Node 不存在", activeIncidentsEmpty: "当前没有活动问题", incidentsFirst: "问题首页", incidentsNext: "问题下一页", capacityTitle: "采集容量诊断", capacityDescription: "当前环境采集条件评估，不代表最近一次采集成功", refreshCapacity: "刷新容量", readingCapacity: "正在读取采集容量", capacityUnavailable: "容量诊断暂不可用", capacityExceeded: "监控规模超过采集容量，整轮新采集暂停", capacityExceededDescription: "请调整采集并发，或通过监控管理流程减少监控 Node；完成后刷新容量诊断。已有账号证据保留。", ready: "可用", capacityExceededLabel: "容量不足", disabled: "已禁用", enabled: "启用", yes: "是", no: "否", eligibleNodes: "符合采集条件的 Node", effectiveCapacity: "有效容量", concurrency: "并发", requestBudget: "请求", finalizeBudget: "落库预算", lifecycleBudget: "落库生命周期", claimBudget: "任务认领预算", dispatchMargin: "调度余量", pollGrace: "启动宽限", evaluatedSlot: "评估槽位", evaluatedAt: "时间", accountQuality: "账号清单与质量", noInstance: "请选择 Node 查看账号", previousAccounts: "账号上一页", nextAccounts: "账号下一页", providerExact: "Provider 精确筛选", providerPlaceholder: "Provider（精确）", allLifecycle: "全部生命周期", allBasicStatus: "全部基础状态", emailExact: "邮箱精确筛选", emailPlaceholder: "邮箱（精确匹配）", qualityWindow: "质量窗口", recent15m: "最近 15 分钟", recent1h: "最近 1 小时", allQuality: "全部质量", perPage: "每页账号数", pageSuffix: " / 页", query: "查询", invalidAccountFilter: "筛选条件或分页凭据无效，请清除筛选并重新查询。", forbiddenAccountList: "当前会话无权读取账号清单。", selectedNodeNotFound: "所选 Node 不存在", unsupportedAccountList: "所选 Node 不支持账号清单查询。", readUnavailable: "账号清单暂时不可用", unavailableAccountList: "Control 暂时无法读取账号清单。"
} as const;
const stage3AccountsEn = {
  node: "Node", model: "Model", time: "Time", result: "Result", failure: "Failure", latency: "Latency", requestId: "Request ID", requestHistoryCard: "Account Request History", unselectedHistory: "Select an account to view request history", noHistory: "No request history in the last 7 days", severity: "Severity", confirmed: "Confirmed",
  account: "Account", provider: "Provider", status: "Status", quality: "Quality", good: "Good", degraded: "Degraded", bad: "Bad", unknown: "Unknown", availability: "Availability", reason: "Reason", since: "Since", recentRequests: "Recent requests", successRate: "Success rate", requests: "Requests", p95: "P95", recentFailure: "Recent failure", details: "Details", viewDetails: "View details", noRequests: "No requests", recentRequestsAria: "Latest 10 requests in the last 7 days", success: "Success", failed: "Failed", noAccounts: "No account matches the current filters", readingAccounts: "Reading accounts", unavailable: "Unavailable", retry: "Retry", recentRequestsDescription: "Latest 10 requests in 7 days, oldest to newest; green is success and red is failure. Quality is calculated for the selected window.", accountDetails: "Account details", requestHistory: "Request history", availabilityEvents: "Availability events", accountOperations: "Account operations", inventory: "Inventory", accountKey: "Account key", lifecycle: "Lifecycle", basicStatus: "Basic status", consecutiveMissing: "Consecutive missing", firstSeen: "First seen", lastSeen: "Last seen", lastRefresh: "Last refresh", nextRetry: "Next retry", providerSnapshot: "Provider snapshot", snapshotFreshness: "Snapshot freshness", providerHealth: "Provider health", tokenHealth: "Token health", expectedValidUntil: "Expected valid until", availabilityReason: "Availability reason", availabilitySince: "Availability since", availabilityState: "Availability", unknownAvailabilityNote: "Availability is {{state}}; existing ACTIVE events remain in event history.", notLoaded: "This account is not on the current list page; inventory was not loaded.", eventStatus: "Availability event status", active: "Active", resolved: "Resolved", readingEvents: "Reading availability events", activeEmpty: "No Active availability events", resolvedEmpty: "No Resolved availability events", firstPage: "Availability first page", nextPage: "Availability next page", incidentAccount: "Account", incidentReason: "Reason", incidentStatus: "Status", hits: "Hits", firstSeenLabel: "First Seen", lastSeenLabel: "Last Seen", incidents: "Account Quality Incidents", incidentProvider: "Incident Provider", allProviders: "All Providers", incidentReasonFilter: "Incident Reason", allReasons: "All Reasons", refreshIncidents: "Refresh Incidents", providerUnavailable: "Provider filter source unavailable", providerUnavailableDescription: "Provider filter options could not be loaded safely.", readingIncidents: "Reading Incidents", nodeNotFound: "Node not found", activeIncidentsEmpty: "No Active incidents", incidentsFirst: "Incidents first page", incidentsNext: "Incidents next page", capacityTitle: "Inventory capacity diagnostics", capacityDescription: "Evaluation of current collection capacity; it does not represent the latest collection success.", refreshCapacity: "Refresh capacity", readingCapacity: "Reading collection capacity", capacityUnavailable: "Capacity diagnostics unavailable", capacityExceeded: "Monitoring scale exceeds collection capacity; new collection is paused for the whole cycle", capacityExceededDescription: "Adjust collection concurrency or reduce monitored Nodes through the monitoring process, then refresh capacity diagnostics. Existing account evidence is retained.", ready: "Ready", capacityExceededLabel: "Capacity exceeded", disabled: "Disabled", enabled: "Enabled", yes: "Yes", no: "No", eligibleNodes: "Eligible Nodes", effectiveCapacity: "Effective capacity", concurrency: "Concurrency", requestBudget: "Request", finalizeBudget: "Finalize budget", lifecycleBudget: "Lifecycle", claimBudget: "Task claim budget", dispatchMargin: "Dispatch margin", pollGrace: "Startup grace", evaluatedSlot: "Evaluated slot", evaluatedAt: "Time"
} as const;
const stage3AccountsCanonicalZh = {
  node: "节点", selectNode: "选择节点", nodeListUnavailable: "节点清单读取不可用", nodeNotFound: "节点不存在", empty: "当前没有登记节点", nodeFirstPage: "节点首页", nodeNextPage: "下一页节点",
  noInstance: "请选择节点查看账号", selectedNodeNotFound: "所选节点不存在", unsupportedAccountList: "所选节点不支持账号清单查询。", eligibleNodes: "符合采集条件的节点", capacityExceededDescription: "请调整采集并发，或通过监控管理流程减少监控节点；完成后刷新容量诊断。已有账号证据保留。",
} as const;
const stage3AccountsCanonicalEn = {
  node: "Node", selectNode: "Select Node", nodeListUnavailable: "Node list unavailable", nodeNotFound: "Node not found", empty: "No Node is registered", nodeFirstPage: "Node first page", nodeNextPage: "Next Node page",
  noInstance: "Select a Node to view accounts", selectedNodeNotFound: "The selected Node does not exist", unsupportedAccountList: "The selected Node does not support account-list queries.", eligibleNodes: "Eligible Nodes", capacityExceededDescription: "Adjust collection concurrency or reduce monitored Nodes through the monitoring process, then refresh capacity diagnostics. Existing account evidence is retained.",
} as const;
const stage3OperationsCanonicalZh = { accountsUploadAccount: "上传新账号", accountsUploadDescription: "无需已有采集账号。服务端会根据逻辑身份生成并验证远端目标。", accountsUploadProvider: "上传新 Provider", accountsUploadEmail: "上传新邮箱" } as const;
const stage3OperationsCanonicalEn = { accountsUploadAccount: "Upload New Account", accountsUploadDescription: "No existing collection account is required. The server generates and validates the remote target from the logical identity.", accountsUploadProvider: "Upload New Provider", accountsUploadEmail: "Upload New Email" } as const;
const stage3TopologyCapacityZh = { capacityTitle: "采集容量诊断", capacityDescription: "当前环境采集条件评估，不代表最近一次采集成功", refreshCapacity: "刷新容量", readingCapacity: "正在读取采集容量", capacityUnavailable: "容量诊断暂不可用", capacityExceeded: "监控规模超过采集容量，整轮新采集暂停", capacityExceededDescription: "请调整采集并发，或通过监控管理流程减少监控 Node；完成后刷新容量诊断。已有账号证据保留。", ready: "可用", capacityExceededLabel: "容量不足", disabled: "已禁用", enabled: "启用", yes: "是", no: "否", eligibleNodes: "符合采集条件的 Node", effectiveCapacity: "有效容量", concurrency: "并发", requestBudget: "请求", finalizeBudget: "落库预算", lifecycleBudget: "落库生命周期", claimBudget: "任务认领预算", dispatchMargin: "调度余量", pollGrace: "启动宽限", evaluatedSlot: "评估槽位", evaluatedAt: "时间" } as const;
const stage3TopologyCapacityEn = { capacityTitle: "Inventory capacity diagnostics", capacityDescription: "Evaluation of current collection capacity; it does not represent the latest collection success.", refreshCapacity: "Refresh capacity", readingCapacity: "Reading collection capacity", capacityUnavailable: "Capacity diagnostics unavailable", capacityExceeded: "Monitoring scale exceeds collection capacity; new collection is paused for the whole cycle", capacityExceededDescription: "Adjust collection concurrency or reduce monitored Nodes through the monitoring process, then refresh capacity diagnostics. Existing account evidence is retained.", ready: "Ready", capacityExceededLabel: "Capacity exceeded", disabled: "Disabled", enabled: "Enabled", yes: "Yes", no: "No", eligibleNodes: "Eligible Nodes", effectiveCapacity: "Effective capacity", concurrency: "Concurrency", requestBudget: "Request", finalizeBudget: "Finalize budget", lifecycleBudget: "Lifecycle", claimBudget: "Task claim budget", dispatchMargin: "Dispatch margin", pollGrace: "Startup grace", evaluatedSlot: "Evaluated slot", evaluatedAt: "Time" } as const;
const stage3AccountsEnExtras = {
  accountQuality: "Account inventory and quality", noInstance: "Select a Node to view accounts", previousAccounts: "Previous accounts", nextAccounts: "Next accounts", providerExact: "Filter Provider exactly", providerPlaceholder: "Provider (exact)", allLifecycle: "All lifecycles", allBasicStatus: "All basic statuses", emailExact: "Filter email exactly", emailPlaceholder: "Email (exact match)", qualityWindow: "Quality window", recent15m: "Last 15 minutes", recent1h: "Last hour", allQuality: "All quality", perPage: "Accounts per page", pageSuffix: " / page", query: "Query", invalidAccountFilter: "The filter or pagination credential is invalid. Clear the filters and try again.", forbiddenAccountList: "The current session cannot read the account list.", selectedNodeNotFound: "The selected Node does not exist", unsupportedAccountList: "The selected Node does not support account-list queries.", readUnavailable: "The account list is unavailable", unavailableAccountList: "Control cannot read the account list right now."
} as const;
const stage3JobsZh = { readError: "读取失败", notFound: "任务不存在", retryRead: "重试读取", action: "操作", viewDetails: "查看详情", filters: "任务过滤", type: "任务类型", allTypes: "全部任务类型", status: "任务状态", allStatuses: "全部状态", createdFrom: "创建时间起点", createdTo: "创建时间终点", perPage: "每页任务数", pageSuffix: " / 页", empty: "当前过滤条件下没有持久任务", previous: "上一页", next: "下一页", detail: "任务详情", attempt: "尝试", cancelRequested: "取消请求", requested: "已请求", notRequested: "未请求", fixedError: "固定错误码", lifecycleEvents: "生命周期事件", noEvents: "尚无生命周期事件", reading: "正在读取任务" } as const;
const stage3JobsEn = { readError: "Read failed", notFound: "Job not found", retryRead: "Retry read", action: "Action", viewDetails: "View details", filters: "Job filters", type: "Job type", allTypes: "All job types", status: "Job status", allStatuses: "All statuses", createdFrom: "Created from", createdTo: "Created to", perPage: "Jobs per page", pageSuffix: " / page", empty: "No jobs", previous: "Previous", next: "Next", detail: "Job details", attempt: "Attempt", cancelRequested: "Cancel requested", requested: "Requested", notRequested: "Not requested", fixedError: "Fixed error code", lifecycleEvents: "Lifecycle events", noEvents: "No lifecycle events", reading: "Reading jobs" } as const;
const stage3ProblemsZh = { invalidFilter: "筛选条件或分页凭据无效，请清除筛选并重新查询。", forbidden: "当前会话无权读取问题。", unavailable: "问题读取暂不可用", retry: "重试", issues: "问题证据", availability: "可用性", token: "Token", inventoryTiming: "采集时间", requestEvidence: "请求证据", since: "自", expectedValidUntil: "预计有效至", lastRefresh: "最近刷新", nextRetry: "下次重试", lastSuccess: "最近成功", lastFailure: "最近失败", filters: "问题筛选", provider: "Provider", nodeUuid: "节点 UUID", severity: "严重度", reason: "原因", problemReason: "原因", email: "邮箱", pageSize: "每页数量", query: "查询", reading: "正在读取问题", noFiltered: "当前筛选条件下没有已确认问题", noProblems: "当前没有已确认问题", previous: "上一页", next: "下一页", critical: "Critical", warning: "Warning", node: "节点", account: "账号" } as const;
const stage3ProblemsEn = { invalidFilter: "The filter is invalid. Clear the filters and try again.", forbidden: "The current session cannot read Problems.", unavailable: "Problems are temporarily unavailable.", retry: "Retry", issues: "Problem evidence", availability: "Availability", token: "Token", inventoryTiming: "Inventory timing", requestEvidence: "Request evidence", since: "Since", expectedValidUntil: "Expected valid until", lastRefresh: "Last refresh", nextRetry: "Next retry", lastSuccess: "Last success", lastFailure: "Last failure", filters: "Problem filters", provider: "Provider", nodeUuid: "Node UUID", severity: "Severity", reason: "Reason", problemReason: "Reason", email: "Email", pageSize: "Page size", query: "Query", reading: "Reading Problems", noFiltered: "No confirmed problems match the filters", noProblems: "No confirmed problems", previous: "Previous", next: "Next", critical: "Critical", warning: "Warning", node: "Node", account: "Account" } as const;
const stage3OperationsZh = { overrideConfirmTitle: "确认执行 {{kind}} Override？", overrideTarget: "目标操作：{{commandId}}", reasonRestart: "Control 进程已重启", reasonNodeStopped: "Node 已停止", reasonAccepted: "已人工接受风险", lifecycleOverride: "Lifecycle Override", sameAccountOverride: "Same-account Override" } as const;
const stage3OperationsEn = { overrideConfirmTitle: "Run {{kind}} override?", overrideTarget: "Target operation: {{commandId}}", reasonRestart: "The Control process restarted", reasonNodeStopped: "The Node stopped", reasonAccepted: "Risk was accepted manually", lifecycleOverride: "Lifecycle override", sameAccountOverride: "Same-account override" } as const;
const stage3GatewayFormZh = { gatewayFormRegister: "登记 Gateway", gatewayFormEdit: "编辑 Gateway", gatewayFormReplace: "Replace Gateway" } as const;
const stage3GatewayFormEn = { gatewayFormRegister: "Register Gateway", gatewayFormEdit: "Edit Gateway", gatewayFormReplace: "Replace Gateway" } as const;
const stage3AssetsZh = { managementTitle: "Gateway 管理", lifecycleFilter: "Gateway 生命周期过滤", currentGateway: "当前 Gateway", retiredGateway: "历史 Gateway", all: "全部", registerGateway: "登记 Gateway", listReadFailed: "Gateway 列表读取失败", details: "详情", health: "Health", connectionTest: "Connection Test", edit: "编辑", replace: "Replace", retire: "Retire", retireGatewayTitle: "确认退役此 Gateway？", retireGatewayDescription: "退役后将清理当前绑定，历史记录仍会保留。", retireNodeTitle: "确认退役此 Node？", confirmRetire: "退役", cancel: "取消", save: "保存", register: "登记", newInstanceId: "新 Instance ID", displayName: "显示名称", endpoint: "Management endpoint", directoryCredential: "Directory credential（可选）", credentialAction: "Credential 操作", credentialActionPlaceholder: "按操作选择", optional: "可选", keep: "Keep existing", set: "Set new credential", clear: "Clear credential", noSavedCredential: "不会回显已保存的 credential。", uuid: "UUID", validHttp: "请输入有效的 http:// 地址", gatewayDetails: "Gateway 详情", environmentId: "环境 ID", name: "名称", type: "类型", state: "状态", configured: "已配置", notConfigured: "未配置", updatedAt: "更新时间", predecessor: "前驱", successor: "后继", providerPolicyScope: "Provider 策略作用域", version: "版本", scope: "作用域", active: "Active", outOfScope: "Out of scope", activeWindow: "激活区间", nodeType: "Node 类型", contract: "Driver 合约", capability: "能力", monitoring: "账号监控", activated: "已激活", inactive: "未激活", nodeFilter: "Node 过滤器", nodeLifecycle: "Node 生命周期", currentNode: "当前 Node", retiredNode: "历史 Node", allNodes: "全部 Node", allNodeTypes: "全部 Node 类型", allCapabilities: "全部 capability", monitoringStatus: "监控状态", monitoringActive: "监控已激活", monitoringInactive: "监控未激活", registerNode: "登记 Node", driverUnavailable: "Driver 信息不可用，无法登记 Node", nodeDetails: "Node 详情", managementCredential: "Management credential（可选）", monitoringEnable: "启用监控", monitoringDisable: "停用监控", disableMonitoringTitle: "确认立即停用监控？", disableMonitoringDescription: "这会立即关闭当前监控，并取消已有的未来监控预约。", disableMonitoring: "停用监控", healthResult: "Health 结果", connectionResult: "Connection Test 结果", reachable: "reachable", unreachable: "unreachable", monitoringResult: "Monitoring {{result}}", currentState: "current={{state}}", closed: "closed", cancelled: "cancelled", operationCompleted: "监控操作已完成：{{result}}", healthCompleted: "Health 检查已完成。", connectionCompleted: "Connection Test 已完成。", environment: "环境", credential: "Credential", revision: "Revision", operation: "操作", lifecycle: "生命周期", capabilities: "能力", monitoringWindow: "监控", predecessorLabel: "前驱", successorLabel: "后继", formTitleRegister: "登记 Node", formTitleEdit: "编辑 Node", formTitleReplace: "Replace Node", generated: "自动生成", requiredCredential: "请输入新的 credential", credentialKeep: "保留现有", credentialSet: "设置新 credential", credentialClear: "清除 credential", policyActive: "Active", policyOutOfScope: "Out of scope", drivers: "Drivers", nodes: "Nodes", nodeTypeLabel: "Node 类型", contractVersion: "合约版本", status: "状态", operationLabel: "操作", healthDescription: "{{reachability}}；reason={{reason}}；latency={{latency}}ms", monitoringDescription: "current={{state}}；closed={{closed}}；cancelled={{cancelled}}" } as const;
const stage3AssetsEn = { managementTitle: "Gateway management", lifecycleFilter: "Gateway lifecycle filter", currentGateway: "Current Gateway", retiredGateway: "Retired Gateway", all: "All", registerGateway: "Register Gateway", listReadFailed: "Gateway list read failed", details: "Details", health: "Health", connectionTest: "Connection Test", edit: "Edit", replace: "Replace", retire: "Retire", retireGatewayTitle: "Retire this Gateway?", retireGatewayDescription: "Retiring it clears the current binding while preserving history.", retireNodeTitle: "Retire this Node?", confirmRetire: "Retire", cancel: "Cancel", save: "Save", register: "Register", newInstanceId: "New Instance ID", displayName: "Display name", endpoint: "Management endpoint", directoryCredential: "Directory credential (optional)", credentialAction: "Credential action", credentialActionPlaceholder: "Choose an action", optional: "Optional", keep: "Keep existing", set: "Set new credential", clear: "Clear credential", noSavedCredential: "Saved credentials are never echoed.", uuid: "UUID", validHttp: "Enter a valid http:// address", gatewayDetails: "Gateway details", environmentId: "Environment ID", name: "Name", type: "Type", state: "State", configured: "Configured", notConfigured: "Not configured", updatedAt: "Updated", predecessor: "Predecessor", successor: "Successor", providerPolicyScope: "Provider policy scope", version: "Version", scope: "Scope", active: "Active", outOfScope: "Out of scope", activeWindow: "Active window", nodeType: "Node type", contract: "Driver contract", capability: "Capability", monitoring: "Account monitoring", activated: "Active", inactive: "Inactive", nodeFilter: "Node filters", nodeLifecycle: "Node lifecycle", currentNode: "Current Node", retiredNode: "Retired Node", allNodes: "All Nodes", allNodeTypes: "All Node types", allCapabilities: "All capabilities", monitoringStatus: "Monitoring status", monitoringActive: "Monitoring active", monitoringInactive: "Monitoring inactive", registerNode: "Register Node", driverUnavailable: "Driver information unavailable; Node registration is disabled", nodeDetails: "Node details", managementCredential: "Management credential (optional)", monitoringEnable: "Enable monitoring", monitoringDisable: "Disable monitoring", disableMonitoringTitle: "Disable monitoring now?", disableMonitoringDescription: "This closes current monitoring and cancels future monitoring reservations.", disableMonitoring: "Disable monitoring", healthResult: "Health result", connectionResult: "Connection Test result", reachable: "reachable", unreachable: "unreachable", monitoringResult: "Monitoring {{result}}", currentState: "current={{state}}", closed: "closed", cancelled: "cancelled", operationCompleted: "Monitoring operation completed: {{result}}", healthCompleted: "Health check completed.", connectionCompleted: "Connection Test completed.", environment: "Environment", credential: "Credential", revision: "Revision", operation: "Action", lifecycle: "Lifecycle", capabilities: "Capabilities", monitoringWindow: "Monitoring", predecessorLabel: "Predecessor", successorLabel: "Successor", formTitleRegister: "Register Node", formTitleEdit: "Edit Node", formTitleReplace: "Replace Node", generated: "Generated automatically", requiredCredential: "Enter a new credential", credentialKeep: "Keep existing", credentialSet: "Set new credential", credentialClear: "Clear credential", policyActive: "Active", policyOutOfScope: "Out of scope", drivers: "Drivers", nodes: "Nodes", nodeTypeLabel: "Node type", contractVersion: "Contract version", status: "Status", operationLabel: "Action", healthDescription: "{{reachability}}; reason={{reason}}; latency={{latency}}ms", monitoringDescription: "current={{state}}; closed={{closed}}; cancelled={{cancelled}}" } as const;
const stage3NodesZh = {
  readFailed: "读取失败", unavailable: "当前数据不可用；未显示旧数据或内部错误。", retry: "重试", cancel: "取消", save: "保存", validHttp: "请输入有效的 http:// 地址",
  node: "节点", instanceId: "实例 ID", endpoint: "管理地址", nodeType: "节点类型", contract: "驱动合约", capability: "能力",
  nodeFilter: "节点筛选", nodeLifecycle: "节点生命周期", currentNode: "当前节点", retiredNode: "已退役节点", allNodes: "全部节点", allNodeTypes: "全部节点类型", allCapabilities: "全部能力",
  monitoringStatus: "监控状态", monitoringActive: "已启用监控", monitoringInactive: "未启用监控", registerNode: "登记节点", driverUnavailable: "驱动信息不可用，无法登记节点", nodeDetails: "节点详情",
  managementCredential: "管理凭据（可选）", health: "健康检查", connectionTest: "连接测试", monitoringEnable: "启用监控", monitoringDisable: "停用监控", healthResult: "健康检查结果", connectionResult: "连接测试结果",
  monitoringResult: "监控操作结果：{{result}}", healthCompleted: "健康检查已完成。", connectionCompleted: "连接测试已完成。", environment: "环境", credential: "凭据", revision: "修订版本", lifecycle: "生命周期", capabilities: "能力", monitoringWindow: "监控",
  formTitleRegister: "登记节点", formTitleEdit: "编辑节点", formTitleReplace: "替换节点", requiredCredential: "请输入新的凭据", credentialKeep: "保留现有凭据", credentialSet: "设置新凭据", credentialClear: "清除凭据",
  drivers: "驱动", nodes: "节点", nodeTypeLabel: "节点类型", operationLabel: "操作", healthDescription: "{{reachability}}；原因={{reason}}；延迟={{latency}}ms", monitoringDescription: "当前状态={{state}}；已关闭={{closed}}；已取消={{cancelled}}",
  emptyNodes: "当前筛选条件下没有节点", previousPage: "上一页", nextPage: "下一页", all: "全部", activated: "已启用", inactive: "未启用", configured: "已配置", notConfigured: "未配置", reachable: "可达", unreachable: "不可达",
  details: "详情", edit: "编辑", replace: "替换", retire: "退役", retireNodeTitle: "确认退役此节点？", confirmRetire: "确认退役", status: "状态", displayName: "显示名称", newInstanceId: "新实例 ID", generated: "自动生成", operation: "操作", predecessorLabel: "前置节点", successorLabel: "后继节点", disableMonitoringTitle: "确认停用监控？", disableMonitoringDescription: "这会立即关闭当前监控，并取消已有的未来监控预约。", disableMonitoring: "停用监控", operationCompleted: "操作已完成：{{result}}", errorConflict: "节点已被其他管理员修改，请刷新后重试。", errorConfig: "节点配置无效，请检查字段后重试。", errorExpired: "认证已过期，请重新登录。", errorForbidden: "当前账号没有执行该操作的权限。", errorOperation: "节点操作未完成，请刷新后重试。", monitoring: "监控", credentialAction: "凭据操作",
} as const;
const stage3NodesEn = {
  readFailed: "Read failed", unavailable: "The current data is unavailable; stale data and internal errors are not shown.", retry: "Retry", cancel: "Cancel", save: "Save", validHttp: "Enter a valid http:// address",
  node: "Node", instanceId: "Instance ID", endpoint: "Management endpoint", nodeType: "Node type", contract: "Driver contract", capability: "Capability",
  nodeFilter: "Node filters", nodeLifecycle: "Node lifecycle", currentNode: "Active node", retiredNode: "Retired node", allNodes: "All nodes", allNodeTypes: "All node types", allCapabilities: "All capabilities",
  monitoringStatus: "Monitoring status", monitoringActive: "Monitoring enabled", monitoringInactive: "Monitoring disabled", registerNode: "Register node", driverUnavailable: "Driver information unavailable; node registration is disabled", nodeDetails: "Node details",
  managementCredential: "Management credential (optional)", health: "Health observation", connectionTest: "Connection test", monitoringEnable: "Enable monitoring", monitoringDisable: "Disable monitoring", healthResult: "Health result", connectionResult: "Connection test result",
  monitoringResult: "Monitoring operation: {{result}}", healthCompleted: "Health observation completed.", connectionCompleted: "Connection test completed.", environment: "Environment", credential: "Credential", revision: "Revision", lifecycle: "Lifecycle", capabilities: "Capabilities", monitoringWindow: "Monitoring",
  formTitleRegister: "Register node", formTitleEdit: "Edit node", formTitleReplace: "Replace node", requiredCredential: "Enter a new credential", credentialKeep: "Keep existing credential", credentialSet: "Set new credential", credentialClear: "Clear credential",
  drivers: "Drivers", nodes: "Nodes", nodeTypeLabel: "Node type", operationLabel: "Action", healthDescription: "{{reachability}}; reason={{reason}}; latency={{latency}}ms", monitoringDescription: "current={{state}}; closed={{closed}}; cancelled={{cancelled}}",
  emptyNodes: "No node matches the current filters", previousPage: "Previous", nextPage: "Next", all: "All", activated: "Enabled", inactive: "Disabled", configured: "Configured", notConfigured: "Not configured", reachable: "reachable", unreachable: "unreachable",
  details: "Details", edit: "Edit", replace: "Replace", retire: "Retire", retireNodeTitle: "Retire this node?", confirmRetire: "Retire", status: "Status", displayName: "Display name", newInstanceId: "New instance ID", generated: "Generated automatically", operation: "Action", predecessorLabel: "Predecessor", successorLabel: "Successor", disableMonitoringTitle: "Disable monitoring now?", disableMonitoringDescription: "This closes current monitoring and cancels future monitoring reservations.", disableMonitoring: "Disable monitoring", operationCompleted: "Operation completed: {{result}}", errorConflict: "The node changed; refresh and try again.", errorConfig: "The node configuration is invalid.", errorExpired: "The session expired; sign in again.", errorForbidden: "You are not allowed to perform this operation.", errorOperation: "The node operation did not complete; refresh and try again.", monitoring: "Monitoring", credentialAction: "Credential action",
} as const;

const canonicalTranslation = {
  common: {
    locale: {
      label: "语言",
    },
    readState: {
      loading: "加载中",
      unavailable: "暂不可用",
      empty: "暂无记录",
      retry: "重试",
    },
    shell: {
      authLoading: "正在读取安全状态",
      routeLoading: "正在加载页面",
      authUnavailable: "Control 认证服务暂时不可用",
      authUnavailableDescription: "管理面已安全关闭；请检查 Control 与 PostgreSQL 状态。",
      sidebarLabel: "主导航",
      controlConsole: "控制台",
      search: "导航搜索",
      searchPlaceholder: "搜索页面或管理入口",
      logout: "注销",
    },
  },
  navigation: {
    dashboard: "仪表盘",
    accounts: "账号",
    nodes: "节点",
    operations: "操作",
    monitoring: "监控",
    problems: "问题",
    settings: "设置",
    assets: "资产 / Gateway 辅助管理",
  },
  dashboard: { title: "仪表盘", description: "系统概览与主要工作入口", overview: "权威概览", control: "控制服务", gatewayAssets: "网关资产", nodeAssets: "节点资产", pollCapacity: "采集容量", status: "状态", available: "正常", version: "版本", total: "总数", active: "活跃", retired: "已退役", eligibleNodes: "符合采集条件的节点", effectiveCapacity: "有效容量", evaluatedAt: "评估时间", workEntries: "工作入口", open: "打开", retry: "重试", unavailable: "暂不可用", entries: { accounts: { title: "账号", description: "查看账号和清单" }, operations: { title: "操作", description: "查看持久任务和操作入口" }, problems: { title: "问题", description: "查看已确认问题" } }, capacityStatus: { ready: "可用", capacity_exceeded: "容量不足", disabled: "已禁用" } },
  nodes: { title: "节点", description: "节点管理与生命周期操作", ...stage3NodesZh },
  settings: {
    title: "设置",
    description: "会话、安全与管理员设置",
    interface: { title: "界面", description: "语言仅保存在当前浏览器，不会同步到其他浏览器或设备。" },
    csrfInvalid: "安全凭据已刷新。为避免重复执行，本次操作没有自动重放，请确认状态后重试。",
    reauthenticationRequired: "此操作需要先在“重新认证”页签验证密码与 MFA，证明有效期为 5 分钟。",
    reauthenticationSuccess: "重新认证成功，高风险操作窗口已开启 5 分钟。",
    passwordChanged: "密码已修改，其他会话已撤销。",
    administratorDisabled: "管理员已禁用，其会话与未使用令牌均已撤销。",
    highRiskValidUntil: "重新认证有效至 {{date}}",
    highRiskLocked: "高风险操作当前锁定",
    tabs: { session: "会话", reauth: "重新认证", password: "修改密码", admins: "管理员", recovery: "恢复码", interface: "界面" },
    session: {
      current: "当前会话",
      idleUntil: "空闲到期：{{date}}",
      absoluteUntil: "绝对到期：{{date}}",
      mfa: "MFA：{{value}}",
      completed: "已完成",
      incomplete: "未完成",
      recoveryRemaining: "剩余恢复码：{{count}}",
      refresh: "刷新会话与 CSRF",
    },
    mfa: { totp: "TOTP", recoveryCode: "恢复码" },
    reauth: { currentPassword: "当前密码", mfaMethod: "MFA 方式", mfaCode: "MFA 验证码", submit: "重新认证" },
    password: { current: "当前密码", next: "新密码", mfaMethod: "MFA 方式", mfaCode: "MFA 验证码", submit: "修改密码并轮换会话" },
    admins: {
      loginName: "登录名", displayName: "实名", createDisplayName: "实名显示名", role: "角色", status: "状态", lastLogin: "最近登录",
      createTitle: "创建待激活管理员", reason: "操作原因", create: "创建并显示一次性令牌",
      actionTitle: "对选中管理员执行高风险操作", reasonPlaceholder: "操作原因（10–500 字符）",
      disable: "禁用", disableConfirmTitle: "确认禁用管理员？", disableConfirmContent: "目标的全部会话与未使用令牌将被撤销。",
      token: "重新生成激活令牌", resetMfa: "重置 MFA", resetConfirmTitle: "确认重置 MFA？", resetConfirmContent: "目标将回到待激活状态并失去现有会话。",
    },
    recovery: {
      description: "重新生成会立即撤销全部旧恢复码，新码只显示一次。",
      regenerate: "重新生成恢复码", confirmTitle: "重新生成恢复码？", confirmContent: "所有旧恢复码将立即失效。",
    },
  },
  assets: {
    ...stage3GatewayFormZh,
    title: "资产注册表",
    description: "Gateway 生命周期管理与资产状态视图",
    management: "管理员控制台",
    gateway: "Gateway",
    policy: "当前 Provider 策略",
    readFailed: "读取失败",
    unavailable: "当前数据不可用；未显示旧数据或内部错误。",
    retry: "重试",
    emptyGateway: "尚未登记 Gateway",
    emptyDriver: "尚未登记 Driver",
    selectDriver: "请先登记 Driver",
    emptyPolicy: "尚未配置当前 Provider 策略",
    emptyNodes: "当前过滤条件下没有 Relay Node",
    node: "Node", instanceId: "Instance ID",
    ...stage3AssetsZh, capability: "Capability", previousPage: "上一页", nextPage: "下一页", errorStale: "资产已被其他管理员修改，请刷新后重试。", errorConflict: "该操作标识已用于其他请求。", errorEndpoint: "Gateway 管理地址必须使用 http://。", errorGatewayExists: "当前已经存在 Gateway，请使用 Replace。", errorRetired: "已退役的 Gateway 不能继续操作。", errorExpired: "认证已过期，请重新登录。", errorForbidden: "当前账号没有执行该操作的权限。", errorOperation: "操作未完成，请刷新后重试。", errorNodeConflict: "Node 已被其他管理员修改或当前状态不允许该操作，请刷新后重试。", errorNodeConfig: "Node 配置无效，请检查字段后重试。", errorNodeOperation: "Node 操作未完成，请刷新后重试。",
  },
  topology: {
    title: "Node Topology",
    description: "Node 及其只读关联观察",
    management: "管理员控制台",
    ...stage3TopologyZh, ...stage3TopologyCapacityZh, accountQuality: "Account Quality", selectedNodeNotFound: "所选 Node 不存在",
  },
  monitoring: {
    title: "监控",
    description: "跨域诊断与证据观察",
    management: "管理员控制台",
    ...stage3TopologyZh,
    ...stage3TopologyCapacityZh,
    provider: "Provider",
    readUnavailable: "读取不可用",
    evidenceNote: "证据记录权威关系评估，不等于历史已确认归属。",
    unknown: "未知",
    historyPlaceholder: "全部历史状态",
    type: "类型",
    account: "账号标识",
    snapshot: "快照",
    notYetObserved: "尚未观测",
    normal: "正常",
    bindingTruth: "绑定事实",
    bindingResolution: "绑定解析",
    directoryFreshness: "目录新鲜度",
    contextSource: "上下文来源",
    accountId: "账号 ID",
    accountContext: "账号上下文",
    freshness: "快照新鲜度",
    latestSnapshot: "最近完整快照",
    current: "当前",
    emptySet: "当前集合为空",
    capacityDescription: "当前环境采集条件评估，不代表最近一次采集成功",
    capacityExceededDescription: "请调整采集并发，或通过监控管理流程减少监控节点；完成后刷新容量诊断。已有账号证据保留。",
    eligibleNodes: "符合采集条件的节点",
    relayNode: "节点上下文",
    node: "节点",
    nodeFirstPage: "节点上一页",
    nodeNextPage: "节点下一页",
    selectNode: "选择节点",
    empty: "当前没有登记节点",
    nodeListUnavailable: "节点清单读取不可用",
    nodeNotFound: "节点不存在",
    nodeReadUnavailable: "节点读取不可用",
    inventoryEvidence: "节点诊断上下文",
    instanceId: "实例 ID",
    providerSnapshot: "Provider 快照与健康观测",
    gatewayContext: "Gateway 绑定上下文",
    ownershipCurrent: "当前重复归属",
    ownershipHistory: "重复归属历史",
    noInstance: "请选择节点查看诊断信息",
    noProviders: "没有可展示的 Provider 诊断",
    health: "健康观测",
    healthObservation: "健康观测时间",
    refreshProvider: "刷新 Provider 诊断",
    refreshBinding: "刷新绑定诊断",
    refreshCurrent: "刷新当前归属",
    refreshHistory: "刷新历史归属",
    historicalInvolvement: "历史诊断涉及情况",
    affectedNodes: "受影响节点",
    emptyOccurrence: "没有符合条件的重复归属记录",
    statusSeverity: "状态 / 严重度",
    evidenceHealth: "证据状态",
    sourceTime: "来源时间",
    evaluationTime: "评估时间",
    recordedTime: "记录时间",
    firstPage: "上一页",
    nextPage: "下一页",
    evidenceFirstPage: "证据上一页",
    evidenceNextPage: "证据下一页",
    navigationTitle: "前往所属页面",
    openNodes: "节点管理",
    openAccounts: "账号与清单",
    openProblems: "已确认问题",
    openAssets: "Gateway 与环境资产",
  },
  operations: {
    title: "操作",
    description: "持久任务运行历史与操作入口",
    guidance: "操作只提交逻辑账号身份；物理目标由服务端基于最新 Node 快照选择。",
    applied: "已应用", noop: "无需变更", unknown: "远端结果不确定", failed: "执行失败",
    unknownTitle: "执行结果未知", unknownDescription: "请求可能已被远端应用，也可能未应用。系统不会自动重试，以避免重复操作。请结合当前账户状态人工判断后再决定是否发起新的命令。",
    commandId: "Operation command ID", operation: "操作", executionState: "执行状态", resultError: "结果/错误", created: "创建时间", updated: "更新时间",
    disable: "Disable", enable: "Enable", remove: "Remove", uploadNew: "Upload New", replaceExisting: "Replace Existing",
    removeTitle: "确认移除此账户？", removeDescription: "该操作会删除 Node 上对应的单个凭据文件，无法由 Control 自动恢复。", confirmRemove: "确认移除",
    replaceTitle: "确认替换现有凭据？", replaceDescription: "Replace 使用远端原生的尽力而为、后写入覆盖语义。", confirmReplace: "确认替换",
    lookupPlaceholder: "输入 Command ID 查看操作结果", read: "读取操作", unknownOverride: "未知结果 Override", overrideType: "Override 类型", overrideReason: "Override reason", overrideDetail: "Override detail", optionalDetail: "可选说明", submitOverride: "执行 Override", confirmOverride: "确认 Override",
    uploadAccount: "Upload New Account", uploadDescription: "无需已有 Inventory 账号。服务端会根据逻辑身份生成并验证远端目标。", uploadProvider: "Upload New Provider", uploadEmail: "Upload New Email", accountEmail: "账户邮箱", chooseCredential: "选择 credential JSON（最大 1 MiB）",
    credentialTooLarge: "凭据文件不能超过 1 MiB", keep: "Keep existing", set: "Set new credential", clear: "Clear credential",
    ...stage3OperationsZh, ...stage3OperationsCanonicalZh,
  },
  accounts: { title: "账号", description: "账号页面基础结构", ...stage3AccountsZh, ...stage3AccountsCanonicalZh, readingEvents: "正在读取请求历史", nodeNotFound: "账号不存在（not found）", requestFirstPage: "History 首页", requestNextPage: "History 下一页" },
  jobs: { title: "持久任务", description: "PostgreSQL 真相源的只读运行视图", management: "管理员控制台", ...stage3JobsZh, jobId: "任务 ID", operationId: "操作 ID", outbox: "发件箱状态", availableAt: "可执行时间", startedAt: "开始时间", completedAt: "完成时间", createdAt: "创建时间", updatedAt: "更新时间", initial: "初始" },
  problems: { title: "问题", description: "已确认账号问题的只读观察", ...stage3ProblemsZh, pageSuffix: " / 页" },
  auth: {
    errors: {
      unavailable: "请求暂时无法完成，请稍后再试。",
      rateLimited: "尝试次数过多，请稍后再试。",
      challengeExpired: "验证已过期，请重新登录。",
      lastAdministratorProtected: "不能禁用最后一个可用管理员。",
      selfDisableForbidden: "不能禁用当前登录账号。",
      reauthenticationRequired: "请先完成重新认证。",
      unauthorized: "认证失败，请检查输入后重试。",
      csrfInvalid: "安全凭据已变化，请刷新会话后重试。",
      requestIncomplete: "请求未完成（请求 ID：{{requestId}}）",
    },
    login: {
      title: "管理员登录",
      securityHint: "所有认证失败使用统一提示，不确认账号状态。",
      loginName: "登录名",
      password: "密码",
      continue: "继续",
      activationLink: "使用激活令牌设置新账号",
      mfaRequired: "需要第二步验证",
      challengeValidUntil: "挑战有效至 {{date}}",
      totp: "TOTP 验证码",
      totpMethod: "TOTP",
      recoveryCode: "恢复码",
      verify: "验证并登录",
      backToPassword: "返回密码登录",
      recoveryWarning: "恢复码成功使用后将立即失效；登录后请检查剩余数量。",
      expired: "验证已过期，请重新登录。",
    },
    bootstrap: {
      title: "初始化 Control",
      inProgress: "存在未完成的初始化，请重新输入相同资料继续，或使用运行时 Secret 重置。",
      newInstallation: "创建首个实名超级管理员。",
      secret: "运行时 Bootstrap Secret",
      loginName: "登录名",
      displayName: "实名显示名",
      password: "密码",
      start: "开始或继续初始化",
      resetPending: "重置未完成流程",
      addAuthenticator: "请立即添加到认证器",
      totpMemoryOnly: "此 TOTP 配置仅在当前页面内存中保留。",
      copyUri: "复制 TOTP 配置 URI",
      confirm: "确认并永久完成",
      reset: "重置",
      totpCode: "TOTP 验证码",
    },
    activation: {
      title: "激活管理员账号",
      tokenHint: "请手工粘贴令牌。页面不会从 URL、历史记录或浏览器存储读取令牌。",
      token: "一次性激活令牌",
      start: "开始激活",
      newPassword: "新密码",
      totpCode: "TOTP 验证码",
      complete: "完成激活",
      backToLogin: "返回登录",
      leaveHint: "离开此页后不会保留。",
    },
    oneTime: {
      recoveryTitle: "保存恢复码",
      activationTitle: "复制激活令牌",
      onlyShownOnce: "只显示这一次",
      recoveryDescription: "每个恢复码只能使用一次。请保存到密码管理器或离线安全位置。",
      activationDescription: "令牌只应通过可信渠道交给对应管理员，禁止放入 URL。",
      validUntil: "有效至 {{date}}",
      confirmation: "我已安全保存，理解离开后无法再次查看",
      leave: "确认并离开",
      noCache: "本页设置禁止缓存；离开时材料会从应用内存移除。",
    },
  },
} as const;

type LeafKeys<T> = {
  [Key in keyof T & string]: T[Key] extends Record<string, unknown>
    ? `${Key}.${LeafKeys<T[Key]>}`
    : Key;
}[keyof T & string];

type ResourceShape<T> = {
  [Key in keyof T]: T[Key] extends Record<string, unknown> ? ResourceShape<T[Key]> : string;
};

export type TranslationKey = LeafKeys<typeof canonicalTranslation>;
export type TranslationResource = ResourceShape<typeof canonicalTranslation>;

export const resources = {
  "zh-CN": {
    translation: canonicalTranslation,
  },
  en: {
    translation: {
      common: {
        locale: {
          label: "Language",
        },
        readState: {
          loading: "Loading",
          unavailable: "Unavailable",
          empty: "No records",
          retry: "Retry",
        },
        shell: {
          authLoading: "Reading security state",
          routeLoading: "Loading page",
          authUnavailable: "Control authentication service is temporarily unavailable",
          authUnavailableDescription: "The management surface is safely closed; check Control and PostgreSQL status.",
          sidebarLabel: "Primary navigation",
          controlConsole: "Control",
          search: "Navigation search",
          searchPlaceholder: "Search pages or management entries",
          logout: "Sign out",
        },
      },
      navigation: {
        dashboard: "Dashboard",
        accounts: "Accounts",
        nodes: "Relay Nodes",
        operations: "Operations",
        monitoring: "Monitoring",
        problems: "Problems",
        settings: "Settings",
        assets: "Assets / Gateway auxiliary",
      },
      dashboard: { title: "Dashboard", description: "Authoritative system overview and work entries", overview: "Authoritative overview", control: "Control service", gatewayAssets: "Gateway assets", nodeAssets: "Relay Node assets", pollCapacity: "Inventory poll capacity", status: "Status", available: "Available", version: "Version", total: "Total", active: "Active", retired: "Retired", eligibleNodes: "Eligible Nodes", effectiveCapacity: "Effective capacity", evaluatedAt: "Evaluated at", workEntries: "Work entries", open: "Open", retry: "Retry", unavailable: "Unavailable", entries: { accounts: { title: "Accounts", description: "View accounts and Inventory" }, operations: { title: "Operations", description: "View durable jobs and operation entry points" }, problems: { title: "Problems", description: "View confirmed problems" } }, capacityStatus: { ready: "Ready", capacity_exceeded: "Capacity exceeded", disabled: "Disabled" } },
      nodes: { title: "Relay Nodes", description: "Relay Node management and lifecycle operations", ...stage3NodesEn },
      settings: {
        title: "Settings",
        description: "Session, security, and administrator settings",
        interface: { title: "Interface", description: "Language is stored only in this browser and is not synchronized to other browsers or devices." },
        csrfInvalid: "The security credential was refreshed. This operation was not replayed; confirm the state and try again.",
        reauthenticationRequired: "Complete reauthentication in the Reauthentication tab first; it is valid for 5 minutes.",
        reauthenticationSuccess: "Reauthentication succeeded. The high-risk operation window is open for 5 minutes.",
        passwordChanged: "The password changed and other sessions were revoked.",
        administratorDisabled: "The administrator was disabled; its sessions and unused tokens were revoked.",
        highRiskValidUntil: "Reauthentication valid until {{date}}",
        highRiskLocked: "High-risk operations are currently locked",
        tabs: { session: "Session", reauth: "Reauthentication", password: "Change password", admins: "Administrators", recovery: "Recovery codes", interface: "Interface" },
        session: {
          current: "Current session", idleUntil: "Idle expiry: {{date}}", absoluteUntil: "Absolute expiry: {{date}}",
          mfa: "MFA: {{value}}", completed: "complete", incomplete: "incomplete", recoveryRemaining: "Recovery codes remaining: {{count}}", refresh: "Refresh session and CSRF",
        },
        mfa: { totp: "TOTP", recoveryCode: "Recovery code" },
        reauth: { currentPassword: "Current password", mfaMethod: "MFA method", mfaCode: "MFA code", submit: "Reauthenticate" },
        password: { current: "Current password", next: "New password", mfaMethod: "MFA method", mfaCode: "MFA code", submit: "Change password and rotate sessions" },
        admins: {
          loginName: "Login name", displayName: "Name", createDisplayName: "Display name", role: "Role", status: "Status", lastLogin: "Last login",
          createTitle: "Create pending administrator", reason: "Reason", create: "Create and show one-time token",
          actionTitle: "Run high-risk operation on selected administrator", reasonPlaceholder: "Reason (10–500 characters)",
          disable: "Disable", disableConfirmTitle: "Disable administrator?", disableConfirmContent: "All sessions and unused tokens for this target will be revoked.",
          token: "Regenerate activation token", resetMfa: "Reset MFA", resetConfirmTitle: "Reset MFA?", resetConfirmContent: "The target will return to pending activation and lose its current sessions.",
        },
        recovery: {
          description: "Regenerating codes immediately revokes all previous codes. The new codes are shown once.",
          regenerate: "Regenerate recovery codes", confirmTitle: "Regenerate recovery codes?", confirmContent: "All previous recovery codes will immediately become invalid.",
        },
      },
      assets: {
        ...stage3GatewayFormEn,
        title: "Asset registry",
        description: "Gateway lifecycle management and asset state view",
        management: "Management console",
        gateway: "Gateway",
        policy: "Current provider policy",
        readFailed: "Failed to read",
        unavailable: "The current data is unavailable; stale data and internal errors are not shown.",
        retry: "Retry",
        emptyGateway: "No Gateway registered",
        emptyDriver: "No Driver registered",
        selectDriver: "Register a Driver first",
        emptyPolicy: "No current provider policy configured",
        emptyNodes: "No Relay Node matches the current filters",
        node: "Node", instanceId: "Instance ID",
        ...stage3AssetsEn, capability: "Capability", previousPage: "Previous", nextPage: "Next", errorStale: "The asset changed; refresh and try again.", errorConflict: "This operation identifier was already used by another request.", errorEndpoint: "The Gateway management address must use http://.", errorGatewayExists: "A current Gateway already exists; use Replace.", errorRetired: "A retired Gateway cannot be operated.", errorExpired: "Authentication expired; sign in again.", errorForbidden: "The current account cannot perform this operation.", errorOperation: "The operation did not complete; refresh and try again.", errorNodeConflict: "The Node changed or does not allow this operation; refresh and try again.", errorNodeConfig: "The Node configuration is invalid; check the fields and try again.", errorNodeOperation: "The Node operation did not complete; refresh and try again.",
      },
      topology: {
        title: "Node Topology",
        description: "Read-only observation of Nodes and their relationships",
        management: "Management console",
        ...stage3TopologyEn, ...stage3TopologyCapacityEn, accountQuality: "Account Quality", selectedNodeNotFound: "The selected Node does not exist",
      },
      monitoring: {
        title: "Monitoring",
        description: "Cross-domain diagnostics and evidence",
        management: "Management console",
        ...stage3TopologyEn,
        ...stage3TopologyCapacityEn,
        relayNode: "Node context",
        node: "Node",
        nodeFirstPage: "Node previous page",
        nodeNextPage: "Node next page",
        selectNode: "Select a node",
        empty: "No registered nodes",
        nodeListUnavailable: "Node list unavailable",
        nodeNotFound: "Node not found",
        nodeReadUnavailable: "Node read unavailable",
        inventoryEvidence: "Node diagnostic context",
        instanceId: "Instance ID",
        providerSnapshot: "Provider snapshot and health observation",
        gatewayContext: "Gateway binding context",
        ownershipCurrent: "Current duplicate ownership",
        ownershipHistory: "Duplicate ownership history",
        noInstance: "Select a node to view diagnostics",
        noProviders: "No Provider diagnostics to display",
        health: "Health observation",
        healthObservation: "Health observation time",
        refreshProvider: "Refresh Provider diagnostics",
        refreshBinding: "Refresh binding diagnostics",
        refreshCurrent: "Refresh current ownership",
        refreshHistory: "Refresh ownership history",
        historicalInvolvement: "Historical diagnostic involvement",
        affectedNodes: "Affected nodes",
        emptyOccurrence: "No duplicate ownership records match",
        statusSeverity: "Status / severity",
        evidenceHealth: "Evidence state",
        sourceTime: "Source time",
        evaluationTime: "Evaluation time",
        recordedTime: "Recorded time",
        firstPage: "Previous page",
        nextPage: "Next page",
        evidenceFirstPage: "Evidence previous page",
        evidenceNextPage: "Evidence next page",
        navigationTitle: "Open owning pages",
        openNodes: "Node management",
        openAccounts: "Accounts and inventory",
        openProblems: "Confirmed problems",
        openAssets: "Gateway and environment assets",
      },
      operations: {
        title: "Operations",
        description: "Durable job history and operation entry points",
        guidance: "Operations submit only the logical account identity; the server selects the physical target from the latest Node snapshot.",
        applied: "Applied", noop: "No change", unknown: "Remote outcome unknown", failed: "Failed",
        unknownTitle: "Outcome unknown", unknownDescription: "The request may or may not have been applied remotely. The system will not retry automatically to avoid duplicate operations. Inspect the current account state before issuing a new command.",
        commandId: "Operation command ID", operation: "Operation", executionState: "Execution state", resultError: "Result/error", created: "Created", updated: "Updated",
        disable: "Disable", enable: "Enable", remove: "Remove", uploadNew: "Upload New", replaceExisting: "Replace Existing",
        removeTitle: "Remove this account?", removeDescription: "This deletes the corresponding single credential file on the Node; Control cannot restore it automatically.", confirmRemove: "Confirm removal",
        replaceTitle: "Replace the existing credential?", replaceDescription: "Replace uses the remote native best-effort, last-write-wins overwrite semantics.", confirmReplace: "Confirm replacement",
        lookupPlaceholder: "Enter a Command ID to view the operation result", read: "Read operation", unknownOverride: "Outcome unknown override", overrideType: "Override type", overrideReason: "Override reason", overrideDetail: "Override detail", optionalDetail: "Optional detail", submitOverride: "Run override", confirmOverride: "Confirm override",
        uploadAccount: "Upload New Account", uploadDescription: "No existing Inventory account is required. The server generates and validates the remote target from the logical identity.", uploadProvider: "Upload New Provider", uploadEmail: "Upload New Email", accountEmail: "Account email", chooseCredential: "Choose credential JSON (max 1 MiB)",
        credentialTooLarge: "Credential file cannot exceed 1 MiB", keep: "Keep existing", set: "Set new credential", clear: "Clear credential",
        ...stage3OperationsEn, ...stage3OperationsCanonicalEn,
      },
      accounts: { title: "Accounts", description: "Account workspace", ...stage3AccountsEn, ...stage3AccountsCanonicalEn, ...stage3AccountsEnExtras, readingEvents: "Reading request history", nodeNotFound: "Account not found", requestFirstPage: "History first page", requestNextPage: "History next page" },
      jobs: { title: "Persistent jobs", description: "Read-only runtime view backed by PostgreSQL truth", management: "Management console", ...stage3JobsEn, jobId: "Job ID", operationId: "Operation ID", outbox: "Outbox", availableAt: "Available at", startedAt: "Started at", completedAt: "Completed at", createdAt: "Created at", updatedAt: "Updated at", initial: "Initial" },
      problems: { title: "Problems", description: "Read-only observation of confirmed account problems", ...stage3ProblemsEn, pageSuffix: " / page" },
      auth: {
        errors: {
          unavailable: "The request could not be completed. Try again later.",
          rateLimited: "Too many attempts. Try again later.",
          challengeExpired: "The verification expired. Sign in again.",
          lastAdministratorProtected: "The last available administrator cannot be disabled.",
          selfDisableForbidden: "The current signed-in account cannot be disabled.",
          reauthenticationRequired: "Complete reauthentication first.",
          unauthorized: "Authentication failed. Check the input and try again.",
          csrfInvalid: "The security credential changed. Refresh the session and try again.",
          requestIncomplete: "The request was not completed (request ID: {{requestId}})",
        },
        login: {
          title: "Administrator sign in",
          securityHint: "All authentication failures use one response and do not confirm account state.",
          loginName: "Login name",
          password: "Password",
          continue: "Continue",
          activationLink: "Set up a new account with an activation token",
          mfaRequired: "Second-step verification required",
          challengeValidUntil: "Challenge valid until {{date}}",
          totp: "TOTP code",
          totpMethod: "TOTP",
          recoveryCode: "Recovery code",
          verify: "Verify and sign in",
          backToPassword: "Back to password sign-in",
          recoveryWarning: "A recovery code becomes invalid after use; check the remaining count after sign-in.",
          expired: "The verification expired. Sign in again.",
        },
        bootstrap: {
          title: "Initialize Control",
          inProgress: "An incomplete initialization exists. Enter the same details to continue, or reset it with the runtime Secret.",
          newInstallation: "Create the first named super administrator.",
          secret: "Runtime Bootstrap Secret",
          loginName: "Login name",
          displayName: "Display name",
          password: "Password",
          start: "Start or continue initialization",
          resetPending: "Reset incomplete flow",
          addAuthenticator: "Add this to an authenticator now",
          totpMemoryOnly: "This TOTP configuration remains only in page memory.",
          copyUri: "Copy TOTP configuration URI",
          confirm: "Confirm and complete permanently",
          reset: "Reset",
          totpCode: "TOTP code",
        },
        activation: {
          title: "Activate administrator account",
          tokenHint: "Paste the token manually. The page never reads it from the URL, history, or browser storage.",
          token: "One-time activation token",
          start: "Start activation",
          newPassword: "New password",
          totpCode: "TOTP code",
          complete: "Complete activation",
          backToLogin: "Back to sign-in",
          leaveHint: "It will not be retained after leaving this page.",
        },
        oneTime: {
          recoveryTitle: "Save recovery codes",
          activationTitle: "Copy activation token",
          onlyShownOnce: "Shown only once",
          recoveryDescription: "Each recovery code can be used once. Save them in a password manager or another secure offline location.",
          activationDescription: "Give the token only to the intended administrator through a trusted channel; never put it in a URL.",
          validUntil: "Valid until {{date}}",
          confirmation: "I saved it securely and understand it cannot be viewed again after leaving",
          leave: "Confirm and leave",
          noCache: "This page is configured not to cache; leaving removes the material from application memory.",
        },
      },
    } satisfies TranslationResource,
  },
} satisfies Record<"zh-CN" | "en", { translation: TranslationResource }>;
